// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * SchedulingMode is the sole source of mode state (I1, INV-M1). Two values
 * are allowed; all other code must go through the methods on this type
 * rather than switching on the raw string.
 */
export enum SchedulingMode {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    ModeFullScheduling = "FULL_SCHEDULING",
    ModeTimeOnlyScheduling = "TIME_ONLY_SCHEDULING",
};
