// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ConflictService handles conflict detection and resolution.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * DetectConflicts finds all scheduling conflicts for a given semester.
 */
export function DetectConflicts(semester: string): $CancellablePromise<$models.Conflict[] | null> {
    return $Call.ByID(2264772659, semester);
}
