// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Conflict represents a scheduling conflict.
 */
export interface Conflict {
    "id": number;
    "type": string;
    "description": string;
    "severity": string;
    "detail": string;
    "info": ConflictInfoItem[] | null;
    "solutions": string[] | null;
}

/**
 * ConflictInfoItem is a key-value detail item.
 */
export interface ConflictInfoItem {
    "label": string;
    "value": string;
}

/**
 * SchedulingConfig holds the parameters for a scheduling run.
 */
export interface SchedulingConfig {
    "scope": string;
    "semester": string;
    "strategy": string;
    "iterations": number;
    "constraints": string[] | null;
}

/**
 * SchedulingResult holds the output of a scheduling run.
 */
export interface SchedulingResult {
    "totalCourses": number;
    "scheduled": number;
    "conflicts": number;
    "utilization": number;
    "logs": string[] | null;
}
