// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as models$0 from "../models/models.js";

/**
 * CheckMoveRequest is the input for CheckMove.
 */
export interface CheckMoveRequest {
    /**
     * the schedule entry being moved
     */
    "entryId": number;

    /**
     * 0-6
     */
    "newDay": number;

    /**
     * 0-10
     */
    "newPeriod": number;

    /**
     * usually 2
     */
    "newSpan": number;

    /**
     * 0 = keep current
     */
    "newClassroom": number;
}

/**
 * CheckMoveResult is the output of the move validation.
 */
export interface CheckMoveResult {
    "valid": boolean;
    "conflicts": MoveConflict[] | null;
}

/**
 * MoveConflict describes a conflict found when checking a move.
 */
export interface MoveConflict {
    /**
     * "teacher" | "room" | "class" | "locked"
     */
    "type": string;

    /**
     * Human-readable
     */
    "description": string;

    /**
     * Conflict entity name
     */
    "entity": string;

    /**
     * Optional suggestion
     */
    "suggestion": string;
}

export interface SchedulingConfig {
    "scope": string;
    "semester": string;
    "strategy": string;
    "iterations": number;

    /**
     * max solve time in seconds, default 60
     */
    "timeLimit": number;
    "constraints": string[] | null;
    "lockedSlots"?: lockedTimeSlot[] | null;
}

export interface SchedulingResult {
    "totalCourses": number;
    "scheduled": number;
    "conflicts": number;
    "utilization": number;
    "score": number;
    "scoreDetail"?: ScoreBreakdown | null;
    "logs": string[] | null;
    "error"?: string;
}

/**
 * ScoreBreakdown holds the detailed scoring result.
 */
export interface ScoreBreakdown {
    "total": number;

    /**
     * 教师偏好满足度 (0-25)
     */
    "teacherPref": number;

    /**
     * 课程间隔均匀度 (0-25)
     */
    "courseSpacing": number;

    /**
     * 教师到校天数 (0-25)
     */
    "teacherDays": number;

    /**
     * 优先低楼层 (0-25)
     */
    "lowFloorPref": number;

    /**
     * 周末避让 (0-25)
     */
    "weekendAvoid": number;
}

/**
 * LockedTimeSlot represents a globally locked time period.
 */
export interface lockedTimeSlot {
    "dayOfWeek": models$0.DayOfWeek;
    "startPeriod": models$0.Period;
    "span": number;
}
