// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * Conflict represents a scheduling conflict.
 */
export class Conflict {
    /**
     * Creates a new Conflict instance.
     * @param {Partial<Conflict>} [$$source = {}] - The source object to create the Conflict.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["id"] = 0;
        }
        if (!("type" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["type"] = "";
        }
        if (!("description" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["description"] = "";
        }
        if (!("severity" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["severity"] = "";
        }
        if (!("detail" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["detail"] = "";
        }
        if (!("info" in $$source)) {
            /**
             * @member
             * @type {ConflictInfoItem[]}
             */
            this["info"] = [];
        }
        if (!("solutions" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["solutions"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Conflict instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Conflict}
     */
    static createFrom($$source = {}) {
        const $$createField5_0 = $$createType1;
        const $$createField6_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("info" in $$parsedSource) {
            $$parsedSource["info"] = $$createField5_0($$parsedSource["info"]);
        }
        if ("solutions" in $$parsedSource) {
            $$parsedSource["solutions"] = $$createField6_0($$parsedSource["solutions"]);
        }
        return new Conflict(/** @type {Partial<Conflict>} */($$parsedSource));
    }
}

/**
 * ConflictInfoItem is a key-value detail item.
 */
export class ConflictInfoItem {
    /**
     * Creates a new ConflictInfoItem instance.
     * @param {Partial<ConflictInfoItem>} [$$source = {}] - The source object to create the ConflictInfoItem.
     */
    constructor($$source = {}) {
        if (!("label" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["label"] = "";
        }
        if (!("value" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["value"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ConflictInfoItem instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ConflictInfoItem}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ConflictInfoItem(/** @type {Partial<ConflictInfoItem>} */($$parsedSource));
    }
}

export class SchedulingConfig {
    /**
     * Creates a new SchedulingConfig instance.
     * @param {Partial<SchedulingConfig>} [$$source = {}] - The source object to create the SchedulingConfig.
     */
    constructor($$source = {}) {
        if (!("scope" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["scope"] = "";
        }
        if (!("semester" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["semester"] = "";
        }
        if (!("strategy" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["strategy"] = "";
        }
        if (!("iterations" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["iterations"] = 0;
        }
        if (!("constraints" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["constraints"] = [];
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {lockedTimeSlot[] | undefined}
             */
            this["lockedSlots"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SchedulingConfig instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {SchedulingConfig}
     */
    static createFrom($$source = {}) {
        const $$createField4_0 = $$createType2;
        const $$createField5_0 = $$createType4;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("constraints" in $$parsedSource) {
            $$parsedSource["constraints"] = $$createField4_0($$parsedSource["constraints"]);
        }
        if ("lockedSlots" in $$parsedSource) {
            $$parsedSource["lockedSlots"] = $$createField5_0($$parsedSource["lockedSlots"]);
        }
        return new SchedulingConfig(/** @type {Partial<SchedulingConfig>} */($$parsedSource));
    }
}

export class SchedulingResult {
    /**
     * Creates a new SchedulingResult instance.
     * @param {Partial<SchedulingResult>} [$$source = {}] - The source object to create the SchedulingResult.
     */
    constructor($$source = {}) {
        if (!("totalCourses" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["totalCourses"] = 0;
        }
        if (!("scheduled" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["scheduled"] = 0;
        }
        if (!("conflicts" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["conflicts"] = 0;
        }
        if (!("utilization" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["utilization"] = 0;
        }
        if (!("score" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["score"] = 0;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {ScoreBreakdown | null | undefined}
             */
            this["scoreDetail"] = undefined;
        }
        if (!("logs" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["logs"] = [];
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["error"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SchedulingResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {SchedulingResult}
     */
    static createFrom($$source = {}) {
        const $$createField5_0 = $$createType6;
        const $$createField6_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("scoreDetail" in $$parsedSource) {
            $$parsedSource["scoreDetail"] = $$createField5_0($$parsedSource["scoreDetail"]);
        }
        if ("logs" in $$parsedSource) {
            $$parsedSource["logs"] = $$createField6_0($$parsedSource["logs"]);
        }
        return new SchedulingResult(/** @type {Partial<SchedulingResult>} */($$parsedSource));
    }
}

/**
 * ScoreBreakdown holds the detailed scoring result.
 */
export class ScoreBreakdown {
    /**
     * Creates a new ScoreBreakdown instance.
     * @param {Partial<ScoreBreakdown>} [$$source = {}] - The source object to create the ScoreBreakdown.
     */
    constructor($$source = {}) {
        if (!("total" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["total"] = 0;
        }
        if (!("teacherPref" in $$source)) {
            /**
             * 教师偏好满足度 (0-25)
             * @member
             * @type {number}
             */
            this["teacherPref"] = 0;
        }
        if (!("courseSpacing" in $$source)) {
            /**
             * 课程间隔均匀度 (0-25)
             * @member
             * @type {number}
             */
            this["courseSpacing"] = 0;
        }
        if (!("teacherDays" in $$source)) {
            /**
             * 教师到校天数 (0-25)
             * @member
             * @type {number}
             */
            this["teacherDays"] = 0;
        }
        if (!("lowFloorPref" in $$source)) {
            /**
             * 老教师低楼层 (0-25)
             * @member
             * @type {number}
             */
            this["lowFloorPref"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ScoreBreakdown instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ScoreBreakdown}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ScoreBreakdown(/** @type {Partial<ScoreBreakdown>} */($$parsedSource));
    }
}

/**
 * LockedTimeSlot represents a globally locked time period.
 */
export class lockedTimeSlot {
    /**
     * Creates a new lockedTimeSlot instance.
     * @param {Partial<lockedTimeSlot>} [$$source = {}] - The source object to create the lockedTimeSlot.
     */
    constructor($$source = {}) {
        if (!("dayOfWeek" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["dayOfWeek"] = 0;
        }
        if (!("startPeriod" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["startPeriod"] = 0;
        }
        if (!("span" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["span"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new lockedTimeSlot instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {lockedTimeSlot}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new lockedTimeSlot(/** @type {Partial<lockedTimeSlot>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = ConflictInfoItem.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = $Create.Array($Create.Any);
const $$createType3 = lockedTimeSlot.createFrom;
const $$createType4 = $Create.Array($$createType3);
const $$createType5 = ScoreBreakdown.createFrom;
const $$createType6 = $Create.Nullable($$createType5);
