// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * MoveService validates schedule entry moves for drag-and-drop micro-adjustment.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * CheckMove validates whether a schedule entry can be moved to a new time/room.
 */
export function CheckMove(req: $models.CheckMoveRequest): $CancellablePromise<$models.CheckMoveResult | null> {
    return $Call.ByID(313766329, req);
}

/**
 * MoveEntry executes a validated move by updating the schedule entry.
 */
export function MoveEntry(req: $models.CheckMoveRequest): $CancellablePromise<void> {
    return $Call.ByID(267007231, req);
}
