// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ResourceService handles CRUD for teachers, classrooms, courses, and class groups.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as models$0 from "../models/models.js";

export function CreateClassGroup(c: models$0.ClassGroup): $CancellablePromise<void> {
    return $Call.ByID(2378452998, c);
}

export function CreateClassroom(c: models$0.Classroom): $CancellablePromise<void> {
    return $Call.ByID(4230659480, c);
}

export function CreateCourse(c: models$0.Course): $CancellablePromise<void> {
    return $Call.ByID(986378328, c);
}

export function CreateTeacher(t: models$0.Teacher): $CancellablePromise<void> {
    return $Call.ByID(118883989, t);
}

export function DeleteClassGroup(id: number): $CancellablePromise<void> {
    return $Call.ByID(2583998629, id);
}

export function DeleteClassroom(id: number): $CancellablePromise<void> {
    return $Call.ByID(21048417, id);
}

export function DeleteCourse(id: number): $CancellablePromise<void> {
    return $Call.ByID(2971047935, id);
}

export function DeleteTeacher(id: number): $CancellablePromise<void> {
    return $Call.ByID(1946163876, id);
}

export function GetClassGroups(): $CancellablePromise<models$0.ClassGroup[] | null> {
    return $Call.ByID(1591698177);
}

export function GetClassrooms(): $CancellablePromise<models$0.Classroom[] | null> {
    return $Call.ByID(943463975);
}

export function GetCourses(): $CancellablePromise<models$0.Course[] | null> {
    return $Call.ByID(3364788411);
}

export function GetScheduleEntries(semester: string): $CancellablePromise<models$0.ScheduleEntry[] | null> {
    return $Call.ByID(1801965054, semester);
}

export function GetTeachers(): $CancellablePromise<models$0.Teacher[] | null> {
    return $Call.ByID(1580423400);
}

export function UpdateClassGroup(c: models$0.ClassGroup): $CancellablePromise<void> {
    return $Call.ByID(3147255191, c);
}

export function UpdateClassroom(c: models$0.Classroom): $CancellablePromise<void> {
    return $Call.ByID(662507967, c);
}

export function UpdateCourse(c: models$0.Course): $CancellablePromise<void> {
    return $Call.ByID(1882758153, c);
}

export function UpdateTeacher(t: models$0.Teacher): $CancellablePromise<void> {
    return $Call.ByID(3029258410, t);
}
