// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ResourceService handles CRUD for teachers, classrooms, courses, and class groups.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as models$0 from "../models/models.js";

/**
 * @param {models$0.ClassGroup} c
 * @returns {$CancellablePromise<void>}
 */
export function CreateClassGroup(c) {
    return $Call.ByID(2378452998, c);
}

/**
 * @param {models$0.Classroom} c
 * @returns {$CancellablePromise<void>}
 */
export function CreateClassroom(c) {
    return $Call.ByID(4230659480, c);
}

/**
 * @param {models$0.Course} c
 * @returns {$CancellablePromise<void>}
 */
export function CreateCourse(c) {
    return $Call.ByID(986378328, c);
}

/**
 * @param {models$0.Teacher} t
 * @returns {$CancellablePromise<void>}
 */
export function CreateTeacher(t) {
    return $Call.ByID(118883989, t);
}

/**
 * @param {number} id
 * @returns {$CancellablePromise<void>}
 */
export function DeleteClassGroup(id) {
    return $Call.ByID(2583998629, id);
}

/**
 * @param {number} id
 * @returns {$CancellablePromise<void>}
 */
export function DeleteClassroom(id) {
    return $Call.ByID(21048417, id);
}

/**
 * @param {number} id
 * @returns {$CancellablePromise<void>}
 */
export function DeleteCourse(id) {
    return $Call.ByID(2971047935, id);
}

/**
 * @param {number} id
 * @returns {$CancellablePromise<void>}
 */
export function DeleteTeacher(id) {
    return $Call.ByID(1946163876, id);
}

/**
 * @returns {$CancellablePromise<models$0.ClassGroup[]>}
 */
export function GetClassGroups() {
    return $Call.ByID(1591698177).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * @returns {$CancellablePromise<models$0.Classroom[]>}
 */
export function GetClassrooms() {
    return $Call.ByID(943463975).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * @returns {$CancellablePromise<models$0.Course[]>}
 */
export function GetCourses() {
    return $Call.ByID(3364788411).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType5($result);
    }));
}

/**
 * @param {string} semester
 * @returns {$CancellablePromise<models$0.ScheduleEntry[]>}
 */
export function GetScheduleEntries(semester) {
    return $Call.ByID(1801965054, semester).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType7($result);
    }));
}

/**
 * @returns {$CancellablePromise<models$0.Teacher[]>}
 */
export function GetTeachers() {
    return $Call.ByID(1580423400).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType9($result);
    }));
}

/**
 * @param {models$0.ClassGroup} c
 * @returns {$CancellablePromise<void>}
 */
export function UpdateClassGroup(c) {
    return $Call.ByID(3147255191, c);
}

/**
 * @param {models$0.Classroom} c
 * @returns {$CancellablePromise<void>}
 */
export function UpdateClassroom(c) {
    return $Call.ByID(662507967, c);
}

/**
 * @param {models$0.Course} c
 * @returns {$CancellablePromise<void>}
 */
export function UpdateCourse(c) {
    return $Call.ByID(1882758153, c);
}

/**
 * @param {models$0.Teacher} t
 * @returns {$CancellablePromise<void>}
 */
export function UpdateTeacher(t) {
    return $Call.ByID(3029258410, t);
}

// Private type creation functions
const $$createType0 = models$0.ClassGroup.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = models$0.Classroom.createFrom;
const $$createType3 = $Create.Array($$createType2);
const $$createType4 = models$0.Course.createFrom;
const $$createType5 = $Create.Array($$createType4);
const $$createType6 = models$0.ScheduleEntry.createFrom;
const $$createType7 = $Create.Array($$createType6);
const $$createType8 = models$0.Teacher.createFrom;
const $$createType9 = $Create.Array($$createType8);
