// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * SchedulingService handles the automated scheduling algorithm.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * RunScheduling executes the scheduling algorithm.
 * This is a simplified greedy algorithm that can be enhanced later.
 */
export function RunScheduling(config: $models.SchedulingConfig): $CancellablePromise<$models.SchedulingResult | null> {
    return $Call.ByID(2776352694, config);
}
