// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * SnapshotService manages schedule validation snapshots.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as models$0 from "../models/models.js";

/**
 * CreateManualSnapshot generates a snapshot on user request (after micro-adjustment).
 */
export function CreateManualSnapshot(semester: string, dept: string, entries: models$0.ScheduleEntry[] | null, teachers: models$0.Teacher[] | null, classrooms: models$0.Classroom[] | null, constraints: string[] | null, conflictCount: number): $CancellablePromise<models$0.ScheduleSnapshot | null> {
    return $Call.ByID(2433123319, semester, dept, entries, teachers, classrooms, constraints, conflictCount);
}

/**
 * CreateSnapshot generates a snapshot from a scheduling result.
 */
export function CreateSnapshot(semester: string, dept: string, trigger: string, solver: string, entries: models$0.ScheduleEntry[] | null, teachers: models$0.Teacher[] | null, classrooms: models$0.Classroom[] | null, constraints: string[] | null, solveTimeMs: number, conflictCount: number): $CancellablePromise<models$0.ScheduleSnapshot | null> {
    return $Call.ByID(162352929, semester, dept, trigger, solver, entries, teachers, classrooms, constraints, solveTimeMs, conflictCount);
}

/**
 * DeleteSnapshot removes a snapshot and its details.
 */
export function DeleteSnapshot(id: number): $CancellablePromise<void> {
    return $Call.ByID(1178185690, id);
}

/**
 * GetSnapshotWithDetails returns a single snapshot with its details preloaded.
 */
export function GetSnapshotWithDetails(id: number): $CancellablePromise<models$0.ScheduleSnapshot | null> {
    return $Call.ByID(2503829355, id);
}

/**
 * GetSnapshots returns all snapshots for a semester.
 */
export function GetSnapshots(semester: string): $CancellablePromise<models$0.ScheduleSnapshot[] | null> {
    return $Call.ByID(3577178096, semester);
}
