// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * SnapshotService manages schedule validation snapshots.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as models$0 from "../models/models.js";

/**
 * CreateManualSnapshot generates a snapshot from the current schedule in the database.
 * @param {string} semester
 * @returns {$CancellablePromise<models$0.ScheduleSnapshot | null>}
 */
export function CreateManualSnapshot(semester) {
    return $Call.ByID(2433123319, semester).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * CreateSnapshot generates a snapshot from a scheduling result.
 * @param {string} semester
 * @param {string} dept
 * @param {string} trigger
 * @param {string} solver
 * @param {models$0.ScheduleEntry[]} entries
 * @param {models$0.Teacher[]} teachers
 * @param {models$0.Classroom[]} classrooms
 * @param {string[]} constraints
 * @param {number} solveTimeMs
 * @param {number} conflictCount
 * @returns {$CancellablePromise<models$0.ScheduleSnapshot | null>}
 */
export function CreateSnapshot(semester, dept, trigger, solver, entries, teachers, classrooms, constraints, solveTimeMs, conflictCount) {
    return $Call.ByID(162352929, semester, dept, trigger, solver, entries, teachers, classrooms, constraints, solveTimeMs, conflictCount).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * DeleteSnapshot removes a snapshot and its details.
 * @param {number} id
 * @returns {$CancellablePromise<void>}
 */
export function DeleteSnapshot(id) {
    return $Call.ByID(1178185690, id);
}

/**
 * GetSnapshotWithDetails returns a single snapshot with its details preloaded.
 * @param {number} id
 * @returns {$CancellablePromise<models$0.ScheduleSnapshot | null>}
 */
export function GetSnapshotWithDetails(id) {
    return $Call.ByID(2503829355, id).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * GetSnapshots returns all snapshots for a semester.
 * @param {string} semester
 * @returns {$CancellablePromise<models$0.ScheduleSnapshot[]>}
 */
export function GetSnapshots(semester) {
    return $Call.ByID(3577178096, semester).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

// Private type creation functions
const $$createType0 = models$0.ScheduleSnapshot.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = $Create.Array($$createType0);
