// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export type {
    ClassGroup,
    Classroom,
    Course,
    ScheduleEntry,
    Teacher
} from "./models.js";
