// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as gorm$0 from "../../gorm.io/gorm/models.js";

/**
 * ClassGroup represents a student class/group (e.g., 计算机2301).
 */
export interface ClassGroup {
    "ID": number;
    "CreatedAt": string;
    "UpdatedAt": string;
    "DeletedAt": gorm$0.DeletedAt;
    "code": string;
    "name": string;
    "dept": string;

    /**
     * 入学年份, e.g. 2023
     */
    "grade": number;

    /**
     * 学生人数
     */
    "students": number;
}

/**
 * Classroom represents a physical room for teaching.
 */
export interface Classroom {
    "ID": number;
    "CreatedAt": string;
    "UpdatedAt": string;
    "DeletedAt": gorm$0.DeletedAt;
    "code": string;
    "name": string;
    "building": string;
    "capacity": number;

    /**
     * 普通教室, 实验室, 体育馆, etc.
     */
    "type": string;
    "status": string;
}

/**
 * Course represents a course in the curriculum.
 */
export interface Course {
    "ID": number;
    "CreatedAt": string;
    "UpdatedAt": string;
    "DeletedAt": gorm$0.DeletedAt;
    "code": string;
    "name": string;
    "dept": string;
    "credit": number;

    /**
     * 专业必修, 全校选修, etc.
     */
    "type": string;
    "hours": number;
}

/**
 * ScheduleEntry represents a single scheduled course slot.
 */
export interface ScheduleEntry {
    "ID": number;
    "CreatedAt": string;
    "UpdatedAt": string;
    "DeletedAt": gorm$0.DeletedAt;
    "courseId": number;
    "teacherId": number;
    "classroomId": number;
    "semester": string;

    /**
     * 0=Mon ... 6=Sun
     */
    "dayOfWeek": number;

    /**
     * 0-9
     */
    "startPeriod": number;

    /**
     * consecutive periods
     */
    "span": number;
    "weeks": string;

    /**
     * Associations
     */
    "course"?: Course;
    "teacher"?: Teacher;
    "classroom"?: Classroom;
}

/**
 * Teacher represents a teaching staff member.
 */
export interface Teacher {
    "ID": number;
    "CreatedAt": string;
    "UpdatedAt": string;
    "DeletedAt": gorm$0.DeletedAt;
    "code": string;
    "name": string;
    "dept": string;

    /**
     * 教授, 副教授, 讲师
     */
    "title": string;

    /**
     * active, inactive
     */
    "status": string;
}
