// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as gorm$0 from "../../gorm.io/gorm/models.js";

/**
 * ClassGroup represents a student class/group (e.g., 计算机2301).
 */
export class ClassGroup {
    /**
     * Creates a new ClassGroup instance.
     * @param {Partial<ClassGroup>} [$$source = {}] - The source object to create the ClassGroup.
     */
    constructor($$source = {}) {
        if (!("ID" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["ID"] = 0;
        }
        if (!("CreatedAt" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["CreatedAt"] = "0001-01-01T00:00:00.000Z";
        }
        if (!("UpdatedAt" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["UpdatedAt"] = "0001-01-01T00:00:00.000Z";
        }
        if (!("DeletedAt" in $$source)) {
            /**
             * @member
             * @type {gorm$0.DeletedAt}
             */
            this["DeletedAt"] = null;
        }
        if (!("code" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["code"] = "";
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("dept" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["dept"] = "";
        }
        if (!("grade" in $$source)) {
            /**
             * 入学年份, e.g. 2023
             * @member
             * @type {number}
             */
            this["grade"] = 0;
        }
        if (!("students" in $$source)) {
            /**
             * 学生人数
             * @member
             * @type {number}
             */
            this["students"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ClassGroup instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ClassGroup}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ClassGroup(/** @type {Partial<ClassGroup>} */($$parsedSource));
    }
}

/**
 * Classroom represents a physical room for teaching.
 */
export class Classroom {
    /**
     * Creates a new Classroom instance.
     * @param {Partial<Classroom>} [$$source = {}] - The source object to create the Classroom.
     */
    constructor($$source = {}) {
        if (!("ID" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["ID"] = 0;
        }
        if (!("CreatedAt" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["CreatedAt"] = "0001-01-01T00:00:00.000Z";
        }
        if (!("UpdatedAt" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["UpdatedAt"] = "0001-01-01T00:00:00.000Z";
        }
        if (!("DeletedAt" in $$source)) {
            /**
             * @member
             * @type {gorm$0.DeletedAt}
             */
            this["DeletedAt"] = null;
        }
        if (!("code" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["code"] = "";
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("building" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["building"] = "";
        }
        if (!("floor" in $$source)) {
            /**
             * 楼层号
             * @member
             * @type {number}
             */
            this["floor"] = 0;
        }
        if (!("capacity" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["capacity"] = 0;
        }
        if (!("type" in $$source)) {
            /**
             * 普通教室, 实验室, 体育馆, etc.
             * @member
             * @type {string}
             */
            this["type"] = "";
        }
        if (!("status" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["status"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Classroom instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Classroom}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Classroom(/** @type {Partial<Classroom>} */($$parsedSource));
    }
}

/**
 * Course represents a course in the curriculum.
 */
export class Course {
    /**
     * Creates a new Course instance.
     * @param {Partial<Course>} [$$source = {}] - The source object to create the Course.
     */
    constructor($$source = {}) {
        if (!("ID" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["ID"] = 0;
        }
        if (!("CreatedAt" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["CreatedAt"] = "0001-01-01T00:00:00.000Z";
        }
        if (!("UpdatedAt" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["UpdatedAt"] = "0001-01-01T00:00:00.000Z";
        }
        if (!("DeletedAt" in $$source)) {
            /**
             * @member
             * @type {gorm$0.DeletedAt}
             */
            this["DeletedAt"] = null;
        }
        if (!("code" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["code"] = "";
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("dept" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["dept"] = "";
        }
        if (!("credit" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["credit"] = 0;
        }
        if (!("type" in $$source)) {
            /**
             * 专业必修, 全校选修, etc.
             * @member
             * @type {string}
             */
            this["type"] = "";
        }
        if (!("hours" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["hours"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Course instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Course}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Course(/** @type {Partial<Course>} */($$parsedSource));
    }
}

/**
 * ScheduleEntry represents a single scheduled course slot.
 */
export class ScheduleEntry {
    /**
     * Creates a new ScheduleEntry instance.
     * @param {Partial<ScheduleEntry>} [$$source = {}] - The source object to create the ScheduleEntry.
     */
    constructor($$source = {}) {
        if (!("ID" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["ID"] = 0;
        }
        if (!("CreatedAt" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["CreatedAt"] = "0001-01-01T00:00:00.000Z";
        }
        if (!("UpdatedAt" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["UpdatedAt"] = "0001-01-01T00:00:00.000Z";
        }
        if (!("DeletedAt" in $$source)) {
            /**
             * @member
             * @type {gorm$0.DeletedAt}
             */
            this["DeletedAt"] = null;
        }
        if (!("courseId" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["courseId"] = 0;
        }
        if (!("teacherId" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["teacherId"] = 0;
        }
        if (!("classroomId" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["classroomId"] = 0;
        }
        if (!("classGroupId" in $$source)) {
            /**
             * nullable FK, 用于班级冲突检测
             * @member
             * @type {number | null}
             */
            this["classGroupId"] = null;
        }
        if (!("semester" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["semester"] = "";
        }
        if (!("dayOfWeek" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["dayOfWeek"] = 0;
        }
        if (!("startPeriod" in $$source)) {
            /**
             * 0-10 (对应第1-11节)
             * @member
             * @type {number}
             */
            this["startPeriod"] = 0;
        }
        if (!("span" in $$source)) {
            /**
             * consecutive periods
             * @member
             * @type {number}
             */
            this["span"] = 0;
        }
        if (!("weeks" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["weeks"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * Associations
             * @member
             * @type {Course | undefined}
             */
            this["course"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {Teacher | undefined}
             */
            this["teacher"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {Classroom | undefined}
             */
            this["classroom"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {ClassGroup | null | undefined}
             */
            this["classGroup"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ScheduleEntry instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ScheduleEntry}
     */
    static createFrom($$source = {}) {
        const $$createField13_0 = $$createType0;
        const $$createField14_0 = $$createType1;
        const $$createField15_0 = $$createType2;
        const $$createField16_0 = $$createType4;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("course" in $$parsedSource) {
            $$parsedSource["course"] = $$createField13_0($$parsedSource["course"]);
        }
        if ("teacher" in $$parsedSource) {
            $$parsedSource["teacher"] = $$createField14_0($$parsedSource["teacher"]);
        }
        if ("classroom" in $$parsedSource) {
            $$parsedSource["classroom"] = $$createField15_0($$parsedSource["classroom"]);
        }
        if ("classGroup" in $$parsedSource) {
            $$parsedSource["classGroup"] = $$createField16_0($$parsedSource["classGroup"]);
        }
        return new ScheduleEntry(/** @type {Partial<ScheduleEntry>} */($$parsedSource));
    }
}

/**
 * Teacher represents a teaching staff member.
 */
export class Teacher {
    /**
     * Creates a new Teacher instance.
     * @param {Partial<Teacher>} [$$source = {}] - The source object to create the Teacher.
     */
    constructor($$source = {}) {
        if (!("ID" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["ID"] = 0;
        }
        if (!("CreatedAt" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["CreatedAt"] = "0001-01-01T00:00:00.000Z";
        }
        if (!("UpdatedAt" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["UpdatedAt"] = "0001-01-01T00:00:00.000Z";
        }
        if (!("DeletedAt" in $$source)) {
            /**
             * @member
             * @type {gorm$0.DeletedAt}
             */
            this["DeletedAt"] = null;
        }
        if (!("code" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["code"] = "";
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("dept" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["dept"] = "";
        }
        if (!("title" in $$source)) {
            /**
             * 教授, 副教授, 讲师
             * @member
             * @type {string}
             */
            this["title"] = "";
        }
        if (!("status" in $$source)) {
            /**
             * active, inactive
             * @member
             * @type {string}
             */
            this["status"] = "";
        }
        if (!("preferNoEarly" in $$source)) {
            /**
             * Soft constraint preferences
             * 避免早课（1-2节）
             * @member
             * @type {boolean}
             */
            this["preferNoEarly"] = false;
        }
        if (!("preferNoLate" in $$source)) {
            /**
             * 避免晚课（7-8节及晚上）
             * @member
             * @type {boolean}
             */
            this["preferNoLate"] = false;
        }
        if (!("maxDaysPerWeek" in $$source)) {
            /**
             * 每周最多到校天数
             * @member
             * @type {number}
             */
            this["maxDaysPerWeek"] = 0;
        }
        if (!("preferLowFloor" in $$source)) {
            /**
             * 优先低楼层（老教师）
             * @member
             * @type {boolean}
             */
            this["preferLowFloor"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Teacher instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Teacher}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Teacher(/** @type {Partial<Teacher>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = Course.createFrom;
const $$createType1 = Teacher.createFrom;
const $$createType2 = Classroom.createFrom;
const $$createType3 = ClassGroup.createFrom;
const $$createType4 = $Create.Nullable($$createType3);
