// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as models$0 from "../models/models.js";

/**
 * CheckMoveRequest is the input for CheckMove.
 */
export interface CheckMoveRequest {
    /**
     * the schedule entry being moved
     */
    "entryId": number;

    /**
     * 0-6
     */
    "newDay": number;

    /**
     * 0-10
     */
    "newPeriod": number;

    /**
     * usually 2
     */
    "newSpan": number;

    /**
     * 0 = keep current
     */
    "newClassroom": number;
}

/**
 * CheckMoveResult is the output of the move validation.
 */
export interface CheckMoveResult {
    "valid": boolean;
    "conflicts": MoveConflict[] | null;
}

/**
 * MoveAndScoreResult is the output of MoveEntryAndScore.
 */
export interface MoveAndScoreResult {
    "success": boolean;
    "error"?: string;
    "beforeScore": number;
    "newScore": number;
    "delta": number;
    "scoreDetail"?: ScoreBreakdown | null;
}

/**
 * MoveConflict describes a conflict found when checking a move.
 */
export interface MoveConflict {
    /**
     * "teacher" | "room" | "class" | "locked"
     */
    "type": string;

    /**
     * Human-readable
     */
    "description": string;

    /**
     * Conflict entity name
     */
    "entity": string;

    /**
     * Optional suggestion
     */
    "suggestion": string;
}

/**
 * ScheduleProgress records a scheduling phase milestone.
 */
export interface ScheduleProgress {
    /**
     * 0-100 percentage
     */
    "progress": number;

    /**
     * human-readable phase name
     */
    "stage": string;
}

export interface SchedulingConfig {
    "scope": string;
    "strategy": string;
    "iterations": number;

    /**
     * max solve time in seconds, default 60
     */
    "timeLimit": number;
    "constraints": string[] | null;

    /**
     * JSON string, avoids Wails enum serialization pitfall
     */
    "lockedSlotsJson"?: string;

    /**
     * active semester ID
     */
    "semesterId"?: number;

    /**
     * per-constraint weights (0-100)
     */
    "constraintWeights"?: { [_ in string]?: number } | null;
}

export interface SchedulingResult {
    "totalCourses": number;
    "scheduled": number;
    "tasksScheduled": number;
    "conflicts": number;
    "teacherConflicts": number;
    "roomConflicts": number;
    "classConflicts": number;
    "utilization": number;
    "score": number;
    "scoreDetail"?: ScoreBreakdown | null;
    "logs": string[] | null;
    "error"?: string;
    "progressHistory"?: ScheduleProgress[] | null;
}

/**
 * ScoreBreakdown holds the detailed scoring result.
 */
export interface ScoreBreakdown {
    "total": number;

    /**
     * 教师偏好满足度
     */
    "teacherPref": number;

    /**
     * 课程间隔均匀度
     */
    "courseSpacing": number;

    /**
     * 教师到校天数
     */
    "teacherDays": number;

    /**
     * 优先低楼层
     */
    "lowFloorPref": number;

    /**
     * 周末避让
     */
    "weekendAvoid": number;

    /**
     * 体育课时段偏好
     */
    "pePeriodPref": number;
    "studentFatigue": number;
    "perCategoryMax": number;
    "enabledCategoryCount": number;

    /**
     * v0.5.2: placement completeness fields.
     * Total keeps its v0.4 semantics (sum of 7 soft-constraint categories).
     * FinalTotal is Total scaled by a completeness factor so under-placed schedules
     * receive a lower published score. When ExpectedSessions==0 or PlacedSessions
     * equals it, FinalTotal == Total (v0.4-compatible round-trip).
     */
    "placedSessions"?: number;
    "expectedSessions"?: number;

    /**
     * ratio in [0,1]
     */
    "completeness"?: number;
    "finalTotal": number;
}

/**
 * ScoringContext bundles all data needed for schedule quality evaluation.
 * It is the single source of truth for scoring — no call site should derive
 * constraints or sports course IDs independently.
 * 
 * Version history:
 * 
 * 	v1 — initial version with 7 soft constraints (teacher_preference,
 * 	      course_dispersed, teacher_days_limit, low_floor_preference,
 * 	      avoid_saturday/avoid_sunday, pe_preferred_periods, student_fatigue)
 * 	v2 — v0.5.2: added ExpectedTotalSessions for placement-completeness scaling
 * 	      of FinalTotal. Total field semantics unchanged (Stable Core compat).
 */
export interface ScoringContext {
    "version": number;
    "enabledConstraints": string[] | null;
}

/**
 * SnapshotCompareResult holds the diff between two schedule snapshots.
 */
export interface SnapshotCompareResult {
    "a": models$0.ScheduleSnapshot | null;
    "b": models$0.ScheduleSnapshot | null;
    "scoreDelta": number;

    /**
     * +1: fail->pass, -1: pass->fail, 0: unchanged
     */
    "conflictDelta": number;
    "entryDelta": number;
    "teacherDiffs": TeacherSnapshotDiff[] | null;
}

/**
 * TeacherSnapshotDiff summarizes per-teacher changes between two snapshots.
 */
export interface TeacherSnapshotDiff {
    "code": string;
    "name": string;
    "entryDelta": number;
    "earlyDelta": number;
    "lateDelta": number;
    "daysActualA": number;
    "daysActualB": number;
    "daysTarget": number;
    "avgFloorDelta": number;

    /**
     * improved / regressed / unchanged / added / removed
     */
    "status": string;
}

/**
 * TeacherWorkloadInfo holds per-teacher workload analysis (post-hoc, does not affect scoring).
 */
export interface TeacherWorkloadInfo {
    "teacherId": number;
    "teacherName": string;
    "totalSessions": number;

    /**
     * 7 elements, sessions per day Mon-Sun
     */
    "dailyDistribution": number[] | null;
    "busyDays": number;
    "maxDaily": number;

    /**
     * min across all 7 days (may be 0)
     */
    "minDaily": number;

    /**
     * 0-100
     */
    "balanceScore": number;
    "suggestion": string;
}
