// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as models$0 from "../models/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as types$0 from "../scheduling/types/models.js";

/**
 * CheckMoveRequest is the input for CheckMove.
 */
export class CheckMoveRequest {
    /**
     * Creates a new CheckMoveRequest instance.
     * @param {Partial<CheckMoveRequest>} [$$source = {}] - The source object to create the CheckMoveRequest.
     */
    constructor($$source = {}) {
        if (!("entryId" in $$source)) {
            /**
             * the schedule entry being moved
             * @member
             * @type {number}
             */
            this["entryId"] = 0;
        }
        if (!("newDay" in $$source)) {
            /**
             * 0-6
             * @member
             * @type {number}
             */
            this["newDay"] = 0;
        }
        if (!("newPeriod" in $$source)) {
            /**
             * 0-10
             * @member
             * @type {number}
             */
            this["newPeriod"] = 0;
        }
        if (!("newSpan" in $$source)) {
            /**
             * usually 2
             * @member
             * @type {number}
             */
            this["newSpan"] = 0;
        }
        if (!("newClassroom" in $$source)) {
            /**
             * 0 = keep current
             * @member
             * @type {number}
             */
            this["newClassroom"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CheckMoveRequest instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {CheckMoveRequest}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new CheckMoveRequest(/** @type {Partial<CheckMoveRequest>} */($$parsedSource));
    }
}

/**
 * CheckMoveResult is the output of the move validation.
 */
export class CheckMoveResult {
    /**
     * Creates a new CheckMoveResult instance.
     * @param {Partial<CheckMoveResult>} [$$source = {}] - The source object to create the CheckMoveResult.
     */
    constructor($$source = {}) {
        if (!("valid" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["valid"] = false;
        }
        if (!("conflicts" in $$source)) {
            /**
             * @member
             * @type {MoveConflict[]}
             */
            this["conflicts"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CheckMoveResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {CheckMoveResult}
     */
    static createFrom($$source = {}) {
        const $$createField1_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("conflicts" in $$parsedSource) {
            $$parsedSource["conflicts"] = $$createField1_0($$parsedSource["conflicts"]);
        }
        return new CheckMoveResult(/** @type {Partial<CheckMoveResult>} */($$parsedSource));
    }
}

/**
 * EnrichedScheduleEntry is a flattened read-model for frontend consumption.
 * It denormalises schedule_entries with their related entities (course, teacher,
 * classroom, building, teaching task, class groups) into a single struct.
 * 
 * Phase 0 (v0.6.0-pre): populated from the legacy schedule_entries table.
 * ScheduleVersionID is always 0 — the legacy table has no version linkage.
 * A future phase will wire this to schedule_version_entries instead.
 */
export class EnrichedScheduleEntry {
    /**
     * Creates a new EnrichedScheduleEntry instance.
     * @param {Partial<EnrichedScheduleEntry>} [$$source = {}] - The source object to create the EnrichedScheduleEntry.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["id"] = 0;
        }
        if (!("dayOfWeek" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["dayOfWeek"] = 0;
        }
        if (!("startPeriod" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["startPeriod"] = 0;
        }
        if (!("span" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["span"] = 0;
        }
        if (!("weeks" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["weeks"] = "";
        }
        if (!("teacherId" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["teacherId"] = 0;
        }
        if (!("teacherName" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["teacherName"] = "";
        }
        if (!("courseId" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["courseId"] = 0;
        }
        if (!("courseName" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["courseName"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["courseCode"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | undefined}
             */
            this["courseCredit"] = undefined;
        }
        if (!("classGroupIds" in $$source)) {
            /**
             * @member
             * @type {number[]}
             */
            this["classGroupIds"] = [];
        }
        if (!("classGroupNames" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["classGroupNames"] = [];
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | null | undefined}
             */
            this["classroomId"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | null | undefined}
             */
            this["classroomName"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | null | undefined}
             */
            this["classroomFloor"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | null | undefined}
             */
            this["classroomType"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | null | undefined}
             */
            this["classroomCode"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | null | undefined}
             */
            this["buildingName"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | null | undefined}
             */
            this["teachingTaskId"] = undefined;
        }
        if (!("semesterId" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["semesterId"] = 0;
        }
        if (!("scheduleVersionId" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["scheduleVersionId"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new EnrichedScheduleEntry instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {EnrichedScheduleEntry}
     */
    static createFrom($$source = {}) {
        const $$createField11_0 = $$createType2;
        const $$createField12_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("classGroupIds" in $$parsedSource) {
            $$parsedSource["classGroupIds"] = $$createField11_0($$parsedSource["classGroupIds"]);
        }
        if ("classGroupNames" in $$parsedSource) {
            $$parsedSource["classGroupNames"] = $$createField12_0($$parsedSource["classGroupNames"]);
        }
        return new EnrichedScheduleEntry(/** @type {Partial<EnrichedScheduleEntry>} */($$parsedSource));
    }
}

export class EntryDiff {
    /**
     * Creates a new EntryDiff instance.
     * @param {Partial<EntryDiff>} [$$source = {}] - The source object to create the EntryDiff.
     */
    constructor($$source = {}) {
        if (!("type" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["type"] = "";
        }
        if (!("course" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["course"] = "";
        }
        if (!("teacher" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["teacher"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | undefined}
             */
            this["taskId"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | undefined}
             */
            this["oldDay"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | undefined}
             */
            this["oldStart"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | undefined}
             */
            this["newDay"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | undefined}
             */
            this["newStart"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new EntryDiff instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {EntryDiff}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new EntryDiff(/** @type {Partial<EntryDiff>} */($$parsedSource));
    }
}

/**
 * MoveAndScoreResult is the output of MoveEntryAndScore.
 */
export class MoveAndScoreResult {
    /**
     * Creates a new MoveAndScoreResult instance.
     * @param {Partial<MoveAndScoreResult>} [$$source = {}] - The source object to create the MoveAndScoreResult.
     */
    constructor($$source = {}) {
        if (!("success" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["success"] = false;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["error"] = undefined;
        }
        if (!("beforeScore" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["beforeScore"] = 0;
        }
        if (!("newScore" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["newScore"] = 0;
        }
        if (!("delta" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["delta"] = 0;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {ScoreBreakdown | null | undefined}
             */
            this["scoreDetail"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new MoveAndScoreResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {MoveAndScoreResult}
     */
    static createFrom($$source = {}) {
        const $$createField5_0 = $$createType5;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("scoreDetail" in $$parsedSource) {
            $$parsedSource["scoreDetail"] = $$createField5_0($$parsedSource["scoreDetail"]);
        }
        return new MoveAndScoreResult(/** @type {Partial<MoveAndScoreResult>} */($$parsedSource));
    }
}

/**
 * MoveConflict describes a conflict found when checking a move.
 */
export class MoveConflict {
    /**
     * Creates a new MoveConflict instance.
     * @param {Partial<MoveConflict>} [$$source = {}] - The source object to create the MoveConflict.
     */
    constructor($$source = {}) {
        if (!("type" in $$source)) {
            /**
             * "teacher" | "room" | "class" | "locked"
             * @member
             * @type {string}
             */
            this["type"] = "";
        }
        if (!("description" in $$source)) {
            /**
             * Human-readable
             * @member
             * @type {string}
             */
            this["description"] = "";
        }
        if (!("entity" in $$source)) {
            /**
             * Conflict entity name
             * @member
             * @type {string}
             */
            this["entity"] = "";
        }
        if (!("suggestion" in $$source)) {
            /**
             * Optional suggestion
             * @member
             * @type {string}
             */
            this["suggestion"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new MoveConflict instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {MoveConflict}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new MoveConflict(/** @type {Partial<MoveConflict>} */($$parsedSource));
    }
}

/**
 * ScheduleProgress records a scheduling phase milestone.
 */
export class ScheduleProgress {
    /**
     * Creates a new ScheduleProgress instance.
     * @param {Partial<ScheduleProgress>} [$$source = {}] - The source object to create the ScheduleProgress.
     */
    constructor($$source = {}) {
        if (!("progress" in $$source)) {
            /**
             * 0-100 percentage
             * @member
             * @type {number}
             */
            this["progress"] = 0;
        }
        if (!("stage" in $$source)) {
            /**
             * human-readable phase name
             * @member
             * @type {string}
             */
            this["stage"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ScheduleProgress instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ScheduleProgress}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ScheduleProgress(/** @type {Partial<ScheduleProgress>} */($$parsedSource));
    }
}

export class SchedulingConfig {
    /**
     * Creates a new SchedulingConfig instance.
     * @param {Partial<SchedulingConfig>} [$$source = {}] - The source object to create the SchedulingConfig.
     */
    constructor($$source = {}) {
        if (!("scope" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["scope"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {types$0.SchedulingMode | undefined}
             */
            this["mode"] = undefined;
        }
        if (!("strategy" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["strategy"] = "";
        }
        if (!("iterations" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["iterations"] = 0;
        }
        if (!("timeLimit" in $$source)) {
            /**
             * max solve time in seconds, default 60
             * @member
             * @type {number}
             */
            this["timeLimit"] = 0;
        }
        if (!("constraints" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["constraints"] = [];
        }
        if (/** @type {any} */(false)) {
            /**
             * JSON string, avoids Wails enum serialization pitfall
             * @member
             * @type {string | undefined}
             */
            this["lockedSlotsJson"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * active semester ID
             * @member
             * @type {number | undefined}
             */
            this["semesterId"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * per-constraint weights (0-100)
             * @member
             * @type {{ [_ in string]?: number } | undefined}
             */
            this["constraintWeights"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * Orchestrator internal retry limit, 0 = no retry
             * @member
             * @type {number | undefined}
             */
            this["maxRetries"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SchedulingConfig instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {SchedulingConfig}
     */
    static createFrom($$source = {}) {
        const $$createField5_0 = $$createType3;
        const $$createField8_0 = $$createType6;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("constraints" in $$parsedSource) {
            $$parsedSource["constraints"] = $$createField5_0($$parsedSource["constraints"]);
        }
        if ("constraintWeights" in $$parsedSource) {
            $$parsedSource["constraintWeights"] = $$createField8_0($$parsedSource["constraintWeights"]);
        }
        return new SchedulingConfig(/** @type {Partial<SchedulingConfig>} */($$parsedSource));
    }
}

export class SchedulingResult {
    /**
     * Creates a new SchedulingResult instance.
     * @param {Partial<SchedulingResult>} [$$source = {}] - The source object to create the SchedulingResult.
     */
    constructor($$source = {}) {
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["mode"] = undefined;
        }
        if (!("totalCourses" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["totalCourses"] = 0;
        }
        if (!("scheduled" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["scheduled"] = 0;
        }
        if (!("tasksScheduled" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["tasksScheduled"] = 0;
        }
        if (!("conflicts" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["conflicts"] = 0;
        }
        if (!("teacherConflicts" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["teacherConflicts"] = 0;
        }
        if (!("roomConflicts" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["roomConflicts"] = 0;
        }
        if (!("classConflicts" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["classConflicts"] = 0;
        }
        if (!("utilization" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["utilization"] = 0;
        }
        if (!("score" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["score"] = 0;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {ScoreBreakdown | null | undefined}
             */
            this["scoreDetail"] = undefined;
        }
        if (!("logs" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["logs"] = [];
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["error"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {ScheduleProgress[] | undefined}
             */
            this["progressHistory"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {UnplacedTask[] | undefined}
             */
            this["unplacedTasks"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SchedulingResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {SchedulingResult}
     */
    static createFrom($$source = {}) {
        const $$createField10_0 = $$createType5;
        const $$createField11_0 = $$createType3;
        const $$createField13_0 = $$createType8;
        const $$createField14_0 = $$createType10;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("scoreDetail" in $$parsedSource) {
            $$parsedSource["scoreDetail"] = $$createField10_0($$parsedSource["scoreDetail"]);
        }
        if ("logs" in $$parsedSource) {
            $$parsedSource["logs"] = $$createField11_0($$parsedSource["logs"]);
        }
        if ("progressHistory" in $$parsedSource) {
            $$parsedSource["progressHistory"] = $$createField13_0($$parsedSource["progressHistory"]);
        }
        if ("unplacedTasks" in $$parsedSource) {
            $$parsedSource["unplacedTasks"] = $$createField14_0($$parsedSource["unplacedTasks"]);
        }
        return new SchedulingResult(/** @type {Partial<SchedulingResult>} */($$parsedSource));
    }
}

/**
 * ScoreBreakdown holds the detailed scoring result.
 */
export class ScoreBreakdown {
    /**
     * Creates a new ScoreBreakdown instance.
     * @param {Partial<ScoreBreakdown>} [$$source = {}] - The source object to create the ScoreBreakdown.
     */
    constructor($$source = {}) {
        if (!("total" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["total"] = 0;
        }
        if (!("teacherPref" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["teacherPref"] = 0;
        }
        if (!("courseSpacing" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["courseSpacing"] = 0;
        }
        if (!("teacherDays" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["teacherDays"] = 0;
        }
        if (!("lowFloorPref" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["lowFloorPref"] = 0;
        }
        if (!("weekendAvoid" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["weekendAvoid"] = 0;
        }
        if (!("pePeriodPref" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["pePeriodPref"] = 0;
        }
        if (!("studentFatigue" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["studentFatigue"] = 0;
        }
        if (!("perCategoryMax" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["perCategoryMax"] = 0;
        }
        if (!("enabledCategoryCount" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["enabledCategoryCount"] = 0;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {{ [_ in string]?: number } | undefined}
             */
            this["categoryMaxes"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | undefined}
             */
            this["placedSessions"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | undefined}
             */
            this["expectedSessions"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | undefined}
             */
            this["completeness"] = undefined;
        }
        if (!("finalTotal" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["finalTotal"] = 0;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {ScoreBuckets | null | undefined}
             */
            this["buckets"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string[] | undefined}
             */
            this["enabledDimensions"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ScoreBreakdown instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ScoreBreakdown}
     */
    static createFrom($$source = {}) {
        const $$createField10_0 = $$createType11;
        const $$createField15_0 = $$createType13;
        const $$createField16_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("categoryMaxes" in $$parsedSource) {
            $$parsedSource["categoryMaxes"] = $$createField10_0($$parsedSource["categoryMaxes"]);
        }
        if ("buckets" in $$parsedSource) {
            $$parsedSource["buckets"] = $$createField15_0($$parsedSource["buckets"]);
        }
        if ("enabledDimensions" in $$parsedSource) {
            $$parsedSource["enabledDimensions"] = $$createField16_0($$parsedSource["enabledDimensions"]);
        }
        return new ScoreBreakdown(/** @type {Partial<ScoreBreakdown>} */($$parsedSource));
    }
}

/**
 * ScoreBucket 一个维度的评分聚合。
 */
export class ScoreBucket {
    /**
     * Creates a new ScoreBucket instance.
     * @param {Partial<ScoreBucket>} [$$source = {}] - The source object to create the ScoreBucket.
     */
    constructor($$source = {}) {
        if (!("value" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["value"] = 0;
        }
        if (!("max" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["max"] = 0;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {{ [_ in string]?: number } | undefined}
             */
            this["details"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ScoreBucket instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ScoreBucket}
     */
    static createFrom($$source = {}) {
        const $$createField2_0 = $$createType11;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("details" in $$parsedSource) {
            $$parsedSource["details"] = $$createField2_0($$parsedSource["details"]);
        }
        return new ScoreBucket(/** @type {Partial<ScoreBucket>} */($$parsedSource));
    }
}

/**
 * ScoreBuckets 按 spec 2.7 冻结的四桶结构表达当前排课结果分值。
 */
export class ScoreBuckets {
    /**
     * Creates a new ScoreBuckets instance.
     * @param {Partial<ScoreBuckets>} [$$source = {}] - The source object to create the ScoreBuckets.
     */
    constructor($$source = {}) {
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {ScoreBucket | null | undefined}
             */
            this["time"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {ScoreBucket | null | undefined}
             */
            this["teacher"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {ScoreBucket | null | undefined}
             */
            this["student"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {ScoreBucket | null | undefined}
             */
            this["resource"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ScoreBuckets instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ScoreBuckets}
     */
    static createFrom($$source = {}) {
        const $$createField0_0 = $$createType15;
        const $$createField1_0 = $$createType15;
        const $$createField2_0 = $$createType15;
        const $$createField3_0 = $$createType15;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("time" in $$parsedSource) {
            $$parsedSource["time"] = $$createField0_0($$parsedSource["time"]);
        }
        if ("teacher" in $$parsedSource) {
            $$parsedSource["teacher"] = $$createField1_0($$parsedSource["teacher"]);
        }
        if ("student" in $$parsedSource) {
            $$parsedSource["student"] = $$createField2_0($$parsedSource["student"]);
        }
        if ("resource" in $$parsedSource) {
            $$parsedSource["resource"] = $$createField3_0($$parsedSource["resource"]);
        }
        return new ScoreBuckets(/** @type {Partial<ScoreBuckets>} */($$parsedSource));
    }
}

/**
 * ScoringContext bundles all data needed for schedule quality evaluation.
 * It is the single source of truth for scoring — no call site should derive
 * constraints or sports course IDs independently.
 * 
 * Version history:
 * 
 * 	v1 — initial version with 7 soft constraints (teacher_preference,
 * 	      course_dispersed, teacher_days_limit, low_floor_preference,
 * 	      avoid_saturday/avoid_sunday, pe_preferred_periods, student_fatigue)
 * 	v2 — v0.5.2: added ExpectedTotalSessions for placement-completeness scaling
 * 	      of FinalTotal. Total field semantics unchanged (Stable Core compat).
 * 	v3 — v0.5.5: added Mode so downstream scoring / snapshot / version writers
 * 	      can distinguish TIME_ONLY from FULL. Absent (v1/v2 stored configs)
 * 	      → treated as FULL_SCHEDULING for backward compatibility.
 */
export class ScoringContext {
    /**
     * Creates a new ScoringContext instance.
     * @param {Partial<ScoringContext>} [$$source = {}] - The source object to create the ScoringContext.
     */
    constructor($$source = {}) {
        if (!("version" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["version"] = 0;
        }
        if (!("enabledConstraints" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["enabledConstraints"] = [];
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {types$0.SchedulingMode | undefined}
             */
            this["mode"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * v0.5.6: per-constraint weights (0-100). When nil or empty, ScoreSchedule
             * falls back to equal weighting (100 / enabledCount per category).
             * Weights are persisted so snapshots/versions remember the configuration.
             * @member
             * @type {{ [_ in string]?: number } | undefined}
             */
            this["constraintWeights"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ScoringContext instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ScoringContext}
     */
    static createFrom($$source = {}) {
        const $$createField1_0 = $$createType3;
        const $$createField3_0 = $$createType6;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("enabledConstraints" in $$parsedSource) {
            $$parsedSource["enabledConstraints"] = $$createField1_0($$parsedSource["enabledConstraints"]);
        }
        if ("constraintWeights" in $$parsedSource) {
            $$parsedSource["constraintWeights"] = $$createField3_0($$parsedSource["constraintWeights"]);
        }
        return new ScoringContext(/** @type {Partial<ScoringContext>} */($$parsedSource));
    }
}

export class TeacherVersionDiff {
    /**
     * Creates a new TeacherVersionDiff instance.
     * @param {Partial<TeacherVersionDiff>} [$$source = {}] - The source object to create the TeacherVersionDiff.
     */
    constructor($$source = {}) {
        if (!("code" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["code"] = "";
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("entryDelta" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["entryDelta"] = 0;
        }
        if (!("earlyDelta" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["earlyDelta"] = 0;
        }
        if (!("lateDelta" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["lateDelta"] = 0;
        }
        if (!("daysActualA" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["daysActualA"] = 0;
        }
        if (!("daysActualB" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["daysActualB"] = 0;
        }
        if (!("daysTarget" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["daysTarget"] = 0;
        }
        if (!("avgFloorDelta" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["avgFloorDelta"] = 0;
        }
        if (!("status" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["status"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TeacherVersionDiff instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {TeacherVersionDiff}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new TeacherVersionDiff(/** @type {Partial<TeacherVersionDiff>} */($$parsedSource));
    }
}

/**
 * TeacherWorkloadInfo holds per-teacher workload analysis data.
 */
export class TeacherWorkloadInfo {
    /**
     * Creates a new TeacherWorkloadInfo instance.
     * @param {Partial<TeacherWorkloadInfo>} [$$source = {}] - The source object to create the TeacherWorkloadInfo.
     */
    constructor($$source = {}) {
        if (!("teacherId" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["teacherId"] = 0;
        }
        if (!("teacherName" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["teacherName"] = "";
        }
        if (!("totalSessions" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["totalSessions"] = 0;
        }
        if (!("dailyDistribution" in $$source)) {
            /**
             * @member
             * @type {number[]}
             */
            this["dailyDistribution"] = [];
        }
        if (!("busyDays" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["busyDays"] = 0;
        }
        if (!("maxDaily" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["maxDaily"] = 0;
        }
        if (!("minDaily" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["minDaily"] = 0;
        }
        if (!("balanceScore" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["balanceScore"] = 0;
        }
        if (!("suggestion" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["suggestion"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TeacherWorkloadInfo instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {TeacherWorkloadInfo}
     */
    static createFrom($$source = {}) {
        const $$createField3_0 = $$createType16;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("dailyDistribution" in $$parsedSource) {
            $$parsedSource["dailyDistribution"] = $$createField3_0($$parsedSource["dailyDistribution"]);
        }
        return new TeacherWorkloadInfo(/** @type {Partial<TeacherWorkloadInfo>} */($$parsedSource));
    }
}

/**
 * UnplacedTask describes a teaching task that could not be scheduled.
 */
export class UnplacedTask {
    /**
     * Creates a new UnplacedTask instance.
     * @param {Partial<UnplacedTask>} [$$source = {}] - The source object to create the UnplacedTask.
     */
    constructor($$source = {}) {
        if (!("taskId" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["taskId"] = 0;
        }
        if (!("courseName" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["courseName"] = "";
        }
        if (!("teacherName" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["teacherName"] = "";
        }
        if (!("className" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["className"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * COMPUTER / LAB / GYM / ""
             * @member
             * @type {string | undefined}
             */
            this["requiredRoom"] = undefined;
        }
        if (!("placed" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["placed"] = 0;
        }
        if (!("expected" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["expected"] = 0;
        }
        if (/** @type {any} */(false)) {
            /**
             * 确诊 or 疑似
             * @member
             * @type {string | undefined}
             */
            this["rootCause"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new UnplacedTask instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {UnplacedTask}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new UnplacedTask(/** @type {Partial<UnplacedTask>} */($$parsedSource));
    }
}

export class VersionCompareResult {
    /**
     * Creates a new VersionCompareResult instance.
     * @param {Partial<VersionCompareResult>} [$$source = {}] - The source object to create the VersionCompareResult.
     */
    constructor($$source = {}) {
        if (!("a" in $$source)) {
            /**
             * @member
             * @type {models$0.ScheduleVersion | null}
             */
            this["a"] = null;
        }
        if (!("b" in $$source)) {
            /**
             * @member
             * @type {models$0.ScheduleVersion | null}
             */
            this["b"] = null;
        }
        if (!("scoreDelta" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["scoreDelta"] = 0;
        }
        if (!("conflictDelta" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["conflictDelta"] = 0;
        }
        if (!("entryDelta" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["entryDelta"] = 0;
        }
        if (!("teacherDiffs" in $$source)) {
            /**
             * @member
             * @type {TeacherVersionDiff[]}
             */
            this["teacherDiffs"] = [];
        }
        if (!("entryDiffs" in $$source)) {
            /**
             * @member
             * @type {EntryDiff[]}
             */
            this["entryDiffs"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new VersionCompareResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {VersionCompareResult}
     */
    static createFrom($$source = {}) {
        const $$createField0_0 = $$createType18;
        const $$createField1_0 = $$createType18;
        const $$createField5_0 = $$createType20;
        const $$createField6_0 = $$createType22;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("a" in $$parsedSource) {
            $$parsedSource["a"] = $$createField0_0($$parsedSource["a"]);
        }
        if ("b" in $$parsedSource) {
            $$parsedSource["b"] = $$createField1_0($$parsedSource["b"]);
        }
        if ("teacherDiffs" in $$parsedSource) {
            $$parsedSource["teacherDiffs"] = $$createField5_0($$parsedSource["teacherDiffs"]);
        }
        if ("entryDiffs" in $$parsedSource) {
            $$parsedSource["entryDiffs"] = $$createField6_0($$parsedSource["entryDiffs"]);
        }
        return new VersionCompareResult(/** @type {Partial<VersionCompareResult>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = MoveConflict.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = $Create.Array($Create.Any);
const $$createType3 = $Create.Array($Create.Any);
const $$createType4 = ScoreBreakdown.createFrom;
const $$createType5 = $Create.Nullable($$createType4);
const $$createType6 = $Create.Map($Create.Any, $Create.Any);
const $$createType7 = ScheduleProgress.createFrom;
const $$createType8 = $Create.Array($$createType7);
const $$createType9 = UnplacedTask.createFrom;
const $$createType10 = $Create.Array($$createType9);
const $$createType11 = $Create.Map($Create.Any, $Create.Any);
const $$createType12 = ScoreBuckets.createFrom;
const $$createType13 = $Create.Nullable($$createType12);
const $$createType14 = ScoreBucket.createFrom;
const $$createType15 = $Create.Nullable($$createType14);
const $$createType16 = $Create.Array($Create.Any);
const $$createType17 = models$0.ScheduleVersion.createFrom;
const $$createType18 = $Create.Nullable($$createType17);
const $$createType19 = TeacherVersionDiff.createFrom;
const $$createType20 = $Create.Array($$createType19);
const $$createType21 = EntryDiff.createFrom;
const $$createType22 = $Create.Array($$createType21);
