// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as models$0 from "../models/models.js";

/**
 * CheckMoveRequest is the input for CheckMove.
 */
export class CheckMoveRequest {
    /**
     * Creates a new CheckMoveRequest instance.
     * @param {Partial<CheckMoveRequest>} [$$source = {}] - The source object to create the CheckMoveRequest.
     */
    constructor($$source = {}) {
        if (!("entryId" in $$source)) {
            /**
             * the schedule entry being moved
             * @member
             * @type {number}
             */
            this["entryId"] = 0;
        }
        if (!("newDay" in $$source)) {
            /**
             * 0-6
             * @member
             * @type {number}
             */
            this["newDay"] = 0;
        }
        if (!("newPeriod" in $$source)) {
            /**
             * 0-10
             * @member
             * @type {number}
             */
            this["newPeriod"] = 0;
        }
        if (!("newSpan" in $$source)) {
            /**
             * usually 2
             * @member
             * @type {number}
             */
            this["newSpan"] = 0;
        }
        if (!("newClassroom" in $$source)) {
            /**
             * 0 = keep current
             * @member
             * @type {number}
             */
            this["newClassroom"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CheckMoveRequest instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {CheckMoveRequest}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new CheckMoveRequest(/** @type {Partial<CheckMoveRequest>} */($$parsedSource));
    }
}

/**
 * CheckMoveResult is the output of the move validation.
 */
export class CheckMoveResult {
    /**
     * Creates a new CheckMoveResult instance.
     * @param {Partial<CheckMoveResult>} [$$source = {}] - The source object to create the CheckMoveResult.
     */
    constructor($$source = {}) {
        if (!("valid" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["valid"] = false;
        }
        if (!("conflicts" in $$source)) {
            /**
             * @member
             * @type {MoveConflict[]}
             */
            this["conflicts"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CheckMoveResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {CheckMoveResult}
     */
    static createFrom($$source = {}) {
        const $$createField1_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("conflicts" in $$parsedSource) {
            $$parsedSource["conflicts"] = $$createField1_0($$parsedSource["conflicts"]);
        }
        return new CheckMoveResult(/** @type {Partial<CheckMoveResult>} */($$parsedSource));
    }
}

/**
 * LockedTimeSlot represents a globally locked time period.
 */
export class LockedTimeSlot {
    /**
     * Creates a new LockedTimeSlot instance.
     * @param {Partial<LockedTimeSlot>} [$$source = {}] - The source object to create the LockedTimeSlot.
     */
    constructor($$source = {}) {
        if (!("dayOfWeek" in $$source)) {
            /**
             * @member
             * @type {models$0.DayOfWeek}
             */
            this["dayOfWeek"] = models$0.DayOfWeek.$zero;
        }
        if (!("startPeriod" in $$source)) {
            /**
             * @member
             * @type {models$0.Period}
             */
            this["startPeriod"] = 0;
        }
        if (!("span" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["span"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new LockedTimeSlot instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {LockedTimeSlot}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new LockedTimeSlot(/** @type {Partial<LockedTimeSlot>} */($$parsedSource));
    }
}

/**
 * MergeableGroup represents a group of teaching tasks that could be merged
 * (same course name + same teacher).
 */
export class MergeableGroup {
    /**
     * Creates a new MergeableGroup instance.
     * @param {Partial<MergeableGroup>} [$$source = {}] - The source object to create the MergeableGroup.
     */
    constructor($$source = {}) {
        if (!("courseName" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["courseName"] = "";
        }
        if (!("teacherName" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["teacherName"] = "";
        }
        if (!("tasks" in $$source)) {
            /**
             * @member
             * @type {models$0.TeachingTask[]}
             */
            this["tasks"] = [];
        }
        if (!("classGroups" in $$source)) {
            /**
             * all classes across the group
             * @member
             * @type {models$0.ClassGroup[]}
             */
            this["classGroups"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new MergeableGroup instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {MergeableGroup}
     */
    static createFrom($$source = {}) {
        const $$createField2_0 = $$createType3;
        const $$createField3_0 = $$createType5;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("tasks" in $$parsedSource) {
            $$parsedSource["tasks"] = $$createField2_0($$parsedSource["tasks"]);
        }
        if ("classGroups" in $$parsedSource) {
            $$parsedSource["classGroups"] = $$createField3_0($$parsedSource["classGroups"]);
        }
        return new MergeableGroup(/** @type {Partial<MergeableGroup>} */($$parsedSource));
    }
}

/**
 * MoveConflict describes a conflict found when checking a move.
 */
export class MoveConflict {
    /**
     * Creates a new MoveConflict instance.
     * @param {Partial<MoveConflict>} [$$source = {}] - The source object to create the MoveConflict.
     */
    constructor($$source = {}) {
        if (!("type" in $$source)) {
            /**
             * "teacher" | "room" | "class" | "locked"
             * @member
             * @type {string}
             */
            this["type"] = "";
        }
        if (!("description" in $$source)) {
            /**
             * Human-readable
             * @member
             * @type {string}
             */
            this["description"] = "";
        }
        if (!("entity" in $$source)) {
            /**
             * Conflict entity name
             * @member
             * @type {string}
             */
            this["entity"] = "";
        }
        if (!("suggestion" in $$source)) {
            /**
             * Optional suggestion
             * @member
             * @type {string}
             */
            this["suggestion"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new MoveConflict instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {MoveConflict}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new MoveConflict(/** @type {Partial<MoveConflict>} */($$parsedSource));
    }
}

export class SchedulingConfig {
    /**
     * Creates a new SchedulingConfig instance.
     * @param {Partial<SchedulingConfig>} [$$source = {}] - The source object to create the SchedulingConfig.
     */
    constructor($$source = {}) {
        if (!("scope" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["scope"] = "";
        }
        if (!("semester" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["semester"] = "";
        }
        if (!("strategy" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["strategy"] = "";
        }
        if (!("iterations" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["iterations"] = 0;
        }
        if (!("timeLimit" in $$source)) {
            /**
             * max solve time in seconds, default 60
             * @member
             * @type {number}
             */
            this["timeLimit"] = 0;
        }
        if (!("constraints" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["constraints"] = [];
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {LockedTimeSlot[] | undefined}
             */
            this["lockedSlots"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * active semester ID
             * @member
             * @type {number | undefined}
             */
            this["semesterId"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SchedulingConfig instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {SchedulingConfig}
     */
    static createFrom($$source = {}) {
        const $$createField5_0 = $$createType6;
        const $$createField6_0 = $$createType8;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("constraints" in $$parsedSource) {
            $$parsedSource["constraints"] = $$createField5_0($$parsedSource["constraints"]);
        }
        if ("lockedSlots" in $$parsedSource) {
            $$parsedSource["lockedSlots"] = $$createField6_0($$parsedSource["lockedSlots"]);
        }
        return new SchedulingConfig(/** @type {Partial<SchedulingConfig>} */($$parsedSource));
    }
}

export class SchedulingResult {
    /**
     * Creates a new SchedulingResult instance.
     * @param {Partial<SchedulingResult>} [$$source = {}] - The source object to create the SchedulingResult.
     */
    constructor($$source = {}) {
        if (!("totalCourses" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["totalCourses"] = 0;
        }
        if (!("scheduled" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["scheduled"] = 0;
        }
        if (!("conflicts" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["conflicts"] = 0;
        }
        if (!("utilization" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["utilization"] = 0;
        }
        if (!("score" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["score"] = 0;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {ScoreBreakdown | null | undefined}
             */
            this["scoreDetail"] = undefined;
        }
        if (!("logs" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["logs"] = [];
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["error"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SchedulingResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {SchedulingResult}
     */
    static createFrom($$source = {}) {
        const $$createField5_0 = $$createType10;
        const $$createField6_0 = $$createType6;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("scoreDetail" in $$parsedSource) {
            $$parsedSource["scoreDetail"] = $$createField5_0($$parsedSource["scoreDetail"]);
        }
        if ("logs" in $$parsedSource) {
            $$parsedSource["logs"] = $$createField6_0($$parsedSource["logs"]);
        }
        return new SchedulingResult(/** @type {Partial<SchedulingResult>} */($$parsedSource));
    }
}

/**
 * ScoreBreakdown holds the detailed scoring result.
 */
export class ScoreBreakdown {
    /**
     * Creates a new ScoreBreakdown instance.
     * @param {Partial<ScoreBreakdown>} [$$source = {}] - The source object to create the ScoreBreakdown.
     */
    constructor($$source = {}) {
        if (!("total" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["total"] = 0;
        }
        if (!("teacherPref" in $$source)) {
            /**
             * 教师偏好满足度
             * @member
             * @type {number}
             */
            this["teacherPref"] = 0;
        }
        if (!("courseSpacing" in $$source)) {
            /**
             * 课程间隔均匀度
             * @member
             * @type {number}
             */
            this["courseSpacing"] = 0;
        }
        if (!("teacherDays" in $$source)) {
            /**
             * 教师到校天数
             * @member
             * @type {number}
             */
            this["teacherDays"] = 0;
        }
        if (!("lowFloorPref" in $$source)) {
            /**
             * 优先低楼层
             * @member
             * @type {number}
             */
            this["lowFloorPref"] = 0;
        }
        if (!("weekendAvoid" in $$source)) {
            /**
             * 周末避让
             * @member
             * @type {number}
             */
            this["weekendAvoid"] = 0;
        }
        if (!("pePeriodPref" in $$source)) {
            /**
             * 体育课时段偏好
             * @member
             * @type {number}
             */
            this["pePeriodPref"] = 0;
        }
        if (!("studentFatigue" in $$source)) {
            /**
             * 学生连续疲劳度
             * @member
             * @type {number}
             */
            this["studentFatigue"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ScoreBreakdown instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ScoreBreakdown}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ScoreBreakdown(/** @type {Partial<ScoreBreakdown>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = MoveConflict.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = models$0.TeachingTask.createFrom;
const $$createType3 = $Create.Array($$createType2);
const $$createType4 = models$0.ClassGroup.createFrom;
const $$createType5 = $Create.Array($$createType4);
const $$createType6 = $Create.Array($Create.Any);
const $$createType7 = LockedTimeSlot.createFrom;
const $$createType8 = $Create.Array($$createType7);
const $$createType9 = ScoreBreakdown.createFrom;
const $$createType10 = $Create.Nullable($$createType9);
