// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as models$0 from "../models/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as types$0 from "../scheduling/types/models.js";

/**
 * CheckMoveRequest is the input for CheckMove.
 */
export class CheckMoveRequest {
    /**
     * Creates a new CheckMoveRequest instance.
     * @param {Partial<CheckMoveRequest>} [$$source = {}] - The source object to create the CheckMoveRequest.
     */
    constructor($$source = {}) {
        if (!("entryId" in $$source)) {
            /**
             * the schedule entry being moved
             * @member
             * @type {number}
             */
            this["entryId"] = 0;
        }
        if (!("newDay" in $$source)) {
            /**
             * 0-6
             * @member
             * @type {number}
             */
            this["newDay"] = 0;
        }
        if (!("newPeriod" in $$source)) {
            /**
             * 0-10
             * @member
             * @type {number}
             */
            this["newPeriod"] = 0;
        }
        if (!("newSpan" in $$source)) {
            /**
             * usually 2
             * @member
             * @type {number}
             */
            this["newSpan"] = 0;
        }
        if (!("newClassroom" in $$source)) {
            /**
             * 0 = keep current
             * @member
             * @type {number}
             */
            this["newClassroom"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CheckMoveRequest instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {CheckMoveRequest}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new CheckMoveRequest(/** @type {Partial<CheckMoveRequest>} */($$parsedSource));
    }
}

/**
 * CheckMoveResult is the output of the move validation.
 */
export class CheckMoveResult {
    /**
     * Creates a new CheckMoveResult instance.
     * @param {Partial<CheckMoveResult>} [$$source = {}] - The source object to create the CheckMoveResult.
     */
    constructor($$source = {}) {
        if (!("valid" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["valid"] = false;
        }
        if (!("conflicts" in $$source)) {
            /**
             * @member
             * @type {MoveConflict[]}
             */
            this["conflicts"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CheckMoveResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {CheckMoveResult}
     */
    static createFrom($$source = {}) {
        const $$createField1_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("conflicts" in $$parsedSource) {
            $$parsedSource["conflicts"] = $$createField1_0($$parsedSource["conflicts"]);
        }
        return new CheckMoveResult(/** @type {Partial<CheckMoveResult>} */($$parsedSource));
    }
}

/**
 * MoveAndScoreResult is the output of MoveEntryAndScore.
 */
export class MoveAndScoreResult {
    /**
     * Creates a new MoveAndScoreResult instance.
     * @param {Partial<MoveAndScoreResult>} [$$source = {}] - The source object to create the MoveAndScoreResult.
     */
    constructor($$source = {}) {
        if (!("success" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["success"] = false;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["error"] = undefined;
        }
        if (!("beforeScore" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["beforeScore"] = 0;
        }
        if (!("newScore" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["newScore"] = 0;
        }
        if (!("delta" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["delta"] = 0;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {ScoreBreakdown | null | undefined}
             */
            this["scoreDetail"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new MoveAndScoreResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {MoveAndScoreResult}
     */
    static createFrom($$source = {}) {
        const $$createField5_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("scoreDetail" in $$parsedSource) {
            $$parsedSource["scoreDetail"] = $$createField5_0($$parsedSource["scoreDetail"]);
        }
        return new MoveAndScoreResult(/** @type {Partial<MoveAndScoreResult>} */($$parsedSource));
    }
}

/**
 * MoveConflict describes a conflict found when checking a move.
 */
export class MoveConflict {
    /**
     * Creates a new MoveConflict instance.
     * @param {Partial<MoveConflict>} [$$source = {}] - The source object to create the MoveConflict.
     */
    constructor($$source = {}) {
        if (!("type" in $$source)) {
            /**
             * "teacher" | "room" | "class" | "locked"
             * @member
             * @type {string}
             */
            this["type"] = "";
        }
        if (!("description" in $$source)) {
            /**
             * Human-readable
             * @member
             * @type {string}
             */
            this["description"] = "";
        }
        if (!("entity" in $$source)) {
            /**
             * Conflict entity name
             * @member
             * @type {string}
             */
            this["entity"] = "";
        }
        if (!("suggestion" in $$source)) {
            /**
             * Optional suggestion
             * @member
             * @type {string}
             */
            this["suggestion"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new MoveConflict instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {MoveConflict}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new MoveConflict(/** @type {Partial<MoveConflict>} */($$parsedSource));
    }
}

/**
 * ScheduleProgress records a scheduling phase milestone.
 */
export class ScheduleProgress {
    /**
     * Creates a new ScheduleProgress instance.
     * @param {Partial<ScheduleProgress>} [$$source = {}] - The source object to create the ScheduleProgress.
     */
    constructor($$source = {}) {
        if (!("progress" in $$source)) {
            /**
             * 0-100 percentage
             * @member
             * @type {number}
             */
            this["progress"] = 0;
        }
        if (!("stage" in $$source)) {
            /**
             * human-readable phase name
             * @member
             * @type {string}
             */
            this["stage"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ScheduleProgress instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ScheduleProgress}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ScheduleProgress(/** @type {Partial<ScheduleProgress>} */($$parsedSource));
    }
}

export class SchedulingConfig {
    /**
     * Creates a new SchedulingConfig instance.
     * @param {Partial<SchedulingConfig>} [$$source = {}] - The source object to create the SchedulingConfig.
     */
    constructor($$source = {}) {
        if (!("scope" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["scope"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {types$0.SchedulingMode | undefined}
             */
            this["mode"] = undefined;
        }
        if (!("strategy" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["strategy"] = "";
        }
        if (!("iterations" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["iterations"] = 0;
        }
        if (!("timeLimit" in $$source)) {
            /**
             * max solve time in seconds, default 60
             * @member
             * @type {number}
             */
            this["timeLimit"] = 0;
        }
        if (!("constraints" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["constraints"] = [];
        }
        if (/** @type {any} */(false)) {
            /**
             * JSON string, avoids Wails enum serialization pitfall
             * @member
             * @type {string | undefined}
             */
            this["lockedSlotsJson"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * active semester ID
             * @member
             * @type {number | undefined}
             */
            this["semesterId"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * per-constraint weights (0-100)
             * @member
             * @type {{ [_ in string]?: number } | undefined}
             */
            this["constraintWeights"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * Orchestrator internal retry limit, 0 = no retry
             * @member
             * @type {number | undefined}
             */
            this["maxRetries"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SchedulingConfig instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {SchedulingConfig}
     */
    static createFrom($$source = {}) {
        const $$createField5_0 = $$createType4;
        const $$createField8_0 = $$createType5;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("constraints" in $$parsedSource) {
            $$parsedSource["constraints"] = $$createField5_0($$parsedSource["constraints"]);
        }
        if ("constraintWeights" in $$parsedSource) {
            $$parsedSource["constraintWeights"] = $$createField8_0($$parsedSource["constraintWeights"]);
        }
        return new SchedulingConfig(/** @type {Partial<SchedulingConfig>} */($$parsedSource));
    }
}

export class SchedulingResult {
    /**
     * Creates a new SchedulingResult instance.
     * @param {Partial<SchedulingResult>} [$$source = {}] - The source object to create the SchedulingResult.
     */
    constructor($$source = {}) {
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["mode"] = undefined;
        }
        if (!("totalCourses" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["totalCourses"] = 0;
        }
        if (!("scheduled" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["scheduled"] = 0;
        }
        if (!("tasksScheduled" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["tasksScheduled"] = 0;
        }
        if (!("conflicts" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["conflicts"] = 0;
        }
        if (!("teacherConflicts" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["teacherConflicts"] = 0;
        }
        if (!("roomConflicts" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["roomConflicts"] = 0;
        }
        if (!("classConflicts" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["classConflicts"] = 0;
        }
        if (!("utilization" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["utilization"] = 0;
        }
        if (!("score" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["score"] = 0;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {ScoreBreakdown | null | undefined}
             */
            this["scoreDetail"] = undefined;
        }
        if (!("logs" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["logs"] = [];
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["error"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {ScheduleProgress[] | undefined}
             */
            this["progressHistory"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SchedulingResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {SchedulingResult}
     */
    static createFrom($$source = {}) {
        const $$createField10_0 = $$createType3;
        const $$createField11_0 = $$createType4;
        const $$createField13_0 = $$createType7;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("scoreDetail" in $$parsedSource) {
            $$parsedSource["scoreDetail"] = $$createField10_0($$parsedSource["scoreDetail"]);
        }
        if ("logs" in $$parsedSource) {
            $$parsedSource["logs"] = $$createField11_0($$parsedSource["logs"]);
        }
        if ("progressHistory" in $$parsedSource) {
            $$parsedSource["progressHistory"] = $$createField13_0($$parsedSource["progressHistory"]);
        }
        return new SchedulingResult(/** @type {Partial<SchedulingResult>} */($$parsedSource));
    }
}

/**
 * ScoreBreakdown holds the detailed scoring result.
 */
export class ScoreBreakdown {
    /**
     * Creates a new ScoreBreakdown instance.
     * @param {Partial<ScoreBreakdown>} [$$source = {}] - The source object to create the ScoreBreakdown.
     */
    constructor($$source = {}) {
        if (!("total" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["total"] = 0;
        }
        if (!("teacherPref" in $$source)) {
            /**
             * 教师偏好满足度
             * @member
             * @type {number}
             */
            this["teacherPref"] = 0;
        }
        if (!("courseSpacing" in $$source)) {
            /**
             * 课程间隔均匀度
             * @member
             * @type {number}
             */
            this["courseSpacing"] = 0;
        }
        if (!("teacherDays" in $$source)) {
            /**
             * 教师到校天数
             * @member
             * @type {number}
             */
            this["teacherDays"] = 0;
        }
        if (!("lowFloorPref" in $$source)) {
            /**
             * 优先低楼层
             * @member
             * @type {number}
             */
            this["lowFloorPref"] = 0;
        }
        if (!("weekendAvoid" in $$source)) {
            /**
             * 周末避让
             * @member
             * @type {number}
             */
            this["weekendAvoid"] = 0;
        }
        if (!("pePeriodPref" in $$source)) {
            /**
             * 体育课时段偏好
             * @member
             * @type {number}
             */
            this["pePeriodPref"] = 0;
        }
        if (!("studentFatigue" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["studentFatigue"] = 0;
        }
        if (!("perCategoryMax" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["perCategoryMax"] = 0;
        }
        if (!("enabledCategoryCount" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["enabledCategoryCount"] = 0;
        }
        if (/** @type {any} */(false)) {
            /**
             * v0.5.2: placement completeness fields.
             * Total keeps its v0.4 semantics (sum of 7 soft-constraint categories).
             * FinalTotal is Total scaled by a completeness factor so under-placed schedules
             * receive a lower published score. When ExpectedSessions==0 or PlacedSessions
             * equals it, FinalTotal == Total (v0.4-compatible round-trip).
             * @member
             * @type {number | undefined}
             */
            this["placedSessions"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | undefined}
             */
            this["expectedSessions"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * ratio in [0,1]
             * @member
             * @type {number | undefined}
             */
            this["completeness"] = undefined;
        }
        if (!("finalTotal" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["finalTotal"] = 0;
        }
        if (/** @type {any} */(false)) {
            /**
             * v0.5.5 P0 M2: nullable buckets — Disabled 语义靠 nil 表达 (INV-S1/S2/I8)。
             * 与上面的 float64 字段并存作为过渡：读侧优先 buckets（nil = Disabled;
             * non-nil = 已评估分值），旧调用可继续读 float64（Disabled 与 真 0 都是 0）。
             * 一旦所有前端消费方切到 buckets，float64 可在下版本删除。
             * @member
             * @type {ScoreBuckets | null | undefined}
             */
            this["buckets"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * EnabledDimensions echoes the mode-derived dimension list (INV-S2)。
             * TIME_ONLY → ["time","teacher","student"]；FULL → [...+"resource"]。
             * @member
             * @type {string[] | undefined}
             */
            this["enabledDimensions"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ScoreBreakdown instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ScoreBreakdown}
     */
    static createFrom($$source = {}) {
        const $$createField14_0 = $$createType9;
        const $$createField15_0 = $$createType4;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("buckets" in $$parsedSource) {
            $$parsedSource["buckets"] = $$createField14_0($$parsedSource["buckets"]);
        }
        if ("enabledDimensions" in $$parsedSource) {
            $$parsedSource["enabledDimensions"] = $$createField15_0($$parsedSource["enabledDimensions"]);
        }
        return new ScoreBreakdown(/** @type {Partial<ScoreBreakdown>} */($$parsedSource));
    }
}

/**
 * ScoreBucket 一个维度的评分聚合。Details 保留子约束分值以便前端做详情。
 */
export class ScoreBucket {
    /**
     * Creates a new ScoreBucket instance.
     * @param {Partial<ScoreBucket>} [$$source = {}] - The source object to create the ScoreBucket.
     */
    constructor($$source = {}) {
        if (!("value" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["value"] = 0;
        }
        if (!("max" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["max"] = 0;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {{ [_ in string]?: number } | undefined}
             */
            this["details"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ScoreBucket instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ScoreBucket}
     */
    static createFrom($$source = {}) {
        const $$createField2_0 = $$createType10;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("details" in $$parsedSource) {
            $$parsedSource["details"] = $$createField2_0($$parsedSource["details"]);
        }
        return new ScoreBucket(/** @type {Partial<ScoreBucket>} */($$parsedSource));
    }
}

/**
 * ScoreBuckets 按 spec 2.7 冻结的四桶结构表达当前排课结果分值。
 * 每个 bucket 用指针：nil 表示该维度被禁用（如 TIME_ONLY 的 Resource），
 * non-nil 但 Value=0 表示"评估了,得 0 分"。这是"Disabled = missing, not 0"的关键。
 */
export class ScoreBuckets {
    /**
     * Creates a new ScoreBuckets instance.
     * @param {Partial<ScoreBuckets>} [$$source = {}] - The source object to create the ScoreBuckets.
     */
    constructor($$source = {}) {
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {ScoreBucket | null | undefined}
             */
            this["time"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {ScoreBucket | null | undefined}
             */
            this["teacher"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {ScoreBucket | null | undefined}
             */
            this["student"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * TIME_ONLY 下必为 nil
             * @member
             * @type {ScoreBucket | null | undefined}
             */
            this["resource"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ScoreBuckets instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ScoreBuckets}
     */
    static createFrom($$source = {}) {
        const $$createField0_0 = $$createType12;
        const $$createField1_0 = $$createType12;
        const $$createField2_0 = $$createType12;
        const $$createField3_0 = $$createType12;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("time" in $$parsedSource) {
            $$parsedSource["time"] = $$createField0_0($$parsedSource["time"]);
        }
        if ("teacher" in $$parsedSource) {
            $$parsedSource["teacher"] = $$createField1_0($$parsedSource["teacher"]);
        }
        if ("student" in $$parsedSource) {
            $$parsedSource["student"] = $$createField2_0($$parsedSource["student"]);
        }
        if ("resource" in $$parsedSource) {
            $$parsedSource["resource"] = $$createField3_0($$parsedSource["resource"]);
        }
        return new ScoreBuckets(/** @type {Partial<ScoreBuckets>} */($$parsedSource));
    }
}

/**
 * ScoringContext bundles all data needed for schedule quality evaluation.
 * It is the single source of truth for scoring — no call site should derive
 * constraints or sports course IDs independently.
 * 
 * Version history:
 * 
 * 	v1 — initial version with 7 soft constraints (teacher_preference,
 * 	      course_dispersed, teacher_days_limit, low_floor_preference,
 * 	      avoid_saturday/avoid_sunday, pe_preferred_periods, student_fatigue)
 * 	v2 — v0.5.2: added ExpectedTotalSessions for placement-completeness scaling
 * 	      of FinalTotal. Total field semantics unchanged (Stable Core compat).
 * 	v3 — v0.5.5: added Mode so downstream scoring / snapshot / version writers
 * 	      can distinguish TIME_ONLY from FULL. Absent (v1/v2 stored configs)
 * 	      → treated as FULL_SCHEDULING for backward compatibility.
 */
export class ScoringContext {
    /**
     * Creates a new ScoringContext instance.
     * @param {Partial<ScoringContext>} [$$source = {}] - The source object to create the ScoringContext.
     */
    constructor($$source = {}) {
        if (!("version" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["version"] = 0;
        }
        if (!("enabledConstraints" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["enabledConstraints"] = [];
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {types$0.SchedulingMode | undefined}
             */
            this["mode"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ScoringContext instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ScoringContext}
     */
    static createFrom($$source = {}) {
        const $$createField1_0 = $$createType4;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("enabledConstraints" in $$parsedSource) {
            $$parsedSource["enabledConstraints"] = $$createField1_0($$parsedSource["enabledConstraints"]);
        }
        return new ScoringContext(/** @type {Partial<ScoringContext>} */($$parsedSource));
    }
}

/**
 * SnapshotCompareResult holds the diff between two schedule snapshots.
 */
export class SnapshotCompareResult {
    /**
     * Creates a new SnapshotCompareResult instance.
     * @param {Partial<SnapshotCompareResult>} [$$source = {}] - The source object to create the SnapshotCompareResult.
     */
    constructor($$source = {}) {
        if (!("a" in $$source)) {
            /**
             * @member
             * @type {models$0.ScheduleSnapshot | null}
             */
            this["a"] = null;
        }
        if (!("b" in $$source)) {
            /**
             * @member
             * @type {models$0.ScheduleSnapshot | null}
             */
            this["b"] = null;
        }
        if (!("scoreDelta" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["scoreDelta"] = 0;
        }
        if (!("conflictDelta" in $$source)) {
            /**
             * +1: fail->pass, -1: pass->fail, 0: unchanged
             * @member
             * @type {number}
             */
            this["conflictDelta"] = 0;
        }
        if (!("entryDelta" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["entryDelta"] = 0;
        }
        if (!("teacherDiffs" in $$source)) {
            /**
             * @member
             * @type {TeacherSnapshotDiff[]}
             */
            this["teacherDiffs"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SnapshotCompareResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {SnapshotCompareResult}
     */
    static createFrom($$source = {}) {
        const $$createField0_0 = $$createType14;
        const $$createField1_0 = $$createType14;
        const $$createField5_0 = $$createType16;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("a" in $$parsedSource) {
            $$parsedSource["a"] = $$createField0_0($$parsedSource["a"]);
        }
        if ("b" in $$parsedSource) {
            $$parsedSource["b"] = $$createField1_0($$parsedSource["b"]);
        }
        if ("teacherDiffs" in $$parsedSource) {
            $$parsedSource["teacherDiffs"] = $$createField5_0($$parsedSource["teacherDiffs"]);
        }
        return new SnapshotCompareResult(/** @type {Partial<SnapshotCompareResult>} */($$parsedSource));
    }
}

/**
 * TeacherSnapshotDiff summarizes per-teacher changes between two snapshots.
 */
export class TeacherSnapshotDiff {
    /**
     * Creates a new TeacherSnapshotDiff instance.
     * @param {Partial<TeacherSnapshotDiff>} [$$source = {}] - The source object to create the TeacherSnapshotDiff.
     */
    constructor($$source = {}) {
        if (!("code" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["code"] = "";
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("entryDelta" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["entryDelta"] = 0;
        }
        if (!("earlyDelta" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["earlyDelta"] = 0;
        }
        if (!("lateDelta" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["lateDelta"] = 0;
        }
        if (!("daysActualA" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["daysActualA"] = 0;
        }
        if (!("daysActualB" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["daysActualB"] = 0;
        }
        if (!("daysTarget" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["daysTarget"] = 0;
        }
        if (!("avgFloorDelta" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["avgFloorDelta"] = 0;
        }
        if (!("status" in $$source)) {
            /**
             * improved / regressed / unchanged / added / removed
             * @member
             * @type {string}
             */
            this["status"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TeacherSnapshotDiff instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {TeacherSnapshotDiff}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new TeacherSnapshotDiff(/** @type {Partial<TeacherSnapshotDiff>} */($$parsedSource));
    }
}

/**
 * TeacherWorkloadInfo holds per-teacher workload analysis (post-hoc, does not affect scoring).
 */
export class TeacherWorkloadInfo {
    /**
     * Creates a new TeacherWorkloadInfo instance.
     * @param {Partial<TeacherWorkloadInfo>} [$$source = {}] - The source object to create the TeacherWorkloadInfo.
     */
    constructor($$source = {}) {
        if (!("teacherId" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["teacherId"] = 0;
        }
        if (!("teacherName" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["teacherName"] = "";
        }
        if (!("totalSessions" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["totalSessions"] = 0;
        }
        if (!("dailyDistribution" in $$source)) {
            /**
             * 7 elements, sessions per day Mon-Sun
             * @member
             * @type {number[]}
             */
            this["dailyDistribution"] = [];
        }
        if (!("busyDays" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["busyDays"] = 0;
        }
        if (!("maxDaily" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["maxDaily"] = 0;
        }
        if (!("minDaily" in $$source)) {
            /**
             * min across all 7 days (may be 0)
             * @member
             * @type {number}
             */
            this["minDaily"] = 0;
        }
        if (!("balanceScore" in $$source)) {
            /**
             * 0-100
             * @member
             * @type {number}
             */
            this["balanceScore"] = 0;
        }
        if (!("suggestion" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["suggestion"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TeacherWorkloadInfo instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {TeacherWorkloadInfo}
     */
    static createFrom($$source = {}) {
        const $$createField3_0 = $$createType17;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("dailyDistribution" in $$parsedSource) {
            $$parsedSource["dailyDistribution"] = $$createField3_0($$parsedSource["dailyDistribution"]);
        }
        return new TeacherWorkloadInfo(/** @type {Partial<TeacherWorkloadInfo>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = MoveConflict.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = ScoreBreakdown.createFrom;
const $$createType3 = $Create.Nullable($$createType2);
const $$createType4 = $Create.Array($Create.Any);
const $$createType5 = $Create.Map($Create.Any, $Create.Any);
const $$createType6 = ScheduleProgress.createFrom;
const $$createType7 = $Create.Array($$createType6);
const $$createType8 = ScoreBuckets.createFrom;
const $$createType9 = $Create.Nullable($$createType8);
const $$createType10 = $Create.Map($Create.Any, $Create.Any);
const $$createType11 = ScoreBucket.createFrom;
const $$createType12 = $Create.Nullable($$createType11);
const $$createType13 = models$0.ScheduleSnapshot.createFrom;
const $$createType14 = $Create.Nullable($$createType13);
const $$createType15 = TeacherSnapshotDiff.createFrom;
const $$createType16 = $Create.Array($$createType15);
const $$createType17 = $Create.Array($Create.Any);
