// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as models$0 from "../models/models.js";

/**
 * CheckMoveRequest is the input for CheckMove.
 */
export interface CheckMoveRequest {
    /**
     * the schedule entry being moved
     */
    "entryId": number;

    /**
     * 0-6
     */
    "newDay": number;

    /**
     * 0-10
     */
    "newPeriod": number;

    /**
     * usually 2
     */
    "newSpan": number;

    /**
     * 0 = keep current
     */
    "newClassroom": number;
}

/**
 * CheckMoveResult is the output of the move validation.
 */
export interface CheckMoveResult {
    "valid": boolean;
    "conflicts": MoveConflict[] | null;
}

/**
 * MergeableGroup represents a group of teaching tasks that could be merged
 * (same course name + same teacher).
 */
export interface MergeableGroup {
    "courseName": string;
    "teacherName": string;
    "tasks": models$0.TeachingTask[] | null;

    /**
     * all classes across the group
     */
    "classGroups": models$0.ClassGroup[] | null;
}

/**
 * MoveConflict describes a conflict found when checking a move.
 */
export interface MoveConflict {
    /**
     * "teacher" | "room" | "class" | "locked"
     */
    "type": string;

    /**
     * Human-readable
     */
    "description": string;

    /**
     * Conflict entity name
     */
    "entity": string;

    /**
     * Optional suggestion
     */
    "suggestion": string;
}

export interface SchedulingConfig {
    "scope": string;
    "semester": string;
    "strategy": string;
    "iterations": number;

    /**
     * max solve time in seconds, default 60
     */
    "timeLimit": number;
    "constraints": string[] | null;

    /**
     * JSON string, avoids Wails enum serialization pitfall
     */
    "lockedSlotsJson"?: string;

    /**
     * active semester ID
     */
    "semesterId"?: number;
}

export interface SchedulingResult {
    "totalCourses": number;
    "scheduled": number;
    "conflicts": number;
    "utilization": number;
    "score": number;
    "scoreDetail"?: ScoreBreakdown | null;
    "logs": string[] | null;
    "error"?: string;
}

/**
 * ScoreBreakdown holds the detailed scoring result.
 */
export interface ScoreBreakdown {
    "total": number;

    /**
     * 教师偏好满足度
     */
    "teacherPref": number;

    /**
     * 课程间隔均匀度
     */
    "courseSpacing": number;

    /**
     * 教师到校天数
     */
    "teacherDays": number;

    /**
     * 优先低楼层
     */
    "lowFloorPref": number;

    /**
     * 周末避让
     */
    "weekendAvoid": number;

    /**
     * 体育课时段偏好
     */
    "pePeriodPref": number;

    /**
     * 学生连续疲劳度
     */
    "studentFatigue": number;
}
