// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * MoveService validates schedule entry moves for drag-and-drop micro-adjustment.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * CheckMove validates whether a schedule entry can be moved to a new time/room.
 * @param {$models.CheckMoveRequest} req
 * @returns {$CancellablePromise<$models.CheckMoveResult | null>}
 */
export function CheckMove(req) {
    return $Call.ByID(3592166944, req).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * MoveEntry executes a validated move by updating the schedule entry.
 * @param {$models.CheckMoveRequest} req
 * @returns {$CancellablePromise<void>}
 */
export function MoveEntry(req) {
    return $Call.ByID(410174494, req);
}

// Private type creation functions
const $$createType0 = $models.CheckMoveResult.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
