// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * MoveService validates schedule entry moves for drag-and-drop micro-adjustment.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * TODO(v0.6.0): Adapt CheckMove for TimeAssignment+ScheduleEntry split model.
 * CheckMove currently accesses old ScheduleEntry fields (DayOfWeek, StartPeriod, Span,
 * Teacher, TeachingTask, etc.) that no longer exist after the TA+SE model migration.
 * Will be properly adapted when move operations are re-implemented against the new model.
 */
export function CheckMove(req: $models.CheckMoveRequest): $CancellablePromise<$models.CheckMoveResult | null> {
    return $Call.ByID(3592166944, req);
}

/**
 * TODO(v0.6.0): Adapt MoveEntry for TimeAssignment+ScheduleEntry split model.
 * MoveEntry updates old ScheduleEntry fields (DayOfWeek, StartPeriod, Span) that no
 * longer exist after the TA+SE split. Will be properly adapted when move operations
 * are re-implemented against the new model (TimeAssignment for time moves, ScheduleEntry
 * for room changes).
 */
export function MoveEntry(req: $models.CheckMoveRequest): $CancellablePromise<void> {
    return $Call.ByID(410174494, req);
}

/**
 * TODO(v0.6.0): Adapt MoveEntryAndScore for TimeAssignment+ScheduleEntry split model.
 * Depends on CheckMove, MoveEntry, and computeScoreDB — all of which access old
 * ScheduleEntry fields removed by the TA+SE split. Will be properly adapted in v0.6.1.
 */
export function MoveEntryAndScore(req: $models.CheckMoveRequest): $CancellablePromise<$models.MoveAndScoreResult | null> {
    return $Call.ByID(3988363451, req);
}
