// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * MoveService validates schedule entry moves for drag-and-drop micro-adjustment.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * CheckMove validates whether a schedule entry can be moved to a new time/room.
 */
export function CheckMove(req: $models.CheckMoveRequest): $CancellablePromise<$models.CheckMoveResult | null> {
    return $Call.ByID(3592166944, req).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * MoveEntry executes a validated move by updating the schedule entry.
 */
export function MoveEntry(req: $models.CheckMoveRequest): $CancellablePromise<void> {
    return $Call.ByID(410174494, req);
}

/**
 * MoveEntryAndScore validates and applies a move, then recalculates the full
 * schedule score to provide immediate quality-change feedback. On success the
 * DB entry is updated and the response includes before/after scores with a
 * human-readable delta.
 * 
 * This is the recommended single-call replacement for CheckMove + MoveEntry
 * when the caller also wants score feedback. Existing CheckMove + MoveEntry
 * callers are unaffected (backward compatible).
 */
export function MoveEntryAndScore(req: $models.CheckMoveRequest): $CancellablePromise<$models.MoveAndScoreResult | null> {
    return $Call.ByID(3988363451, req).then(($result: any) => {
        return $$createType3($result);
    });
}

// Private type creation functions
const $$createType0 = $models.CheckMoveResult.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = $models.MoveAndScoreResult.createFrom;
const $$createType3 = $Create.Nullable($$createType2);
