// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ResourceService handles CRUD for teachers, classrooms, courses, and class groups.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as models$0 from "../models/models.js";

/**
 * BackupDatabase copies the database file to a backup location.
 */
export function BackupDatabase(backupPath: string): $CancellablePromise<void> {
    return $Call.ByID(426460745, backupPath);
}

export function CreateClassGroup(c: models$0.ClassGroup): $CancellablePromise<void> {
    return $Call.ByID(2929636441, c);
}

export function CreateClassroom(c: models$0.Classroom): $CancellablePromise<void> {
    return $Call.ByID(2979645581, c);
}

export function CreateCourse(c: models$0.Course): $CancellablePromise<void> {
    return $Call.ByID(1220227755, c);
}

export function CreateDepartment(dept: models$0.Department): $CancellablePromise<void> {
    return $Call.ByID(1572938852, dept);
}

export function CreateSemester(sem: models$0.Semester): $CancellablePromise<void> {
    return $Call.ByID(2898724944, sem);
}

export function CreateTeacher(t: models$0.Teacher): $CancellablePromise<void> {
    return $Call.ByID(3813397992, t);
}

export function DeleteClassGroup(id: number): $CancellablePromise<void> {
    return $Call.ByID(3930905198, id);
}

export function DeleteClassroom(id: number): $CancellablePromise<void> {
    return $Call.ByID(32826096, id);
}

export function DeleteCourse(id: number): $CancellablePromise<void> {
    return $Call.ByID(2400459696, id);
}

export function DeleteDepartment(id: number): $CancellablePromise<void> {
    return $Call.ByID(521741391, id);
}

export function DeleteSemester(id: number): $CancellablePromise<void> {
    return $Call.ByID(246029095, id);
}

export function DeleteTeacher(id: number): $CancellablePromise<void> {
    return $Call.ByID(3486932189, id);
}

/**
 * GetActiveSemester returns the first semester with Status="active".
 * v0.5.5: 替代旧 IsActive 布尔逻辑，改用 Status 字段。
 */
export function GetActiveSemester(): $CancellablePromise<models$0.Semester | null> {
    return $Call.ByID(1572033238).then(($result: any) => {
        return $$createType1($result);
    });
}

export function GetClassGroups(): $CancellablePromise<models$0.ClassGroup[]> {
    return $Call.ByID(738541606).then(($result: any) => {
        return $$createType3($result);
    });
}

export function GetClassrooms(): $CancellablePromise<models$0.Classroom[]> {
    return $Call.ByID(625788786).then(($result: any) => {
        return $$createType5($result);
    });
}

export function GetCourses(): $CancellablePromise<models$0.Course[]> {
    return $Call.ByID(1247827488).then(($result: any) => {
        return $$createType7($result);
    });
}

/**
 * GetDatabasePath returns the absolute path to the active database file.
 */
export function GetDatabasePath(): $CancellablePromise<string> {
    return $Call.ByID(4115972420);
}

export function GetDepartments(): $CancellablePromise<models$0.Department[]> {
    return $Call.ByID(359877501).then(($result: any) => {
        return $$createType9($result);
    });
}

export function GetScheduleEntries(semesterID: number): $CancellablePromise<models$0.ScheduleEntry[]> {
    return $Call.ByID(1541252201, semesterID).then(($result: any) => {
        return $$createType11($result);
    });
}

export function GetSemesters(): $CancellablePromise<models$0.Semester[]> {
    return $Call.ByID(4004272785).then(($result: any) => {
        return $$createType12($result);
    });
}

export function GetSetting(key: string): $CancellablePromise<string> {
    return $Call.ByID(2106596506, key);
}

export function GetTeachers(): $CancellablePromise<models$0.Teacher[]> {
    return $Call.ByID(4028316649).then(($result: any) => {
        return $$createType14($result);
    });
}

/**
 * OpenDownloads opens the user's Downloads folder in the system file explorer.
 */
export function OpenDownloads(): $CancellablePromise<void> {
    return $Call.ByID(1032748571);
}

/**
 * RestoreDatabase replaces the current database with a backup file.
 * WARNING: this will overwrite all current data. The application should
 * restart after restore to reload the database.
 */
export function RestoreDatabase(backupPath: string): $CancellablePromise<void> {
    return $Call.ByID(4284031461, backupPath);
}

export function SaveSetting(key: string, value: string): $CancellablePromise<void> {
    return $Call.ByID(3754637109, key, value);
}

export function UpdateClassGroup(c: models$0.ClassGroup): $CancellablePromise<void> {
    return $Call.ByID(2402162084, c);
}

export function UpdateClassroom(c: models$0.Classroom): $CancellablePromise<void> {
    return $Call.ByID(3496546402, c);
}

export function UpdateCourse(c: models$0.Course): $CancellablePromise<void> {
    return $Call.ByID(3826924046, c);
}

export function UpdateDepartment(dept: models$0.Department): $CancellablePromise<void> {
    return $Call.ByID(1924014597, dept);
}

export function UpdateSemester(sem: models$0.Semester): $CancellablePromise<void> {
    return $Call.ByID(1025382337, sem);
}

export function UpdateTeacher(t: models$0.Teacher): $CancellablePromise<void> {
    return $Call.ByID(702117399, t);
}

// Private type creation functions
const $$createType0 = models$0.Semester.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = models$0.ClassGroup.createFrom;
const $$createType3 = $Create.Array($$createType2);
const $$createType4 = models$0.Classroom.createFrom;
const $$createType5 = $Create.Array($$createType4);
const $$createType6 = models$0.Course.createFrom;
const $$createType7 = $Create.Array($$createType6);
const $$createType8 = models$0.Department.createFrom;
const $$createType9 = $Create.Array($$createType8);
const $$createType10 = models$0.ScheduleEntry.createFrom;
const $$createType11 = $Create.Array($$createType10);
const $$createType12 = $Create.Array($$createType0);
const $$createType13 = models$0.Teacher.createFrom;
const $$createType14 = $Create.Array($$createType13);
