// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ResourceService handles CRUD for teachers, classrooms, courses, and class groups.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as models$0 from "../models/models.js";

/**
 * BackupDatabase copies the database file to a backup location.
 * Returns the backup file path.
 */
export function BackupDatabase(backupPath: string): $CancellablePromise<void> {
    return $Call.ByID(426460745, backupPath);
}

export function CreateClassGroup(c: models$0.ClassGroup): $CancellablePromise<void> {
    return $Call.ByID(2929636441, c);
}

export function CreateClassroom(c: models$0.Classroom): $CancellablePromise<void> {
    return $Call.ByID(2979645581, c);
}

export function CreateCourse(c: models$0.Course): $CancellablePromise<void> {
    return $Call.ByID(1220227755, c);
}

export function CreateDepartment(dept: models$0.Department): $CancellablePromise<void> {
    return $Call.ByID(1572938852, dept);
}

export function CreateSemester(sem: models$0.Semester): $CancellablePromise<void> {
    return $Call.ByID(2898724944, sem);
}

export function CreateTeacher(t: models$0.Teacher): $CancellablePromise<void> {
    return $Call.ByID(3813397992, t);
}

export function DeleteClassGroup(id: number): $CancellablePromise<void> {
    return $Call.ByID(3930905198, id);
}

export function DeleteClassroom(id: number): $CancellablePromise<void> {
    return $Call.ByID(32826096, id);
}

export function DeleteCourse(id: number): $CancellablePromise<void> {
    return $Call.ByID(2400459696, id);
}

export function DeleteDepartment(id: number): $CancellablePromise<void> {
    return $Call.ByID(521741391, id);
}

export function DeleteSemester(id: number): $CancellablePromise<void> {
    return $Call.ByID(246029095, id);
}

export function DeleteTeacher(id: number): $CancellablePromise<void> {
    return $Call.ByID(3486932189, id);
}

export function GetActiveSemester(): $CancellablePromise<models$0.Semester | null> {
    return $Call.ByID(1572033238);
}

export function GetClassGroups(): $CancellablePromise<models$0.ClassGroup[] | null> {
    return $Call.ByID(738541606);
}

export function GetClassrooms(): $CancellablePromise<models$0.Classroom[] | null> {
    return $Call.ByID(625788786);
}

export function GetCourses(): $CancellablePromise<models$0.Course[] | null> {
    return $Call.ByID(1247827488);
}

/**
 * GetDatabasePath returns the absolute path to the active database file.
 */
export function GetDatabasePath(): $CancellablePromise<string> {
    return $Call.ByID(4115972420);
}

export function GetDepartments(): $CancellablePromise<models$0.Department[] | null> {
    return $Call.ByID(359877501);
}

export function GetScheduleEntries(semester: string): $CancellablePromise<models$0.ScheduleEntry[] | null> {
    return $Call.ByID(1541252201, semester);
}

export function GetSemesters(): $CancellablePromise<models$0.Semester[] | null> {
    return $Call.ByID(4004272785);
}

export function GetSetting(key: string): $CancellablePromise<string> {
    return $Call.ByID(2106596506, key);
}

export function GetTeachers(): $CancellablePromise<models$0.Teacher[] | null> {
    return $Call.ByID(4028316649);
}

/**
 * OpenDownloads opens the user's Downloads folder in the system file explorer.
 */
export function OpenDownloads(): $CancellablePromise<void> {
    return $Call.ByID(1032748571);
}

/**
 * RestoreDatabase replaces the current database with a backup file.
 * WARNING: this will overwrite all current data. The application should
 * restart after restore to reload the database.
 */
export function RestoreDatabase(backupPath: string): $CancellablePromise<void> {
    return $Call.ByID(4284031461, backupPath);
}

export function SaveSetting(key: string, value: string): $CancellablePromise<void> {
    return $Call.ByID(3754637109, key, value);
}

export function UpdateClassGroup(c: models$0.ClassGroup): $CancellablePromise<void> {
    return $Call.ByID(2402162084, c);
}

export function UpdateClassroom(c: models$0.Classroom): $CancellablePromise<void> {
    return $Call.ByID(3496546402, c);
}

export function UpdateCourse(c: models$0.Course): $CancellablePromise<void> {
    return $Call.ByID(3826924046, c);
}

export function UpdateDepartment(dept: models$0.Department): $CancellablePromise<void> {
    return $Call.ByID(1924014597, dept);
}

export function UpdateSemester(sem: models$0.Semester): $CancellablePromise<void> {
    return $Call.ByID(1025382337, sem);
}

export function UpdateTeacher(t: models$0.Teacher): $CancellablePromise<void> {
    return $Call.ByID(702117399, t);
}
