// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ResourceService handles CRUD for teachers, classrooms, courses, and class groups.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as models$0 from "../models/models.js";

/**
 * BackupDatabase copies the database file to a backup location.
 * Returns the backup file path.
 * @param {string} backupPath
 * @returns {$CancellablePromise<void>}
 */
export function BackupDatabase(backupPath) {
    return $Call.ByID(426460745, backupPath);
}

/**
 * @param {models$0.ClassGroup} c
 * @returns {$CancellablePromise<void>}
 */
export function CreateClassGroup(c) {
    return $Call.ByID(2929636441, c);
}

/**
 * @param {models$0.Classroom} c
 * @returns {$CancellablePromise<void>}
 */
export function CreateClassroom(c) {
    return $Call.ByID(2979645581, c);
}

/**
 * @param {models$0.Course} c
 * @returns {$CancellablePromise<void>}
 */
export function CreateCourse(c) {
    return $Call.ByID(1220227755, c);
}

/**
 * @param {models$0.Department} dept
 * @returns {$CancellablePromise<void>}
 */
export function CreateDepartment(dept) {
    return $Call.ByID(1572938852, dept);
}

/**
 * @param {models$0.Semester} sem
 * @returns {$CancellablePromise<void>}
 */
export function CreateSemester(sem) {
    return $Call.ByID(2898724944, sem);
}

/**
 * @param {models$0.Teacher} t
 * @returns {$CancellablePromise<void>}
 */
export function CreateTeacher(t) {
    return $Call.ByID(3813397992, t);
}

/**
 * @param {number} id
 * @returns {$CancellablePromise<void>}
 */
export function DeleteClassGroup(id) {
    return $Call.ByID(3930905198, id);
}

/**
 * @param {number} id
 * @returns {$CancellablePromise<void>}
 */
export function DeleteClassroom(id) {
    return $Call.ByID(32826096, id);
}

/**
 * @param {number} id
 * @returns {$CancellablePromise<void>}
 */
export function DeleteCourse(id) {
    return $Call.ByID(2400459696, id);
}

/**
 * @param {number} id
 * @returns {$CancellablePromise<void>}
 */
export function DeleteDepartment(id) {
    return $Call.ByID(521741391, id);
}

/**
 * @param {number} id
 * @returns {$CancellablePromise<void>}
 */
export function DeleteSemester(id) {
    return $Call.ByID(246029095, id);
}

/**
 * @param {number} id
 * @returns {$CancellablePromise<void>}
 */
export function DeleteTeacher(id) {
    return $Call.ByID(3486932189, id);
}

/**
 * @returns {$CancellablePromise<models$0.Semester | null>}
 */
export function GetActiveSemester() {
    return $Call.ByID(1572033238).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * @returns {$CancellablePromise<models$0.ClassGroup[]>}
 */
export function GetClassGroups() {
    return $Call.ByID(738541606).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * @returns {$CancellablePromise<models$0.Classroom[]>}
 */
export function GetClassrooms() {
    return $Call.ByID(625788786).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType5($result);
    }));
}

/**
 * @returns {$CancellablePromise<models$0.Course[]>}
 */
export function GetCourses() {
    return $Call.ByID(1247827488).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType7($result);
    }));
}

/**
 * GetDatabasePath returns the absolute path to the active database file.
 * @returns {$CancellablePromise<string>}
 */
export function GetDatabasePath() {
    return $Call.ByID(4115972420);
}

/**
 * @returns {$CancellablePromise<models$0.Department[]>}
 */
export function GetDepartments() {
    return $Call.ByID(359877501).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType9($result);
    }));
}

/**
 * @param {string} semester
 * @returns {$CancellablePromise<models$0.ScheduleEntry[]>}
 */
export function GetScheduleEntries(semester) {
    return $Call.ByID(1541252201, semester).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType11($result);
    }));
}

/**
 * @returns {$CancellablePromise<models$0.Semester[]>}
 */
export function GetSemesters() {
    return $Call.ByID(4004272785).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType12($result);
    }));
}

/**
 * @param {string} key
 * @returns {$CancellablePromise<string>}
 */
export function GetSetting(key) {
    return $Call.ByID(2106596506, key);
}

/**
 * @returns {$CancellablePromise<models$0.Teacher[]>}
 */
export function GetTeachers() {
    return $Call.ByID(4028316649).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType14($result);
    }));
}

/**
 * OpenDownloads opens the user's Downloads folder in the system file explorer.
 * @returns {$CancellablePromise<void>}
 */
export function OpenDownloads() {
    return $Call.ByID(1032748571);
}

/**
 * RestoreDatabase replaces the current database with a backup file.
 * WARNING: this will overwrite all current data. The application should
 * restart after restore to reload the database.
 * @param {string} backupPath
 * @returns {$CancellablePromise<void>}
 */
export function RestoreDatabase(backupPath) {
    return $Call.ByID(4284031461, backupPath);
}

/**
 * @param {string} key
 * @param {string} value
 * @returns {$CancellablePromise<void>}
 */
export function SaveSetting(key, value) {
    return $Call.ByID(3754637109, key, value);
}

/**
 * @param {models$0.ClassGroup} c
 * @returns {$CancellablePromise<void>}
 */
export function UpdateClassGroup(c) {
    return $Call.ByID(2402162084, c);
}

/**
 * @param {models$0.Classroom} c
 * @returns {$CancellablePromise<void>}
 */
export function UpdateClassroom(c) {
    return $Call.ByID(3496546402, c);
}

/**
 * @param {models$0.Course} c
 * @returns {$CancellablePromise<void>}
 */
export function UpdateCourse(c) {
    return $Call.ByID(3826924046, c);
}

/**
 * @param {models$0.Department} dept
 * @returns {$CancellablePromise<void>}
 */
export function UpdateDepartment(dept) {
    return $Call.ByID(1924014597, dept);
}

/**
 * @param {models$0.Semester} sem
 * @returns {$CancellablePromise<void>}
 */
export function UpdateSemester(sem) {
    return $Call.ByID(1025382337, sem);
}

/**
 * @param {models$0.Teacher} t
 * @returns {$CancellablePromise<void>}
 */
export function UpdateTeacher(t) {
    return $Call.ByID(702117399, t);
}

// Private type creation functions
const $$createType0 = models$0.Semester.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = models$0.ClassGroup.createFrom;
const $$createType3 = $Create.Array($$createType2);
const $$createType4 = models$0.Classroom.createFrom;
const $$createType5 = $Create.Array($$createType4);
const $$createType6 = models$0.Course.createFrom;
const $$createType7 = $Create.Array($$createType6);
const $$createType8 = models$0.Department.createFrom;
const $$createType9 = $Create.Array($$createType8);
const $$createType10 = models$0.ScheduleEntry.createFrom;
const $$createType11 = $Create.Array($$createType10);
const $$createType12 = $Create.Array($$createType0);
const $$createType13 = models$0.Teacher.createFrom;
const $$createType14 = $Create.Array($$createType13);
