// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * SnapshotService manages schedule validation snapshots.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as models$0 from "../models/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * AnalyzeTeacherWorkload loads the current schedule entries and computes per-teacher workload analysis.
 * Pure post-hoc analysis — does not affect scoring or solver behaviour.
 */
export function AnalyzeTeacherWorkload(semester: string): $CancellablePromise<$models.TeacherWorkloadInfo[] | null> {
    return $Call.ByID(2269459629, semester);
}

/**
 * CompareSnapshots returns a structured diff between two snapshots
 * (A = baseline, B = comparison target).
 */
export function CompareSnapshots(aID: number, bID: number): $CancellablePromise<$models.SnapshotCompareResult | null> {
    return $Call.ByID(4235514270, aID, bID);
}

/**
 * CreateManualSnapshot generates a snapshot from the current schedule in the database.
 * It reads EnabledConstraints from the latest auto-snapshot (falling back to full defaults).
 */
export function CreateManualSnapshot(semester: string): $CancellablePromise<models$0.ScheduleSnapshot | null> {
    return $Call.ByID(299046732, semester);
}

/**
 * CreateSnapshot generates a snapshot from a scheduling result.
 */
export function CreateSnapshot(semester: string, dept: string, trigger: string, solver: string, entries: models$0.ScheduleEntry[] | null, teachers: models$0.Teacher[] | null, classrooms: models$0.Classroom[] | null, scoringCtx: $models.ScoringContext, solveTimeMs: number, conflictCount: number): $CancellablePromise<models$0.ScheduleSnapshot | null> {
    return $Call.ByID(1676786010, semester, dept, trigger, solver, entries, teachers, classrooms, scoringCtx, solveTimeMs, conflictCount);
}

/**
 * DeleteSnapshot removes a snapshot and its details.
 */
export function DeleteSnapshot(id: number): $CancellablePromise<void> {
    return $Call.ByID(1169474405, id);
}

/**
 * GetSnapshotWithDetails returns a single snapshot with its details preloaded.
 */
export function GetSnapshotWithDetails(id: number): $CancellablePromise<models$0.ScheduleSnapshot | null> {
    return $Call.ByID(769250772, id);
}

/**
 * GetSnapshots returns all snapshots for a semester.
 * Backfills Name for legacy snapshots that were created before the Name field existed.
 */
export function GetSnapshots(semester: string): $CancellablePromise<models$0.ScheduleSnapshot[] | null> {
    return $Call.ByID(3410442531, semester);
}

/**
 * RenameSnapshot updates the Name field of an existing snapshot.
 * Validates that the name is non-empty and within the size limit.
 */
export function RenameSnapshot(id: number, newName: string): $CancellablePromise<void> {
    return $Call.ByID(1987166232, id, newName);
}
