// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * SnapshotService manages schedule validation snapshots.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as models$0 from "../models/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * AnalyzeTeacherWorkload loads the current schedule entries and computes per-teacher workload analysis.
 * Pure post-hoc analysis — does not affect scoring or solver behaviour.
 * @param {string} semester
 * @returns {$CancellablePromise<$models.TeacherWorkloadInfo[]>}
 */
export function AnalyzeTeacherWorkload(semester) {
    return $Call.ByID(2269459629, semester).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * CompareSnapshots returns a structured diff between two snapshots
 * (A = baseline, B = comparison target).
 * @param {number} aID
 * @param {number} bID
 * @returns {$CancellablePromise<$models.SnapshotCompareResult | null>}
 */
export function CompareSnapshots(aID, bID) {
    return $Call.ByID(4235514270, aID, bID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * CreateManualSnapshot generates a snapshot from the current schedule in the database.
 * It reads EnabledConstraints from the latest auto-snapshot (falling back to full defaults).
 * @param {string} semester
 * @returns {$CancellablePromise<models$0.ScheduleSnapshot | null>}
 */
export function CreateManualSnapshot(semester) {
    return $Call.ByID(299046732, semester).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType5($result);
    }));
}

/**
 * CreateSnapshot generates a snapshot from a scheduling result.
 * @param {string} semester
 * @param {string} dept
 * @param {string} trigger
 * @param {string} solver
 * @param {models$0.ScheduleEntry[]} entries
 * @param {models$0.Teacher[]} teachers
 * @param {models$0.Classroom[]} classrooms
 * @param {$models.ScoringContext} scoringCtx
 * @param {number} solveTimeMs
 * @param {number} conflictCount
 * @returns {$CancellablePromise<models$0.ScheduleSnapshot | null>}
 */
export function CreateSnapshot(semester, dept, trigger, solver, entries, teachers, classrooms, scoringCtx, solveTimeMs, conflictCount) {
    return $Call.ByID(1676786010, semester, dept, trigger, solver, entries, teachers, classrooms, scoringCtx, solveTimeMs, conflictCount).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType5($result);
    }));
}

/**
 * DeleteSnapshot removes a snapshot and its details.
 * @param {number} id
 * @returns {$CancellablePromise<void>}
 */
export function DeleteSnapshot(id) {
    return $Call.ByID(1169474405, id);
}

/**
 * GetSnapshotWithDetails returns a single snapshot with its details preloaded.
 * @param {number} id
 * @returns {$CancellablePromise<models$0.ScheduleSnapshot | null>}
 */
export function GetSnapshotWithDetails(id) {
    return $Call.ByID(769250772, id).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType5($result);
    }));
}

/**
 * GetSnapshots returns all snapshots for a semester.
 * Backfills Name for legacy snapshots that were created before the Name field existed.
 * @param {string} semester
 * @returns {$CancellablePromise<models$0.ScheduleSnapshot[]>}
 */
export function GetSnapshots(semester) {
    return $Call.ByID(3410442531, semester).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType6($result);
    }));
}

/**
 * RenameSnapshot updates the Name field of an existing snapshot.
 * Validates that the name is non-empty and within the size limit.
 * @param {number} id
 * @param {string} newName
 * @returns {$CancellablePromise<void>}
 */
export function RenameSnapshot(id, newName) {
    return $Call.ByID(1987166232, id, newName);
}

// Private type creation functions
const $$createType0 = $models.TeacherWorkloadInfo.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = $models.SnapshotCompareResult.createFrom;
const $$createType3 = $Create.Nullable($$createType2);
const $$createType4 = models$0.ScheduleSnapshot.createFrom;
const $$createType5 = $Create.Nullable($$createType4);
const $$createType6 = $Create.Array($$createType4);
