// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * TeachingTaskService handles CRUD and intelligent detection for teaching tasks.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as models$0 from "../models/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * CreateTeachingTask creates a teaching task with its class associations.
 */
export function CreateTeachingTask(task: models$0.TeachingTask, classGroupIDs: number[] | null): $CancellablePromise<void> {
    return $Call.ByID(1884256178, task, classGroupIDs);
}

/**
 * DeleteTeachingTask soft-deletes a teaching task and its class associations.
 */
export function DeleteTeachingTask(id: number): $CancellablePromise<void> {
    return $Call.ByID(763924985, id);
}

/**
 * DetectMergeableTasks scans teaching tasks for the same semester and finds groups
 * that share the same course name and teacher, suggesting they could be merged
 * into a combined class offering.
 */
export function DetectMergeableTasks(semesterID: number): $CancellablePromise<$models.MergeableGroup[] | null> {
    return $Call.ByID(1305060129, semesterID);
}

/**
 * ExportTeachingTasks returns teaching task data formatted for Excel export.
 */
export function ExportTeachingTasks(semesterID: number): $CancellablePromise<(string[] | null)[] | null> {
    return $Call.ByID(3612443393, semesterID);
}

/**
 * GetTeachingTask returns a single teaching task with relations.
 */
export function GetTeachingTask(id: number): $CancellablePromise<models$0.TeachingTask | null> {
    return $Call.ByID(2408803522, id);
}

/**
 * ImportTeachingTasks imports teaching tasks from a 2D string array.
 * Expected columns: [课程编号, 教师编号, 班级编号列表(逗号分隔)]
 */
export function ImportTeachingTasks(semesterID: number, rows: (string[] | null)[] | null): $CancellablePromise<[number, string[] | null]> {
    return $Call.ByID(2540860548, semesterID, rows);
}

/**
 * ListTeachingTasks returns all teaching tasks for a semester, with preloaded relations.
 */
export function ListTeachingTasks(semesterID: number): $CancellablePromise<models$0.TeachingTask[] | null> {
    return $Call.ByID(4246079887, semesterID);
}

/**
 * UpdateTeachingTask updates a teaching task and replaces its class associations.
 */
export function UpdateTeachingTask(id: number, task: models$0.TeachingTask, classGroupIDs: number[] | null): $CancellablePromise<void> {
    return $Call.ByID(2358490451, id, task, classGroupIDs);
}
