// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * TeachingTaskService handles CRUD, import/export for teaching tasks.
 * v0.5.4: 自动智能合班能力已移除；多班绑定仅通过显式创建/更新/导入完成。
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as models$0 from "../models/models.js";

/**
 * CreateTeachingTask creates a teaching task with its class associations.
 */
export function CreateTeachingTask(task: models$0.TeachingTask, classGroupIDs: number[] | null): $CancellablePromise<void> {
    return $Call.ByID(1884256178, task, classGroupIDs);
}

/**
 * DeleteTeachingTask soft-deletes a teaching task and its class associations.
 */
export function DeleteTeachingTask(id: number): $CancellablePromise<void> {
    return $Call.ByID(763924985, id);
}

/**
 * ExportTeachingTasks returns teaching task data formatted for Excel export.
 */
export function ExportTeachingTasks(semesterID: number): $CancellablePromise<(string[] | null)[] | null> {
    return $Call.ByID(3612443393, semesterID);
}

/**
 * GetTeachingTask returns a single teaching task with relations.
 */
export function GetTeachingTask(id: number): $CancellablePromise<models$0.TeachingTask | null> {
    return $Call.ByID(2408803522, id);
}

/**
 * ImportTeachingTasks imports teaching tasks from a 2D string array.
 * Columns: [课程代码, 教师编号, 班级编号, 总学时?, 起始周?, 结束周?, 周最大学时?]
 */
export function ImportTeachingTasks(semesterID: number, rows: (string[] | null)[] | null): $CancellablePromise<[number, string[] | null]> {
    return $Call.ByID(2540860548, semesterID, rows);
}

/**
 * ListTeachingTasks returns all teaching tasks for a semester, with preloaded relations.
 */
export function ListTeachingTasks(semesterID: number): $CancellablePromise<models$0.TeachingTask[] | null> {
    return $Call.ByID(4246079887, semesterID);
}

/**
 * UpdateTeachingTask updates a teaching task and replaces its class associations.
 */
export function UpdateTeachingTask(id: number, task: models$0.TeachingTask, classGroupIDs: number[] | null): $CancellablePromise<void> {
    return $Call.ByID(2358490451, id, task, classGroupIDs);
}
