// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * TeachingTaskService handles CRUD and intelligent detection for teaching tasks.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as models$0 from "../models/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * CreateTeachingTask creates a teaching task with its class associations.
 * @param {models$0.TeachingTask} task
 * @param {number[]} classGroupIDs
 * @returns {$CancellablePromise<void>}
 */
export function CreateTeachingTask(task, classGroupIDs) {
    return $Call.ByID(1884256178, task, classGroupIDs);
}

/**
 * DeleteTeachingTask soft-deletes a teaching task and its class associations.
 * @param {number} id
 * @returns {$CancellablePromise<void>}
 */
export function DeleteTeachingTask(id) {
    return $Call.ByID(763924985, id);
}

/**
 * DetectMergeableTasks scans teaching tasks for the same semester and finds groups
 * that share the same course name and teacher, suggesting they could be merged
 * into a combined class offering.
 * @param {number} semesterID
 * @returns {$CancellablePromise<$models.MergeableGroup[]>}
 */
export function DetectMergeableTasks(semesterID) {
    return $Call.ByID(1305060129, semesterID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * ExportTeachingTasks returns teaching task data formatted for Excel export.
 * @param {number} semesterID
 * @returns {$CancellablePromise<string[][]>}
 */
export function ExportTeachingTasks(semesterID) {
    return $Call.ByID(3612443393, semesterID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * GetTeachingTask returns a single teaching task with relations.
 * @param {number} id
 * @returns {$CancellablePromise<models$0.TeachingTask | null>}
 */
export function GetTeachingTask(id) {
    return $Call.ByID(2408803522, id).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType5($result);
    }));
}

/**
 * ImportTeachingTasks imports teaching tasks from a 2D string array.
 * Expected columns: [课程编号, 教师编号, 班级编号列表(逗号分隔)]
 * @param {number} semesterID
 * @param {string[][]} rows
 * @returns {$CancellablePromise<[number, string[]]>}
 */
export function ImportTeachingTasks(semesterID, rows) {
    return $Call.ByID(2540860548, semesterID, rows).then(/** @type {($result: any) => any} */(($result) => {
        $result[1] = $$createType2($result[1]);
        return $result;
    }));
}

/**
 * ListTeachingTasks returns all teaching tasks for a semester, with preloaded relations.
 * @param {number} semesterID
 * @returns {$CancellablePromise<models$0.TeachingTask[]>}
 */
export function ListTeachingTasks(semesterID) {
    return $Call.ByID(4246079887, semesterID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType6($result);
    }));
}

/**
 * UpdateTeachingTask updates a teaching task and replaces its class associations.
 * @param {number} id
 * @param {models$0.TeachingTask} task
 * @param {number[]} classGroupIDs
 * @returns {$CancellablePromise<void>}
 */
export function UpdateTeachingTask(id, task, classGroupIDs) {
    return $Call.ByID(2358490451, id, task, classGroupIDs);
}

// Private type creation functions
const $$createType0 = $models.MergeableGroup.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = $Create.Array($Create.Any);
const $$createType3 = $Create.Array($$createType2);
const $$createType4 = models$0.TeachingTask.createFrom;
const $$createType5 = $Create.Nullable($$createType4);
const $$createType6 = $Create.Array($$createType4);
