// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * VersionService manages ScheduleVersion and ScheduleVersionEntry records.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as models$0 from "../models/models.js";

/**
 * ClearSemesterVersions removes every ScheduleVersion (and its entries)
 * belonging to the given semester in a single transaction. Only affects
 * the specified semester; other semesters, courses, teachers, classrooms,
 * snapshots, and live schedule entries are untouched.
 * 
 * Returns the number of versions deleted. If the semester has no versions,
 * returns 0 with a nil error.
 * @param {number} semesterID
 * @returns {$CancellablePromise<number>}
 */
export function ClearSemesterVersions(semesterID) {
    return $Call.ByID(2909980406, semesterID);
}

/**
 * CreateManualVersion saves the current schedule as a new version with
 * source = ManualAdjust. It loads the live schedule entries from the
 * database, computes the current ScoreSchedule score, and persists a
 * new ScheduleVersion (with entries) in a single transaction.
 * @param {number} semesterID
 * @param {string} name
 * @returns {$CancellablePromise<models$0.ScheduleVersion | null>}
 */
export function CreateManualVersion(semesterID, name) {
    return $Call.ByID(443717862, semesterID, name).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * CreateVersion stores a new historical version from the given schedule entries.
 * It automatically enforces the per-semester retention limit (DefaultMaxVersions).
 * 
 * semesterID — Semester.ID (v0.5.5 起改为直接传 FK，取代旧的 name 查找).
 * name       — user-visible version label (e.g. "自动方案 #3").
 * source     — one of the VersionSource* constants.
 * score      — final ScoreSchedule total at the time of capture.
 * solver     — solver identifier ("simulated_annealing", "ortools", etc.).
 * entries    — current schedule entries to copy into the version.
 * @param {number} semesterID
 * @param {string} name
 * @param {string} source
 * @param {number} score
 * @param {string} solver
 * @param {models$0.ScheduleEntry[]} entries
 * @returns {$CancellablePromise<models$0.ScheduleVersion | null>}
 */
export function CreateVersion(semesterID, name, source, score, solver, entries) {
    return $Call.ByID(523734880, semesterID, name, source, score, solver, entries).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * DeleteVersion removes a version and its entries by ID.
 * @param {number} id
 * @returns {$CancellablePromise<void>}
 */
export function DeleteVersion(id) {
    return $Call.ByID(2322552237, id);
}

/**
 * GetVersion retrieves a single version with its entries preloaded.
 * @param {number} id
 * @returns {$CancellablePromise<models$0.ScheduleVersion | null>}
 */
export function GetVersion(id) {
    return $Call.ByID(2988749672, id).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * ListVersions returns all versions for the given semester, ordered by
 * created_at descending (newest first).
 * @param {number} semesterID
 * @returns {$CancellablePromise<models$0.ScheduleVersion[]>}
 */
export function ListVersions(semesterID) {
    return $Call.ByID(1900345469, semesterID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

// Private type creation functions
const $$createType0 = models$0.ScheduleVersion.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = $Create.Array($$createType0);
