// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * VersionService manages ScheduleVersion and ScheduleVersionEntry records.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as models$0 from "../models/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * AnalyzeTeacherWorkload loads the current schedule entries and computes per-teacher workload analysis.
 * Pure post-hoc analysis — does not affect scoring or solver behaviour.
 * TODO(v0.6.0): Adapt AnalyzeTeacherWorkload for TimeAssignment+ScheduleEntry split.
 * @param {number} semesterID
 * @returns {$CancellablePromise<$models.TeacherWorkloadInfo[]>}
 */
export function AnalyzeTeacherWorkload(semesterID) {
    return $Call.ByID(1142847927, semesterID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * ClearSemesterVersions removes every ScheduleVersion (and its entries)
 * belonging to the given semester in a single transaction. Only affects
 * the specified semester; other semesters, courses, teachers, classrooms,
 * snapshots, and live schedule entries are untouched.
 * 
 * Returns the number of versions deleted. If the semester has no versions,
 * returns 0 with a nil error.
 * @param {number} semesterID
 * @returns {$CancellablePromise<number>}
 */
export function ClearSemesterVersions(semesterID) {
    return $Call.ByID(2909980406, semesterID);
}

/**
 * CompareVersions returns a structured diff between two versions (A=baseline, B=target).
 * Includes teacher-level diffs and entry-level diffs (moved/added/removed).
 * @param {number} aID
 * @param {number} bID
 * @returns {$CancellablePromise<$models.VersionCompareResult | null>}
 */
export function CompareVersions(aID, bID) {
    return $Call.ByID(2173696750, aID, bID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * CreateManualReport generates a version from the current schedule in the database,
 * computing full scoring details. This replaces the old SnapshotService.CreateManualSnapshot.
 * TODO(v0.6.0): Adapt CreateManualReport for TimeAssignment+ScheduleEntry split.
 * @param {number} semesterID
 * @returns {$CancellablePromise<models$0.ScheduleVersion | null>}
 */
export function CreateManualReport(semesterID) {
    return $Call.ByID(2740214144, semesterID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType5($result);
    }));
}

/**
 * CreateManualVersion saves the current schedule as a new version with
 * source = ManualAdjust. It loads the live schedule entries from the
 * database, computes the current ScoreSchedule score, and persists a
 * new ScheduleVersion (with entries) in a single transaction.
 * TODO(v0.6.0): Adapt CreateManualVersion for TimeAssignment+ScheduleEntry split.
 * @param {number} semesterID
 * @param {string} name
 * @returns {$CancellablePromise<models$0.ScheduleVersion | null>}
 */
export function CreateManualVersion(semesterID, name) {
    return $Call.ByID(443717862, semesterID, name).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType5($result);
    }));
}

/**
 * CreateVersionFromSchedule creates a version with full scoring details and
 * teacher breakdowns from a scheduling result. This is the unified replacement
 * for both the old SnapshotService.CreateSnapshot and VersionService.CreateVersion.
 * 
 * It computes ScoreSchedule internally, stores entries, scoring fields, and
 * per-teacher VersionDetail records in a single transaction.
 * TODO(v0.6.0): Adapt CreateVersionFromSchedule for TimeAssignment+ScheduleEntry split.
 * @param {number} semesterID
 * @param {string} dept
 * @param {string} trigger
 * @param {string} solver
 * @param {models$0.ScheduleEntry[]} entries
 * @param {models$0.Teacher[]} teachers
 * @param {models$0.Classroom[]} classrooms
 * @param {$models.ScoringContext} scoringCtx
 * @param {number} solveTimeMs
 * @param {number} conflictCount
 * @returns {$CancellablePromise<models$0.ScheduleVersion | null>}
 */
export function CreateVersionFromSchedule(semesterID, dept, trigger, solver, entries, teachers, classrooms, scoringCtx, solveTimeMs, conflictCount) {
    return $Call.ByID(3458152285, semesterID, dept, trigger, solver, entries, teachers, classrooms, scoringCtx, solveTimeMs, conflictCount).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType5($result);
    }));
}

/**
 * DeleteVersion removes a version and its entries/details by ID in a single transaction.
 * @param {number} id
 * @returns {$CancellablePromise<void>}
 */
export function DeleteVersion(id) {
    return $Call.ByID(2322552237, id);
}

/**
 * GetVersion retrieves a single version with its entries preloaded.
 * @param {number} id
 * @returns {$CancellablePromise<models$0.ScheduleVersion | null>}
 */
export function GetVersion(id) {
    return $Call.ByID(2988749672, id).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType5($result);
    }));
}

/**
 * GetVersionWithDetails returns a single version with its Details preloaded.
 * Used by the report page to display per-teacher scoring breakdown.
 * @param {number} id
 * @returns {$CancellablePromise<models$0.ScheduleVersion | null>}
 */
export function GetVersionWithDetails(id) {
    return $Call.ByID(3281964470, id).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType5($result);
    }));
}

/**
 * @param {number} semesterID
 * @returns {$CancellablePromise<models$0.ScheduleVersion[]>}
 */
export function ListVersions(semesterID) {
    return $Call.ByID(1900345469, semesterID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType6($result);
    }));
}

/**
 * RenameVersion updates the Name field of an existing version.
 * @param {number} id
 * @param {string} newName
 * @returns {$CancellablePromise<void>}
 */
export function RenameVersion(id, newName) {
    return $Call.ByID(3863980246, id, newName);
}

/**
 * RestoreVersion restores a historical version as the current schedule.
 * It loads the version entries, replaces the current schedule for the semester,
 * and creates a new version with source=Restore to record the action.
 * TODO(v0.6.0): Adapt RestoreVersion for TimeAssignment+ScheduleEntry split.
 * @param {number} versionID
 * @returns {$CancellablePromise<void>}
 */
export function RestoreVersion(versionID) {
    return $Call.ByID(914410806, versionID);
}

// Private type creation functions
const $$createType0 = $models.TeacherWorkloadInfo.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = $models.VersionCompareResult.createFrom;
const $$createType3 = $Create.Nullable($$createType2);
const $$createType4 = models$0.ScheduleVersion.createFrom;
const $$createType5 = $Create.Nullable($$createType4);
const $$createType6 = $Create.Array($$createType4);
