// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * VersionService manages ScheduleVersion and ScheduleVersionEntry records.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as models$0 from "../models/models.js";

/**
 * CreateVersion stores a new historical version from the given schedule entries.
 * It automatically enforces the per-semester retention limit (DefaultMaxVersions).
 * 
 * semester — semester name string, used to look up Semester.ID.
 * name     — user-visible version label (e.g. "自动方案 #3").
 * source   — one of the VersionSource* constants.
 * score    — final ScoreSchedule total at the time of capture.
 * solver   — solver identifier ("simulated_annealing", "ortools", etc.).
 * entries  — current schedule entries to copy into the version.
 */
export function CreateVersion(semester: string, name: string, source: string, score: number, solver: string, entries: models$0.ScheduleEntry[] | null): $CancellablePromise<models$0.ScheduleVersion | null> {
    return $Call.ByID(523734880, semester, name, source, score, solver, entries);
}

/**
 * DeleteVersion removes a version and its entries by ID.
 */
export function DeleteVersion(id: number): $CancellablePromise<void> {
    return $Call.ByID(2322552237, id);
}

/**
 * GetVersion retrieves a single version with its entries preloaded.
 */
export function GetVersion(id: number): $CancellablePromise<models$0.ScheduleVersion | null> {
    return $Call.ByID(2988749672, id);
}

/**
 * ListVersions returns all versions for the given semester, ordered by
 * created_at descending (newest first).
 */
export function ListVersions(semester: string): $CancellablePromise<models$0.ScheduleVersion[] | null> {
    return $Call.ByID(1900345469, semester);
}
