// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export {
    Building,
    ClassGroup,
    Classroom,
    Course,
    DayOfWeek,
    Department,
    ScheduleEntry,
    ScheduleVersion,
    ScheduleVersionEntry,
    Semester,
    Teacher,
    TeachingTask,
    TeachingTaskClass,
    TimeAssignment,
    VersionDetail
} from "./models.js";

import * as $models from "./models.js";

/**
 * Period represents a teaching period slot (0-indexed internal, 1-indexed for display).
 * Period 0 = 第1节, Period 9 = 第10节, etc.
 * @typedef {$models.Period} Period
 */
