// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export {
    DayOfWeek
} from "./models.js";

export type {
    Building,
    ClassGroup,
    Classroom,
    Course,
    Department,
    Period,
    ScheduleEntry,
    ScheduleVersion,
    ScheduleVersionEntry,
    Semester,
    Teacher,
    TeachingTask,
    TeachingTaskClass,
    VersionDetail
} from "./models.js";
