// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as gorm$0 from "../../../gorm.io/gorm/models.js";

/**
 * Building represents a physical building on campus (e.g., "1 教", "5 教 A 区", "体育馆").
 * 
 * Core Domain: 通用建筑抽象，不含任何学校特定规则。
 *   - Code 由学校自定义，仅作唯一标识（如 "1"、"5A"、"6A"、"GYM"）。
 *   - Name 作为 UI 展示名（如 "1 教"、"5 教 A 区"、"体育馆"）。
 *   - Category 描述楼栋整体功能定位，但不硬约束该楼内的教室类型（教学楼里
 *     也可以有机房；实验楼里也可以有多媒体教室 —— 由 seed / 用户配置决定）。
 * 
 * 编号解析规则（"6教=实验楼" / "分 A/B 区" 等）不属于 Core，位于
 * backend/services/parsers/<school>/ adapter 层。
 */
export class Building {
    /**
     * Creates a new Building instance.
     * @param {Partial<Building>} [$$source = {}] - The source object to create the Building.
     */
    constructor($$source = {}) {
        if (!("ID" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["ID"] = 0;
        }
        if (!("CreatedAt" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["CreatedAt"] = "0001-01-01T00:00:00.000Z";
        }
        if (!("UpdatedAt" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["UpdatedAt"] = "0001-01-01T00:00:00.000Z";
        }
        if (!("DeletedAt" in $$source)) {
            /**
             * @member
             * @type {gorm$0.DeletedAt}
             */
            this["DeletedAt"] = null;
        }
        if (!("code" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["code"] = "";
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("category" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["category"] = "";
        }
        if (!("status" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["status"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Building instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Building}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Building(/** @type {Partial<Building>} */($$parsedSource));
    }
}

/**
 * ClassGroup represents a student class/group (e.g., 计算机2301).
 */
export class ClassGroup {
    /**
     * Creates a new ClassGroup instance.
     * @param {Partial<ClassGroup>} [$$source = {}] - The source object to create the ClassGroup.
     */
    constructor($$source = {}) {
        if (!("ID" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["ID"] = 0;
        }
        if (!("CreatedAt" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["CreatedAt"] = "0001-01-01T00:00:00.000Z";
        }
        if (!("UpdatedAt" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["UpdatedAt"] = "0001-01-01T00:00:00.000Z";
        }
        if (!("DeletedAt" in $$source)) {
            /**
             * @member
             * @type {gorm$0.DeletedAt}
             */
            this["DeletedAt"] = null;
        }
        if (!("code" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["code"] = "";
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("dept" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["dept"] = "";
        }
        if (!("grade" in $$source)) {
            /**
             * 入学年份, e.g. 2023
             * @member
             * @type {number}
             */
            this["grade"] = 0;
        }
        if (!("students" in $$source)) {
            /**
             * 学生人数
             * @member
             * @type {number}
             */
            this["students"] = 0;
        }
        if (!("status" in $$source)) {
            /**
             * active, inactive
             * @member
             * @type {string}
             */
            this["status"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ClassGroup instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ClassGroup}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ClassGroup(/** @type {Partial<ClassGroup>} */($$parsedSource));
    }
}

/**
 * Classroom represents a physical room for teaching.
 * 
 * v0.5.5 Stage B: 通用资源领域重构。
 *   - Building string → BuildingID FK + Building Association（关联 Building 表）
 *   - Type → RoomType（英文枚举，见 room_types.go）
 *   - 新增 Number 字段（教室号，不含楼栋前缀，如 "302" / "001" / "422"）
 *   - Code 字段仅是"唯一标识字符串"，无内在结构约束；编号解析规则在 adapter 层
 */
export class Classroom {
    /**
     * Creates a new Classroom instance.
     * @param {Partial<Classroom>} [$$source = {}] - The source object to create the Classroom.
     */
    constructor($$source = {}) {
        if (!("ID" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["ID"] = 0;
        }
        if (!("CreatedAt" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["CreatedAt"] = "0001-01-01T00:00:00.000Z";
        }
        if (!("UpdatedAt" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["UpdatedAt"] = "0001-01-01T00:00:00.000Z";
        }
        if (!("DeletedAt" in $$source)) {
            /**
             * @member
             * @type {gorm$0.DeletedAt}
             */
            this["DeletedAt"] = null;
        }
        if (!("code" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["code"] = "";
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("buildingId" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["buildingId"] = 0;
        }
        if (!("floor" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["floor"] = 0;
        }
        if (!("number" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["number"] = "";
        }
        if (!("capacity" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["capacity"] = 0;
        }
        if (!("roomType" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["roomType"] = "";
        }
        if (!("status" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["status"] = "";
        }
        if (!("equipment" in $$source)) {
            /**
             * +v0.5.3: 设备列表 JSON array，如 ["projector","smartboard","aircon"]
             * @member
             * @type {string}
             */
            this["equipment"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * Association
             * @member
             * @type {Building | undefined}
             */
            this["building"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Classroom instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Classroom}
     */
    static createFrom($$source = {}) {
        const $$createField13_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("building" in $$parsedSource) {
            $$parsedSource["building"] = $$createField13_0($$parsedSource["building"]);
        }
        return new Classroom(/** @type {Partial<Classroom>} */($$parsedSource));
    }
}

/**
 * Course represents a course in the curriculum.
 */
export class Course {
    /**
     * Creates a new Course instance.
     * @param {Partial<Course>} [$$source = {}] - The source object to create the Course.
     */
    constructor($$source = {}) {
        if (!("ID" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["ID"] = 0;
        }
        if (!("CreatedAt" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["CreatedAt"] = "0001-01-01T00:00:00.000Z";
        }
        if (!("UpdatedAt" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["UpdatedAt"] = "0001-01-01T00:00:00.000Z";
        }
        if (!("DeletedAt" in $$source)) {
            /**
             * @member
             * @type {gorm$0.DeletedAt}
             */
            this["DeletedAt"] = null;
        }
        if (!("code" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["code"] = "";
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("dept" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["dept"] = "";
        }
        if (!("credit" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["credit"] = 0;
        }
        if (!("type" in $$source)) {
            /**
             * 专业必修, 全校选修, etc.
             * @member
             * @type {string}
             */
            this["type"] = "";
        }
        if (!("hours" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["hours"] = 0;
        }
        if (!("status" in $$source)) {
            /**
             * active, inactive
             * @member
             * @type {string}
             */
            this["status"] = "";
        }
        if (!("category" in $$source)) {
            /**
             * +v0.5.3: 课程类别，用于资源匹配。空值=由名称推断(兼容, Deprecated)。
             * @member
             * @type {string}
             */
            this["category"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Course instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Course}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Course(/** @type {Partial<Course>} */($$parsedSource));
    }
}

/**
 * DayOfWeek represents a day in the teaching week (0 = Monday, 6 = Sunday).
 * This is the canonical internal representation throughout the system.
 * Display conversion (0→"周一", etc.) is handled by the frontend DAY_NAMES mapping.
 * @readonly
 * @enum {number}
 */
export const DayOfWeek = {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero: 0,

    Mon: 0,
    Tue: 1,
    Wed: 2,
    Thu: 3,
    Fri: 4,
    Sat: 5,
    Sun: 6,
};

/**
 * Department represents a college/faculty (e.g., 计算机学院, 材料科学与工程学院).
 */
export class Department {
    /**
     * Creates a new Department instance.
     * @param {Partial<Department>} [$$source = {}] - The source object to create the Department.
     */
    constructor($$source = {}) {
        if (!("ID" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["ID"] = 0;
        }
        if (!("CreatedAt" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["CreatedAt"] = "0001-01-01T00:00:00.000Z";
        }
        if (!("UpdatedAt" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["UpdatedAt"] = "0001-01-01T00:00:00.000Z";
        }
        if (!("DeletedAt" in $$source)) {
            /**
             * @member
             * @type {gorm$0.DeletedAt}
             */
            this["DeletedAt"] = null;
        }
        if (!("code" in $$source)) {
            /**
             * 院系代码，如 "cs"
             * @member
             * @type {string}
             */
            this["code"] = "";
        }
        if (!("name" in $$source)) {
            /**
             * 院系名称，如 "计算机学院"
             * @member
             * @type {string}
             */
            this["name"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Department instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Department}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Department(/** @type {Partial<Department>} */($$parsedSource));
    }
}

/**
 * Period represents a teaching period slot (0-indexed internal, 1-indexed for display).
 * Period 0 = 第1节, Period 9 = 第10节, etc.
 * @typedef {number} Period
 */

/**
 * ScheduleEntry 是 v0.6.0 模型拆分后的资源分配实体。
 * 一条 ScheduleEntry = 一个 TimeAssignment 分配到一间 Classroom。
 * TIME_ONLY 模式下本表为零行 (INV-E1)。
 */
export class ScheduleEntry {
    /**
     * Creates a new ScheduleEntry instance.
     * @param {Partial<ScheduleEntry>} [$$source = {}] - The source object to create the ScheduleEntry.
     */
    constructor($$source = {}) {
        if (!("ID" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["ID"] = 0;
        }
        if (!("CreatedAt" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["CreatedAt"] = "0001-01-01T00:00:00.000Z";
        }
        if (!("UpdatedAt" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["UpdatedAt"] = "0001-01-01T00:00:00.000Z";
        }
        if (!("DeletedAt" in $$source)) {
            /**
             * @member
             * @type {gorm$0.DeletedAt}
             */
            this["DeletedAt"] = null;
        }
        if (!("semesterId" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["semesterId"] = 0;
        }
        if (!("scheduleVersionId" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["scheduleVersionId"] = 0;
        }
        if (!("timeAssignmentId" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["timeAssignmentId"] = 0;
        }
        if (!("classroomId" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["classroomId"] = 0;
        }
        if (/** @type {any} */(false)) {
            /**
             * Associations (read-only preloads)
             * @member
             * @type {TimeAssignment | null | undefined}
             */
            this["timeAssignment"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {Classroom | undefined}
             */
            this["classroom"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ScheduleEntry instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ScheduleEntry}
     */
    static createFrom($$source = {}) {
        const $$createField8_0 = $$createType2;
        const $$createField9_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("timeAssignment" in $$parsedSource) {
            $$parsedSource["timeAssignment"] = $$createField8_0($$parsedSource["timeAssignment"]);
        }
        if ("classroom" in $$parsedSource) {
            $$parsedSource["classroom"] = $$createField9_0($$parsedSource["classroom"]);
        }
        return new ScheduleEntry(/** @type {Partial<ScheduleEntry>} */($$parsedSource));
    }
}

/**
 * ScheduleVersion is the single unified entity representing a saved schedule state.
 * It combines the former ScheduleSnapshot (scoring details) and ScheduleVersion
 * (actual entries) into one record. Every version has both the full entry set and
 * the complete scoring breakdown, eliminating the previous split-brain design.
 */
export class ScheduleVersion {
    /**
     * Creates a new ScheduleVersion instance.
     * @param {Partial<ScheduleVersion>} [$$source = {}] - The source object to create the ScheduleVersion.
     */
    constructor($$source = {}) {
        if (!("ID" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["ID"] = 0;
        }
        if (!("CreatedAt" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["CreatedAt"] = "0001-01-01T00:00:00.000Z";
        }
        if (!("UpdatedAt" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["UpdatedAt"] = "0001-01-01T00:00:00.000Z";
        }
        if (!("DeletedAt" in $$source)) {
            /**
             * @member
             * @type {gorm$0.DeletedAt}
             */
            this["DeletedAt"] = null;
        }
        if (!("semesterId" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["semesterId"] = 0;
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("source" in $$source)) {
            /**
             * AutoGenerate | ManualAdjust | Import | Restore | Copy
             * @member
             * @type {string}
             */
            this["source"] = "";
        }
        if (!("solver" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["solver"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["mode"] = undefined;
        }
        if (!("hardPassed" in $$source)) {
            /**
             * Hard constraint status (merged from ScheduleSnapshot)
             * @member
             * @type {boolean}
             */
            this["hardPassed"] = false;
        }
        if (!("teacherConflicts" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["teacherConflicts"] = 0;
        }
        if (!("roomConflicts" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["roomConflicts"] = 0;
        }
        if (!("classConflicts" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["classConflicts"] = 0;
        }
        if (!("totalScore" in $$source)) {
            /**
             * Soft constraint scores (merged from ScheduleSnapshot)
             * @member
             * @type {number}
             */
            this["totalScore"] = 0;
        }
        if (!("finalScore" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["finalScore"] = 0;
        }
        if (!("teacherPref" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["teacherPref"] = 0;
        }
        if (!("courseSpacing" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["courseSpacing"] = 0;
        }
        if (!("teacherDays" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["teacherDays"] = 0;
        }
        if (!("lowFloorPref" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["lowFloorPref"] = 0;
        }
        if (!("weekendAvoid" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["weekendAvoid"] = 0;
        }
        if (!("pePeriodPref" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["pePeriodPref"] = 0;
        }
        if (!("studentFatigue" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["studentFatigue"] = 0;
        }
        if (!("capacityWarn" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["capacityWarn"] = 0;
        }
        if (!("enabledConstraints" in $$source)) {
            /**
             * Scoring configuration (merged from ScheduleSnapshot)
             * @member
             * @type {string}
             */
            this["enabledConstraints"] = "";
        }
        if (!("scoreVersion" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["scoreVersion"] = 0;
        }
        if (!("perCategoryMax" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["perCategoryMax"] = 0;
        }
        if (!("enabledCategoryCount" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["enabledCategoryCount"] = 0;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["categoryMaxes"] = undefined;
        }
        if (!("placedSessions" in $$source)) {
            /**
             * Placement completeness (merged from ScheduleSnapshot)
             * @member
             * @type {number}
             */
            this["placedSessions"] = 0;
        }
        if (!("expectedSessions" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["expectedSessions"] = 0;
        }
        if (!("completeness" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["completeness"] = 0;
        }
        if (!("entryCount" in $$source)) {
            /**
             * Statistics
             * @member
             * @type {number}
             */
            this["entryCount"] = 0;
        }
        if (!("solveTimeMs" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["solveTimeMs"] = 0;
        }
        if (/** @type {any} */(false)) {
            /**
             * Linked data
             * @member
             * @type {ScheduleVersionEntry[] | undefined}
             */
            this["entries"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {VersionDetail[] | undefined}
             */
            this["details"] = undefined;
        }
        if (!("score" in $$source)) {
            /**
             * Deprecated: Score is kept for backward compatibility; use FinalScore instead.
             * New code should always read/write FinalScore.
             * @member
             * @type {number}
             */
            this["score"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ScheduleVersion instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ScheduleVersion}
     */
    static createFrom($$source = {}) {
        const $$createField33_0 = $$createType5;
        const $$createField34_0 = $$createType7;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("entries" in $$parsedSource) {
            $$parsedSource["entries"] = $$createField33_0($$parsedSource["entries"]);
        }
        if ("details" in $$parsedSource) {
            $$parsedSource["details"] = $$createField34_0($$parsedSource["details"]);
        }
        return new ScheduleVersion(/** @type {Partial<ScheduleVersion>} */($$parsedSource));
    }
}

/**
 * ScheduleVersionEntry stores a single course entry within a historical
 * schedule version. Fields mirror the main ScheduleEntry but are stored
 * independently so historical versions remain valid even if current
 * resource data (teachers, classrooms, etc.) is later modified or deleted.
 */
export class ScheduleVersionEntry {
    /**
     * Creates a new ScheduleVersionEntry instance.
     * @param {Partial<ScheduleVersionEntry>} [$$source = {}] - The source object to create the ScheduleVersionEntry.
     */
    constructor($$source = {}) {
        if (!("ID" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["ID"] = 0;
        }
        if (!("CreatedAt" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["CreatedAt"] = "0001-01-01T00:00:00.000Z";
        }
        if (!("UpdatedAt" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["UpdatedAt"] = "0001-01-01T00:00:00.000Z";
        }
        if (!("DeletedAt" in $$source)) {
            /**
             * @member
             * @type {gorm$0.DeletedAt}
             */
            this["DeletedAt"] = null;
        }
        if (!("versionId" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["versionId"] = 0;
        }
        if (/** @type {any} */(false)) {
            /**
             * optional: links back to the schedule_entry row at time of capture
             * @member
             * @type {number | null | undefined}
             */
            this["originalEntryId"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | null | undefined}
             */
            this["teachingTaskId"] = undefined;
        }
        if (!("courseId" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["courseId"] = 0;
        }
        if (!("teacherId" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["teacherId"] = 0;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | null | undefined}
             */
            this["classroomId"] = undefined;
        }
        if (!("dayOfWeek" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["dayOfWeek"] = 0;
        }
        if (!("startPeriod" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["startPeriod"] = 0;
        }
        if (!("span" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["span"] = 0;
        }
        if (!("weeks" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["weeks"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ScheduleVersionEntry instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ScheduleVersionEntry}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ScheduleVersionEntry(/** @type {Partial<ScheduleVersionEntry>} */($$parsedSource));
    }
}

/**
 * Semester represents an academic semester.
 * v0.5.5: 重构为结构化学期模型，删除 Name/IsActive/string StartDate。
 */
export class Semester {
    /**
     * Creates a new Semester instance.
     * @param {Partial<Semester>} [$$source = {}] - The source object to create the Semester.
     */
    constructor($$source = {}) {
        if (!("ID" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["ID"] = 0;
        }
        if (!("CreatedAt" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["CreatedAt"] = "0001-01-01T00:00:00.000Z";
        }
        if (!("UpdatedAt" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["UpdatedAt"] = "0001-01-01T00:00:00.000Z";
        }
        if (!("DeletedAt" in $$source)) {
            /**
             * @member
             * @type {gorm$0.DeletedAt}
             */
            this["DeletedAt"] = null;
        }
        if (!("academicYear" in $$source)) {
            /**
             * "2025-2026"
             * @member
             * @type {string}
             */
            this["academicYear"] = "";
        }
        if (!("term" in $$source)) {
            /**
             * FIRST, SECOND
             * @member
             * @type {string}
             */
            this["term"] = "";
        }
        if (!("startDate" in $$source)) {
            /**
             * 学期第一周周一
             * @member
             * @type {string}
             */
            this["startDate"] = "0001-01-01T00:00:00.000Z";
        }
        if (!("endDate" in $$source)) {
            /**
             * 学期最后一天
             * @member
             * @type {string}
             */
            this["endDate"] = "0001-01-01T00:00:00.000Z";
        }
        if (!("status" in $$source)) {
            /**
             * active, archived, planned
             * @member
             * @type {string}
             */
            this["status"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Semester instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Semester}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Semester(/** @type {Partial<Semester>} */($$parsedSource));
    }
}

/**
 * Teacher represents a teaching staff member.
 */
export class Teacher {
    /**
     * Creates a new Teacher instance.
     * @param {Partial<Teacher>} [$$source = {}] - The source object to create the Teacher.
     */
    constructor($$source = {}) {
        if (!("ID" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["ID"] = 0;
        }
        if (!("CreatedAt" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["CreatedAt"] = "0001-01-01T00:00:00.000Z";
        }
        if (!("UpdatedAt" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["UpdatedAt"] = "0001-01-01T00:00:00.000Z";
        }
        if (!("DeletedAt" in $$source)) {
            /**
             * @member
             * @type {gorm$0.DeletedAt}
             */
            this["DeletedAt"] = null;
        }
        if (!("code" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["code"] = "";
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("dept" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["dept"] = "";
        }
        if (!("status" in $$source)) {
            /**
             * active, inactive
             * @member
             * @type {string}
             */
            this["status"] = "";
        }
        if (!("preferNoEarly" in $$source)) {
            /**
             * Soft constraint preferences
             * 避免早课（1-2节）
             * @member
             * @type {boolean}
             */
            this["preferNoEarly"] = false;
        }
        if (!("preferNoLate" in $$source)) {
            /**
             * 避免晚课（7-8节及晚上）
             * @member
             * @type {boolean}
             */
            this["preferNoLate"] = false;
        }
        if (!("maxDaysPerWeek" in $$source)) {
            /**
             * 每周最多到校天数
             * @member
             * @type {number}
             */
            this["maxDaysPerWeek"] = 0;
        }
        if (!("preferLowFloor" in $$source)) {
            /**
             * 优先低楼层
             * @member
             * @type {boolean}
             */
            this["preferLowFloor"] = false;
        }
        if (!("unavailableSlots" in $$source)) {
            /**
             * Per-teacher unavailable time slots (JSON array).
             * Each element: {"dayOfWeek":0-6, "startPeriod":0-10, "span":2-4}
             * @member
             * @type {string}
             */
            this["unavailableSlots"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Teacher instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Teacher}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Teacher(/** @type {Partial<Teacher>} */($$parsedSource));
    }
}

/**
 * TeachingTask represents a teaching assignment: one course taught by one teacher
 * for one or more class groups in a specific semester.
 * This replaces the implicit department-based matching with explicit relationships.
 */
export class TeachingTask {
    /**
     * Creates a new TeachingTask instance.
     * @param {Partial<TeachingTask>} [$$source = {}] - The source object to create the TeachingTask.
     */
    constructor($$source = {}) {
        if (!("ID" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["ID"] = 0;
        }
        if (!("CreatedAt" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["CreatedAt"] = "0001-01-01T00:00:00.000Z";
        }
        if (!("UpdatedAt" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["UpdatedAt"] = "0001-01-01T00:00:00.000Z";
        }
        if (!("DeletedAt" in $$source)) {
            /**
             * @member
             * @type {gorm$0.DeletedAt}
             */
            this["DeletedAt"] = null;
        }
        if (!("courseId" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["courseId"] = 0;
        }
        if (!("teacherId" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["teacherId"] = 0;
        }
        if (!("semesterId" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["semesterId"] = 0;
        }
        if (!("status" in $$source)) {
            /**
             * active, inactive
             * @member
             * @type {string}
             */
            this["status"] = "";
        }
        if (!("totalHours" in $$source)) {
            /**
             * Time parameters for scheduling
             * 总学时（必填）
             * @member
             * @type {number}
             */
            this["totalHours"] = 0;
        }
        if (!("startWeek" in $$source)) {
            /**
             * 起始周（默认1）
             * @member
             * @type {number}
             */
            this["startWeek"] = 0;
        }
        if (!("endWeek" in $$source)) {
            /**
             * 结束周（默认16）
             * @member
             * @type {number}
             */
            this["endWeek"] = 0;
        }
        if (!("maxHoursPerWeek" in $$source)) {
            /**
             * 周最大学时（0=不限）
             * @member
             * @type {number}
             */
            this["maxHoursPerWeek"] = 0;
        }
        if (!("preferredSpan" in $$source)) {
            /**
             * v0.5.1: single-session span preference (HBUT). 0 = 不指定, 1/2/3 = 强制单次连排节次.
             * When >0 and legal under IsSpanLegal for at least one start, overrides the
             * hour-derived default from resolveSessionPlan. Illegal values fall back silently.
             * @member
             * @type {number}
             */
            this["preferredSpan"] = 0;
        }
        if (!("requiredRoomType" in $$source)) {
            /**
             * +v0.5.3: 显式指定教室类型。空=由 Course.Category 推导。
             * @member
             * @type {string}
             */
            this["requiredRoomType"] = "";
        }
        if (!("requiredEquipment" in $$source)) {
            /**
             * +v0.5.3: 显式指定所需设备 JSON array，如 ["projector"]
             * @member
             * @type {string}
             */
            this["requiredEquipment"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * Associations
             * @member
             * @type {Course | undefined}
             */
            this["course"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {Teacher | undefined}
             */
            this["teacher"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {Semester | undefined}
             */
            this["semester"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {TeachingTaskClass[] | undefined}
             */
            this["classes"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TeachingTask instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {TeachingTask}
     */
    static createFrom($$source = {}) {
        const $$createField15_0 = $$createType8;
        const $$createField16_0 = $$createType9;
        const $$createField17_0 = $$createType10;
        const $$createField18_0 = $$createType12;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("course" in $$parsedSource) {
            $$parsedSource["course"] = $$createField15_0($$parsedSource["course"]);
        }
        if ("teacher" in $$parsedSource) {
            $$parsedSource["teacher"] = $$createField16_0($$parsedSource["teacher"]);
        }
        if ("semester" in $$parsedSource) {
            $$parsedSource["semester"] = $$createField17_0($$parsedSource["semester"]);
        }
        if ("classes" in $$parsedSource) {
            $$parsedSource["classes"] = $$createField18_0($$parsedSource["classes"]);
        }
        return new TeachingTask(/** @type {Partial<TeachingTask>} */($$parsedSource));
    }
}

/**
 * TeachingTaskClass links a TeachingTask to its enrolled ClassGroups.
 * A composite unique index prevents duplicate bindings.
 */
export class TeachingTaskClass {
    /**
     * Creates a new TeachingTaskClass instance.
     * @param {Partial<TeachingTaskClass>} [$$source = {}] - The source object to create the TeachingTaskClass.
     */
    constructor($$source = {}) {
        if (!("ID" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["ID"] = 0;
        }
        if (!("CreatedAt" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["CreatedAt"] = "0001-01-01T00:00:00.000Z";
        }
        if (!("UpdatedAt" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["UpdatedAt"] = "0001-01-01T00:00:00.000Z";
        }
        if (!("DeletedAt" in $$source)) {
            /**
             * @member
             * @type {gorm$0.DeletedAt}
             */
            this["DeletedAt"] = null;
        }
        if (!("teachingTaskId" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["teachingTaskId"] = 0;
        }
        if (!("classGroupId" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["classGroupId"] = 0;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {ClassGroup | undefined}
             */
            this["classGroup"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TeachingTaskClass instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {TeachingTaskClass}
     */
    static createFrom($$source = {}) {
        const $$createField6_0 = $$createType13;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("classGroup" in $$parsedSource) {
            $$parsedSource["classGroup"] = $$createField6_0($$parsedSource["classGroup"]);
        }
        return new TeachingTaskClass(/** @type {Partial<TeachingTaskClass>} */($$parsedSource));
    }
}

/**
 * TimeAssignment 是 v0.5.5 双模式排课的 **时间事实实体**。
 * 一条 TA 行 = 一次周课(一个 TeachingTask 在某天某节起某跨度的排课),
 * 与"教室"完全解耦(INV-T2 / spec §2.2)。
 * 
 * - FULL_SCHEDULING 模式:每条 TA 对应 exactly one ScheduleEntry(教室分配)。
 * - TIME_ONLY_SCHEDULING 模式:只写 TA 不写 ScheduleEntry(INV-E1)。
 * 
 * 这个模型在 v0.5.5 PR-03 阶段被引入但**尚未被生产写路径使用** ——
 * PR-09 才做数据模型切换。此时先注册 AutoMigrate 让 schema 落地,
 * 为后续 refactor 铺路。
 */
export class TimeAssignment {
    /**
     * Creates a new TimeAssignment instance.
     * @param {Partial<TimeAssignment>} [$$source = {}] - The source object to create the TimeAssignment.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["id"] = 0;
        }
        if (!("semesterId" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["semesterId"] = 0;
        }
        if (!("scheduleVersionId" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["scheduleVersionId"] = 0;
        }
        if (!("teachingTaskId" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["teachingTaskId"] = 0;
        }
        if (!("dayOfWeek" in $$source)) {
            /**
             * @member
             * @type {DayOfWeek}
             */
            this["dayOfWeek"] = DayOfWeek.$zero;
        }
        if (!("startPeriod" in $$source)) {
            /**
             * @member
             * @type {Period}
             */
            this["startPeriod"] = 0;
        }
        if (!("span" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["span"] = 0;
        }
        if (!("createdAt" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["createdAt"] = "0001-01-01T00:00:00.000Z";
        }
        if (!("updatedAt" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["updatedAt"] = "0001-01-01T00:00:00.000Z";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | null | undefined}
             */
            this["deletedAt"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TimeAssignment instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {TimeAssignment}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new TimeAssignment(/** @type {Partial<TimeAssignment>} */($$parsedSource));
    }
}

/**
 * VersionDetail stores per-teacher score contributions for a schedule version.
 * This is the unified replacement for SnapshotDetail, linked to ScheduleVersion
 * instead of ScheduleSnapshot.
 */
export class VersionDetail {
    /**
     * Creates a new VersionDetail instance.
     * @param {Partial<VersionDetail>} [$$source = {}] - The source object to create the VersionDetail.
     */
    constructor($$source = {}) {
        if (!("ID" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["ID"] = 0;
        }
        if (!("CreatedAt" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["CreatedAt"] = "0001-01-01T00:00:00.000Z";
        }
        if (!("UpdatedAt" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["UpdatedAt"] = "0001-01-01T00:00:00.000Z";
        }
        if (!("DeletedAt" in $$source)) {
            /**
             * @member
             * @type {gorm$0.DeletedAt}
             */
            this["DeletedAt"] = null;
        }
        if (!("versionId" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["versionId"] = 0;
        }
        if (!("entityType" in $$source)) {
            /**
             * "teacher" | "course"
             * @member
             * @type {string}
             */
            this["entityType"] = "";
        }
        if (!("entityCode" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["entityCode"] = "";
        }
        if (!("entityName" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["entityName"] = "";
        }
        if (!("earlyPenalty" in $$source)) {
            /**
             * Per-constraint breakdown
             * @member
             * @type {number}
             */
            this["earlyPenalty"] = 0;
        }
        if (!("latePenalty" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["latePenalty"] = 0;
        }
        if (!("daysActual" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["daysActual"] = 0;
        }
        if (!("daysTarget" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["daysTarget"] = 0;
        }
        if (!("avgFloor" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["avgFloor"] = 0;
        }
        if (!("capacityWarning" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["capacityWarning"] = false;
        }
        if (!("entryCount" in $$source)) {
            /**
             * Schedule summary
             * @member
             * @type {number}
             */
            this["entryCount"] = 0;
        }
        if (!("daysCount" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["daysCount"] = 0;
        }
        if (!("summary" in $$source)) {
            /**
             * e.g. "周一1-2节,周三3-4节"
             * @member
             * @type {string}
             */
            this["summary"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new VersionDetail instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {VersionDetail}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new VersionDetail(/** @type {Partial<VersionDetail>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = Building.createFrom;
const $$createType1 = TimeAssignment.createFrom;
const $$createType2 = $Create.Nullable($$createType1);
const $$createType3 = Classroom.createFrom;
const $$createType4 = ScheduleVersionEntry.createFrom;
const $$createType5 = $Create.Array($$createType4);
const $$createType6 = VersionDetail.createFrom;
const $$createType7 = $Create.Array($$createType6);
const $$createType8 = Course.createFrom;
const $$createType9 = Teacher.createFrom;
const $$createType10 = Semester.createFrom;
const $$createType11 = TeachingTaskClass.createFrom;
const $$createType12 = $Create.Array($$createType11);
const $$createType13 = ClassGroup.createFrom;
