// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as gorm$0 from "../../../gorm.io/gorm/models.js";

/**
 * ClassGroup represents a student class/group (e.g., 计算机2301).
 */
export class ClassGroup {
    /**
     * Creates a new ClassGroup instance.
     * @param {Partial<ClassGroup>} [$$source = {}] - The source object to create the ClassGroup.
     */
    constructor($$source = {}) {
        if (!("ID" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["ID"] = 0;
        }
        if (!("CreatedAt" in $$source)) {
            /**
             * @member
             * @type {Date}
             */
            this["CreatedAt"] = new Date("0001-01-01T00:00:00.000Z");
        }
        if (!("UpdatedAt" in $$source)) {
            /**
             * @member
             * @type {Date}
             */
            this["UpdatedAt"] = new Date("0001-01-01T00:00:00.000Z");
        }
        if (!("DeletedAt" in $$source)) {
            /**
             * @member
             * @type {gorm$0.DeletedAt}
             */
            this["DeletedAt"] = null;
        }
        if (!("code" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["code"] = "";
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("dept" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["dept"] = "";
        }
        if (!("grade" in $$source)) {
            /**
             * 入学年份, e.g. 2023
             * @member
             * @type {number}
             */
            this["grade"] = 0;
        }
        if (!("students" in $$source)) {
            /**
             * 学生人数
             * @member
             * @type {number}
             */
            this["students"] = 0;
        }
        if (!("status" in $$source)) {
            /**
             * active, inactive
             * @member
             * @type {string}
             */
            this["status"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ClassGroup instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ClassGroup}
     */
    static createFrom($$source = {}) {
        const $$createField1_0 = $Create.DateFromTime;
        const $$createField2_0 = $Create.DateFromTime;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("CreatedAt" in $$parsedSource) {
            $$parsedSource["CreatedAt"] = $$createField1_0($$parsedSource["CreatedAt"]);
        }
        if ("UpdatedAt" in $$parsedSource) {
            $$parsedSource["UpdatedAt"] = $$createField2_0($$parsedSource["UpdatedAt"]);
        }
        return new ClassGroup(/** @type {Partial<ClassGroup>} */($$parsedSource));
    }
}

/**
 * Classroom represents a physical room for teaching.
 */
export class Classroom {
    /**
     * Creates a new Classroom instance.
     * @param {Partial<Classroom>} [$$source = {}] - The source object to create the Classroom.
     */
    constructor($$source = {}) {
        if (!("ID" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["ID"] = 0;
        }
        if (!("CreatedAt" in $$source)) {
            /**
             * @member
             * @type {Date}
             */
            this["CreatedAt"] = new Date("0001-01-01T00:00:00.000Z");
        }
        if (!("UpdatedAt" in $$source)) {
            /**
             * @member
             * @type {Date}
             */
            this["UpdatedAt"] = new Date("0001-01-01T00:00:00.000Z");
        }
        if (!("DeletedAt" in $$source)) {
            /**
             * @member
             * @type {gorm$0.DeletedAt}
             */
            this["DeletedAt"] = null;
        }
        if (!("code" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["code"] = "";
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("building" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["building"] = "";
        }
        if (!("floor" in $$source)) {
            /**
             * 楼层号
             * @member
             * @type {number}
             */
            this["floor"] = 0;
        }
        if (!("capacity" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["capacity"] = 0;
        }
        if (!("type" in $$source)) {
            /**
             * 普通教室, 实验室, 体育馆, etc.
             * @member
             * @type {string}
             */
            this["type"] = "";
        }
        if (!("status" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["status"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Classroom instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Classroom}
     */
    static createFrom($$source = {}) {
        const $$createField1_0 = $Create.DateFromTime;
        const $$createField2_0 = $Create.DateFromTime;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("CreatedAt" in $$parsedSource) {
            $$parsedSource["CreatedAt"] = $$createField1_0($$parsedSource["CreatedAt"]);
        }
        if ("UpdatedAt" in $$parsedSource) {
            $$parsedSource["UpdatedAt"] = $$createField2_0($$parsedSource["UpdatedAt"]);
        }
        return new Classroom(/** @type {Partial<Classroom>} */($$parsedSource));
    }
}

/**
 * Course represents a course in the curriculum.
 */
export class Course {
    /**
     * Creates a new Course instance.
     * @param {Partial<Course>} [$$source = {}] - The source object to create the Course.
     */
    constructor($$source = {}) {
        if (!("ID" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["ID"] = 0;
        }
        if (!("CreatedAt" in $$source)) {
            /**
             * @member
             * @type {Date}
             */
            this["CreatedAt"] = new Date("0001-01-01T00:00:00.000Z");
        }
        if (!("UpdatedAt" in $$source)) {
            /**
             * @member
             * @type {Date}
             */
            this["UpdatedAt"] = new Date("0001-01-01T00:00:00.000Z");
        }
        if (!("DeletedAt" in $$source)) {
            /**
             * @member
             * @type {gorm$0.DeletedAt}
             */
            this["DeletedAt"] = null;
        }
        if (!("code" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["code"] = "";
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("dept" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["dept"] = "";
        }
        if (!("credit" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["credit"] = 0;
        }
        if (!("type" in $$source)) {
            /**
             * 专业必修, 全校选修, etc.
             * @member
             * @type {string}
             */
            this["type"] = "";
        }
        if (!("hours" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["hours"] = 0;
        }
        if (!("status" in $$source)) {
            /**
             * active, inactive
             * @member
             * @type {string}
             */
            this["status"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Course instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Course}
     */
    static createFrom($$source = {}) {
        const $$createField1_0 = $Create.DateFromTime;
        const $$createField2_0 = $Create.DateFromTime;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("CreatedAt" in $$parsedSource) {
            $$parsedSource["CreatedAt"] = $$createField1_0($$parsedSource["CreatedAt"]);
        }
        if ("UpdatedAt" in $$parsedSource) {
            $$parsedSource["UpdatedAt"] = $$createField2_0($$parsedSource["UpdatedAt"]);
        }
        return new Course(/** @type {Partial<Course>} */($$parsedSource));
    }
}

/**
 * DayOfWeek represents a day in the teaching week (0 = Monday, 6 = Sunday).
 * This is the canonical internal representation throughout the system.
 * Display conversion (0→"周一", etc.) is handled by the frontend DAY_NAMES mapping.
 * @readonly
 * @enum {number}
 */
export const DayOfWeek = {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero: 0,

    Mon: 0,
    Tue: 1,
    Wed: 2,
    Thu: 3,
    Fri: 4,
    Sat: 5,
    Sun: 6,
};

/**
 * Department represents a college/faculty (e.g., 计算机学院, 材料科学与工程学院).
 */
export class Department {
    /**
     * Creates a new Department instance.
     * @param {Partial<Department>} [$$source = {}] - The source object to create the Department.
     */
    constructor($$source = {}) {
        if (!("ID" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["ID"] = 0;
        }
        if (!("CreatedAt" in $$source)) {
            /**
             * @member
             * @type {Date}
             */
            this["CreatedAt"] = new Date("0001-01-01T00:00:00.000Z");
        }
        if (!("UpdatedAt" in $$source)) {
            /**
             * @member
             * @type {Date}
             */
            this["UpdatedAt"] = new Date("0001-01-01T00:00:00.000Z");
        }
        if (!("DeletedAt" in $$source)) {
            /**
             * @member
             * @type {gorm$0.DeletedAt}
             */
            this["DeletedAt"] = null;
        }
        if (!("code" in $$source)) {
            /**
             * 院系代码，如 "cs"
             * @member
             * @type {string}
             */
            this["code"] = "";
        }
        if (!("name" in $$source)) {
            /**
             * 院系名称，如 "计算机学院"
             * @member
             * @type {string}
             */
            this["name"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Department instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Department}
     */
    static createFrom($$source = {}) {
        const $$createField1_0 = $Create.DateFromTime;
        const $$createField2_0 = $Create.DateFromTime;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("CreatedAt" in $$parsedSource) {
            $$parsedSource["CreatedAt"] = $$createField1_0($$parsedSource["CreatedAt"]);
        }
        if ("UpdatedAt" in $$parsedSource) {
            $$parsedSource["UpdatedAt"] = $$createField2_0($$parsedSource["UpdatedAt"]);
        }
        return new Department(/** @type {Partial<Department>} */($$parsedSource));
    }
}

/**
 * Period represents a teaching period slot (0-indexed internal, 1-indexed for display).
 * Period 0 = 第1节, Period 9 = 第10节, etc.
 * @typedef {number} Period
 */

/**
 * ScheduleEntry represents a single scheduled course slot.
 */
export class ScheduleEntry {
    /**
     * Creates a new ScheduleEntry instance.
     * @param {Partial<ScheduleEntry>} [$$source = {}] - The source object to create the ScheduleEntry.
     */
    constructor($$source = {}) {
        if (!("ID" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["ID"] = 0;
        }
        if (!("CreatedAt" in $$source)) {
            /**
             * @member
             * @type {Date}
             */
            this["CreatedAt"] = new Date("0001-01-01T00:00:00.000Z");
        }
        if (!("UpdatedAt" in $$source)) {
            /**
             * @member
             * @type {Date}
             */
            this["UpdatedAt"] = new Date("0001-01-01T00:00:00.000Z");
        }
        if (!("DeletedAt" in $$source)) {
            /**
             * @member
             * @type {gorm$0.DeletedAt}
             */
            this["DeletedAt"] = null;
        }
        if (!("courseId" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["courseId"] = 0;
        }
        if (!("teacherId" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["teacherId"] = 0;
        }
        if (!("classroomId" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["classroomId"] = 0;
        }
        if (!("classGroupId" in $$source)) {
            /**
             * legacy FK, kept for backward compatibility
             * @member
             * @type {number | null}
             */
            this["classGroupId"] = null;
        }
        if (!("teachingTaskId" in $$source)) {
            /**
             * FK to TeachingTask, enables combined classes
             * @member
             * @type {number | null}
             */
            this["teachingTaskId"] = null;
        }
        if (!("semester" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["semester"] = "";
        }
        if (!("dayOfWeek" in $$source)) {
            /**
             * 0=周一..6=周日
             * @member
             * @type {DayOfWeek}
             */
            this["dayOfWeek"] = DayOfWeek.$zero;
        }
        if (!("startPeriod" in $$source)) {
            /**
             * 0=第1节..10=第11节
             * @member
             * @type {Period}
             */
            this["startPeriod"] = 0;
        }
        if (!("span" in $$source)) {
            /**
             * consecutive periods
             * @member
             * @type {number}
             */
            this["span"] = 0;
        }
        if (!("weeks" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["weeks"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * Associations
             * @member
             * @type {Course | undefined}
             */
            this["course"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {Teacher | undefined}
             */
            this["teacher"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {Classroom | undefined}
             */
            this["classroom"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {ClassGroup | null | undefined}
             */
            this["classGroup"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {TeachingTask | null | undefined}
             */
            this["teachingTask"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ScheduleEntry instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ScheduleEntry}
     */
    static createFrom($$source = {}) {
        const $$createField1_0 = $Create.DateFromTime;
        const $$createField2_0 = $Create.DateFromTime;
        const $$createField14_0 = $$createType0;
        const $$createField15_0 = $$createType1;
        const $$createField16_0 = $$createType2;
        const $$createField17_0 = $$createType4;
        const $$createField18_0 = $$createType6;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("CreatedAt" in $$parsedSource) {
            $$parsedSource["CreatedAt"] = $$createField1_0($$parsedSource["CreatedAt"]);
        }
        if ("UpdatedAt" in $$parsedSource) {
            $$parsedSource["UpdatedAt"] = $$createField2_0($$parsedSource["UpdatedAt"]);
        }
        if ("course" in $$parsedSource) {
            $$parsedSource["course"] = $$createField14_0($$parsedSource["course"]);
        }
        if ("teacher" in $$parsedSource) {
            $$parsedSource["teacher"] = $$createField15_0($$parsedSource["teacher"]);
        }
        if ("classroom" in $$parsedSource) {
            $$parsedSource["classroom"] = $$createField16_0($$parsedSource["classroom"]);
        }
        if ("classGroup" in $$parsedSource) {
            $$parsedSource["classGroup"] = $$createField17_0($$parsedSource["classGroup"]);
        }
        if ("teachingTask" in $$parsedSource) {
            $$parsedSource["teachingTask"] = $$createField18_0($$parsedSource["teachingTask"]);
        }
        return new ScheduleEntry(/** @type {Partial<ScheduleEntry>} */($$parsedSource));
    }
}

/**
 * ScheduleSnapshot captures a point-in-time evaluation of a schedule.
 * Generated automatically after scheduling or manually by user request.
 */
export class ScheduleSnapshot {
    /**
     * Creates a new ScheduleSnapshot instance.
     * @param {Partial<ScheduleSnapshot>} [$$source = {}] - The source object to create the ScheduleSnapshot.
     */
    constructor($$source = {}) {
        if (!("ID" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["ID"] = 0;
        }
        if (!("CreatedAt" in $$source)) {
            /**
             * @member
             * @type {Date}
             */
            this["CreatedAt"] = new Date("0001-01-01T00:00:00.000Z");
        }
        if (!("UpdatedAt" in $$source)) {
            /**
             * @member
             * @type {Date}
             */
            this["UpdatedAt"] = new Date("0001-01-01T00:00:00.000Z");
        }
        if (!("DeletedAt" in $$source)) {
            /**
             * @member
             * @type {gorm$0.DeletedAt}
             */
            this["DeletedAt"] = null;
        }
        if (!("name" in $$source)) {
            /**
             * 快照名称，创建时自动生成
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("semester" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["semester"] = "";
        }
        if (!("dept" in $$source)) {
            /**
             * 院系范围，空=全校
             * @member
             * @type {string}
             */
            this["dept"] = "";
        }
        if (!("trigger" in $$source)) {
            /**
             * "auto" | "manual"
             * @member
             * @type {string}
             */
            this["trigger"] = "";
        }
        if (!("hardPassed" in $$source)) {
            /**
             * Hard constraint pass/fail
             * @member
             * @type {boolean}
             */
            this["hardPassed"] = false;
        }
        if (!("teacherConflicts" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["teacherConflicts"] = 0;
        }
        if (!("roomConflicts" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["roomConflicts"] = 0;
        }
        if (!("classConflicts" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["classConflicts"] = 0;
        }
        if (!("lockedViolations" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["lockedViolations"] = 0;
        }
        if (!("totalScore" in $$source)) {
            /**
             * Soft constraint scores (0-100 scale, weighted)
             * @member
             * @type {number}
             */
            this["totalScore"] = 0;
        }
        if (!("teacherPref" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["teacherPref"] = 0;
        }
        if (!("courseSpacing" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["courseSpacing"] = 0;
        }
        if (!("teacherDays" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["teacherDays"] = 0;
        }
        if (!("lowFloorPref" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["lowFloorPref"] = 0;
        }
        if (!("weekendAvoid" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["weekendAvoid"] = 0;
        }
        if (!("pePeriodPref" in $$source)) {
            /**
             * 体育课时段偏好
             * @member
             * @type {number}
             */
            this["pePeriodPref"] = 0;
        }
        if (!("studentFatigue" in $$source)) {
            /**
             * 学生连续疲劳度
             * @member
             * @type {number}
             */
            this["studentFatigue"] = 0;
        }
        if (!("capacityWarn" in $$source)) {
            /**
             * 容量不足警告数
             * @member
             * @type {number}
             */
            this["capacityWarn"] = 0;
        }
        if (!("enabledConstraints" in $$source)) {
            /**
             * Scoring configuration stored at snapshot time for reproducible re-scoring
             * JSON array
             * @member
             * @type {string}
             */
            this["enabledConstraints"] = "";
        }
        if (!("scoreVersion" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["scoreVersion"] = 0;
        }
        if (!("totalEntries" in $$source)) {
            /**
             * Statistics
             * @member
             * @type {number}
             */
            this["totalEntries"] = 0;
        }
        if (!("solveTimeMs" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["solveTimeMs"] = 0;
        }
        if (!("solver" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["solver"] = "";
        }
        if (!("perCategoryMax" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["perCategoryMax"] = 0;
        }
        if (!("enabledCategoryCount" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["enabledCategoryCount"] = 0;
        }
        if (/** @type {any} */(false)) {
            /**
             * Linked details
             * @member
             * @type {SnapshotDetail[] | undefined}
             */
            this["details"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ScheduleSnapshot instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ScheduleSnapshot}
     */
    static createFrom($$source = {}) {
        const $$createField1_0 = $Create.DateFromTime;
        const $$createField2_0 = $Create.DateFromTime;
        const $$createField29_0 = $$createType8;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("CreatedAt" in $$parsedSource) {
            $$parsedSource["CreatedAt"] = $$createField1_0($$parsedSource["CreatedAt"]);
        }
        if ("UpdatedAt" in $$parsedSource) {
            $$parsedSource["UpdatedAt"] = $$createField2_0($$parsedSource["UpdatedAt"]);
        }
        if ("details" in $$parsedSource) {
            $$parsedSource["details"] = $$createField29_0($$parsedSource["details"]);
        }
        return new ScheduleSnapshot(/** @type {Partial<ScheduleSnapshot>} */($$parsedSource));
    }
}

/**
 * Semester represents an academic semester.
 */
export class Semester {
    /**
     * Creates a new Semester instance.
     * @param {Partial<Semester>} [$$source = {}] - The source object to create the Semester.
     */
    constructor($$source = {}) {
        if (!("ID" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["ID"] = 0;
        }
        if (!("CreatedAt" in $$source)) {
            /**
             * @member
             * @type {Date}
             */
            this["CreatedAt"] = new Date("0001-01-01T00:00:00.000Z");
        }
        if (!("UpdatedAt" in $$source)) {
            /**
             * @member
             * @type {Date}
             */
            this["UpdatedAt"] = new Date("0001-01-01T00:00:00.000Z");
        }
        if (!("DeletedAt" in $$source)) {
            /**
             * @member
             * @type {gorm$0.DeletedAt}
             */
            this["DeletedAt"] = null;
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("isActive" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["isActive"] = false;
        }
        if (!("startDate" in $$source)) {
            /**
             * e.g. "2025-09-01", determines day-to-date mapping
             * @member
             * @type {string}
             */
            this["startDate"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Semester instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Semester}
     */
    static createFrom($$source = {}) {
        const $$createField1_0 = $Create.DateFromTime;
        const $$createField2_0 = $Create.DateFromTime;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("CreatedAt" in $$parsedSource) {
            $$parsedSource["CreatedAt"] = $$createField1_0($$parsedSource["CreatedAt"]);
        }
        if ("UpdatedAt" in $$parsedSource) {
            $$parsedSource["UpdatedAt"] = $$createField2_0($$parsedSource["UpdatedAt"]);
        }
        return new Semester(/** @type {Partial<Semester>} */($$parsedSource));
    }
}

/**
 * SnapshotDetail stores per-teacher/course score contributions for the report.
 */
export class SnapshotDetail {
    /**
     * Creates a new SnapshotDetail instance.
     * @param {Partial<SnapshotDetail>} [$$source = {}] - The source object to create the SnapshotDetail.
     */
    constructor($$source = {}) {
        if (!("ID" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["ID"] = 0;
        }
        if (!("CreatedAt" in $$source)) {
            /**
             * @member
             * @type {Date}
             */
            this["CreatedAt"] = new Date("0001-01-01T00:00:00.000Z");
        }
        if (!("UpdatedAt" in $$source)) {
            /**
             * @member
             * @type {Date}
             */
            this["UpdatedAt"] = new Date("0001-01-01T00:00:00.000Z");
        }
        if (!("DeletedAt" in $$source)) {
            /**
             * @member
             * @type {gorm$0.DeletedAt}
             */
            this["DeletedAt"] = null;
        }
        if (!("snapshotId" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["snapshotId"] = 0;
        }
        if (!("entityType" in $$source)) {
            /**
             * "teacher" | "course"
             * @member
             * @type {string}
             */
            this["entityType"] = "";
        }
        if (!("entityCode" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["entityCode"] = "";
        }
        if (!("entityName" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["entityName"] = "";
        }
        if (!("earlyPenalty" in $$source)) {
            /**
             * Per-constraint breakdown
             * @member
             * @type {number}
             */
            this["earlyPenalty"] = 0;
        }
        if (!("latePenalty" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["latePenalty"] = 0;
        }
        if (!("daysActual" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["daysActual"] = 0;
        }
        if (!("daysTarget" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["daysTarget"] = 0;
        }
        if (!("avgFloor" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["avgFloor"] = 0;
        }
        if (!("capacityWarning" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["capacityWarning"] = false;
        }
        if (!("entryCount" in $$source)) {
            /**
             * Schedule summary
             * @member
             * @type {number}
             */
            this["entryCount"] = 0;
        }
        if (!("daysCount" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["daysCount"] = 0;
        }
        if (!("summary" in $$source)) {
            /**
             * e.g. "周一1-2节,周三3-4节"
             * @member
             * @type {string}
             */
            this["summary"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SnapshotDetail instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {SnapshotDetail}
     */
    static createFrom($$source = {}) {
        const $$createField1_0 = $Create.DateFromTime;
        const $$createField2_0 = $Create.DateFromTime;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("CreatedAt" in $$parsedSource) {
            $$parsedSource["CreatedAt"] = $$createField1_0($$parsedSource["CreatedAt"]);
        }
        if ("UpdatedAt" in $$parsedSource) {
            $$parsedSource["UpdatedAt"] = $$createField2_0($$parsedSource["UpdatedAt"]);
        }
        return new SnapshotDetail(/** @type {Partial<SnapshotDetail>} */($$parsedSource));
    }
}

/**
 * Teacher represents a teaching staff member.
 */
export class Teacher {
    /**
     * Creates a new Teacher instance.
     * @param {Partial<Teacher>} [$$source = {}] - The source object to create the Teacher.
     */
    constructor($$source = {}) {
        if (!("ID" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["ID"] = 0;
        }
        if (!("CreatedAt" in $$source)) {
            /**
             * @member
             * @type {Date}
             */
            this["CreatedAt"] = new Date("0001-01-01T00:00:00.000Z");
        }
        if (!("UpdatedAt" in $$source)) {
            /**
             * @member
             * @type {Date}
             */
            this["UpdatedAt"] = new Date("0001-01-01T00:00:00.000Z");
        }
        if (!("DeletedAt" in $$source)) {
            /**
             * @member
             * @type {gorm$0.DeletedAt}
             */
            this["DeletedAt"] = null;
        }
        if (!("code" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["code"] = "";
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("dept" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["dept"] = "";
        }
        if (!("status" in $$source)) {
            /**
             * active, inactive
             * @member
             * @type {string}
             */
            this["status"] = "";
        }
        if (!("preferNoEarly" in $$source)) {
            /**
             * Soft constraint preferences
             * 避免早课（1-2节）
             * @member
             * @type {boolean}
             */
            this["preferNoEarly"] = false;
        }
        if (!("preferNoLate" in $$source)) {
            /**
             * 避免晚课（7-8节及晚上）
             * @member
             * @type {boolean}
             */
            this["preferNoLate"] = false;
        }
        if (!("maxDaysPerWeek" in $$source)) {
            /**
             * 每周最多到校天数
             * @member
             * @type {number}
             */
            this["maxDaysPerWeek"] = 0;
        }
        if (!("preferLowFloor" in $$source)) {
            /**
             * 优先低楼层
             * @member
             * @type {boolean}
             */
            this["preferLowFloor"] = false;
        }
        if (!("unavailableSlots" in $$source)) {
            /**
             * Per-teacher unavailable time slots (JSON array).
             * Each element: {"dayOfWeek":0-6, "startPeriod":0-10, "span":2-4}
             * @member
             * @type {string}
             */
            this["unavailableSlots"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Teacher instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Teacher}
     */
    static createFrom($$source = {}) {
        const $$createField1_0 = $Create.DateFromTime;
        const $$createField2_0 = $Create.DateFromTime;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("CreatedAt" in $$parsedSource) {
            $$parsedSource["CreatedAt"] = $$createField1_0($$parsedSource["CreatedAt"]);
        }
        if ("UpdatedAt" in $$parsedSource) {
            $$parsedSource["UpdatedAt"] = $$createField2_0($$parsedSource["UpdatedAt"]);
        }
        return new Teacher(/** @type {Partial<Teacher>} */($$parsedSource));
    }
}

/**
 * TeachingTask represents a teaching assignment: one course taught by one teacher
 * for one or more class groups in a specific semester.
 * This replaces the implicit department-based matching with explicit relationships.
 */
export class TeachingTask {
    /**
     * Creates a new TeachingTask instance.
     * @param {Partial<TeachingTask>} [$$source = {}] - The source object to create the TeachingTask.
     */
    constructor($$source = {}) {
        if (!("ID" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["ID"] = 0;
        }
        if (!("CreatedAt" in $$source)) {
            /**
             * @member
             * @type {Date}
             */
            this["CreatedAt"] = new Date("0001-01-01T00:00:00.000Z");
        }
        if (!("UpdatedAt" in $$source)) {
            /**
             * @member
             * @type {Date}
             */
            this["UpdatedAt"] = new Date("0001-01-01T00:00:00.000Z");
        }
        if (!("DeletedAt" in $$source)) {
            /**
             * @member
             * @type {gorm$0.DeletedAt}
             */
            this["DeletedAt"] = null;
        }
        if (!("courseId" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["courseId"] = 0;
        }
        if (!("teacherId" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["teacherId"] = 0;
        }
        if (!("semesterId" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["semesterId"] = 0;
        }
        if (!("status" in $$source)) {
            /**
             * active, inactive
             * @member
             * @type {string}
             */
            this["status"] = "";
        }
        if (!("totalHours" in $$source)) {
            /**
             * Time parameters for scheduling
             * 总学时（必填）
             * @member
             * @type {number}
             */
            this["totalHours"] = 0;
        }
        if (!("startWeek" in $$source)) {
            /**
             * 起始周（默认1）
             * @member
             * @type {number}
             */
            this["startWeek"] = 0;
        }
        if (!("endWeek" in $$source)) {
            /**
             * 结束周（默认16）
             * @member
             * @type {number}
             */
            this["endWeek"] = 0;
        }
        if (!("maxHoursPerWeek" in $$source)) {
            /**
             * 周最大学时（0=不限）
             * @member
             * @type {number}
             */
            this["maxHoursPerWeek"] = 0;
        }
        if (/** @type {any} */(false)) {
            /**
             * Associations
             * @member
             * @type {Course | undefined}
             */
            this["course"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {Teacher | undefined}
             */
            this["teacher"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {Semester | undefined}
             */
            this["semester"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {TeachingTaskClass[] | undefined}
             */
            this["classes"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TeachingTask instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {TeachingTask}
     */
    static createFrom($$source = {}) {
        const $$createField1_0 = $Create.DateFromTime;
        const $$createField2_0 = $Create.DateFromTime;
        const $$createField12_0 = $$createType0;
        const $$createField13_0 = $$createType1;
        const $$createField14_0 = $$createType9;
        const $$createField15_0 = $$createType11;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("CreatedAt" in $$parsedSource) {
            $$parsedSource["CreatedAt"] = $$createField1_0($$parsedSource["CreatedAt"]);
        }
        if ("UpdatedAt" in $$parsedSource) {
            $$parsedSource["UpdatedAt"] = $$createField2_0($$parsedSource["UpdatedAt"]);
        }
        if ("course" in $$parsedSource) {
            $$parsedSource["course"] = $$createField12_0($$parsedSource["course"]);
        }
        if ("teacher" in $$parsedSource) {
            $$parsedSource["teacher"] = $$createField13_0($$parsedSource["teacher"]);
        }
        if ("semester" in $$parsedSource) {
            $$parsedSource["semester"] = $$createField14_0($$parsedSource["semester"]);
        }
        if ("classes" in $$parsedSource) {
            $$parsedSource["classes"] = $$createField15_0($$parsedSource["classes"]);
        }
        return new TeachingTask(/** @type {Partial<TeachingTask>} */($$parsedSource));
    }
}

/**
 * TeachingTaskClass links a TeachingTask to its enrolled ClassGroups.
 * A composite unique index prevents duplicate bindings.
 */
export class TeachingTaskClass {
    /**
     * Creates a new TeachingTaskClass instance.
     * @param {Partial<TeachingTaskClass>} [$$source = {}] - The source object to create the TeachingTaskClass.
     */
    constructor($$source = {}) {
        if (!("ID" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["ID"] = 0;
        }
        if (!("CreatedAt" in $$source)) {
            /**
             * @member
             * @type {Date}
             */
            this["CreatedAt"] = new Date("0001-01-01T00:00:00.000Z");
        }
        if (!("UpdatedAt" in $$source)) {
            /**
             * @member
             * @type {Date}
             */
            this["UpdatedAt"] = new Date("0001-01-01T00:00:00.000Z");
        }
        if (!("DeletedAt" in $$source)) {
            /**
             * @member
             * @type {gorm$0.DeletedAt}
             */
            this["DeletedAt"] = null;
        }
        if (!("teachingTaskId" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["teachingTaskId"] = 0;
        }
        if (!("classGroupId" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["classGroupId"] = 0;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {ClassGroup | undefined}
             */
            this["classGroup"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TeachingTaskClass instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {TeachingTaskClass}
     */
    static createFrom($$source = {}) {
        const $$createField1_0 = $Create.DateFromTime;
        const $$createField2_0 = $Create.DateFromTime;
        const $$createField6_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("CreatedAt" in $$parsedSource) {
            $$parsedSource["CreatedAt"] = $$createField1_0($$parsedSource["CreatedAt"]);
        }
        if ("UpdatedAt" in $$parsedSource) {
            $$parsedSource["UpdatedAt"] = $$createField2_0($$parsedSource["UpdatedAt"]);
        }
        if ("classGroup" in $$parsedSource) {
            $$parsedSource["classGroup"] = $$createField6_0($$parsedSource["classGroup"]);
        }
        return new TeachingTaskClass(/** @type {Partial<TeachingTaskClass>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = Course.createFrom;
const $$createType1 = Teacher.createFrom;
const $$createType2 = Classroom.createFrom;
const $$createType3 = ClassGroup.createFrom;
const $$createType4 = $Create.Nullable($$createType3);
const $$createType5 = TeachingTask.createFrom;
const $$createType6 = $Create.Nullable($$createType5);
const $$createType7 = SnapshotDetail.createFrom;
const $$createType8 = $Create.Array($$createType7);
const $$createType9 = Semester.createFrom;
const $$createType10 = TeachingTaskClass.createFrom;
const $$createType11 = $Create.Array($$createType10);
