// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as gorm$0 from "../../../gorm.io/gorm/models.js";

/**
 * Building represents a physical building on campus (e.g., "1 教", "5 教 A 区", "体育馆").
 * 
 * Core Domain: 通用建筑抽象，不含任何学校特定规则。
 *   - Code 由学校自定义，仅作唯一标识（如 "1"、"5A"、"6A"、"GYM"）。
 *   - Name 作为 UI 展示名（如 "1 教"、"5 教 A 区"、"体育馆"）。
 *   - Category 描述楼栋整体功能定位，但不硬约束该楼内的教室类型（教学楼里
 *     也可以有机房；实验楼里也可以有多媒体教室 —— 由 seed / 用户配置决定）。
 * 
 * 编号解析规则（"6教=实验楼" / "分 A/B 区" 等）不属于 Core，位于
 * backend/services/parsers/<school>/ adapter 层。
 */
export interface Building {
    "ID": number;
    "CreatedAt": string;
    "UpdatedAt": string;
    "DeletedAt": gorm$0.DeletedAt;
    "code": string;
    "name": string;
    "category": string;
    "status": string;
}

/**
 * ClassGroup represents a student class/group (e.g., 计算机2301).
 */
export interface ClassGroup {
    "ID": number;
    "CreatedAt": string;
    "UpdatedAt": string;
    "DeletedAt": gorm$0.DeletedAt;
    "code": string;
    "name": string;
    "dept": string;

    /**
     * 入学年份, e.g. 2023
     */
    "grade": number;

    /**
     * 学生人数
     */
    "students": number;

    /**
     * active, inactive
     */
    "status": string;
}

/**
 * Classroom represents a physical room for teaching.
 * 
 * v0.5.5 Stage B: 通用资源领域重构。
 *   - Building string → BuildingID FK + Building Association（关联 Building 表）
 *   - Type → RoomType（英文枚举，见 room_types.go）
 *   - 新增 Number 字段（教室号，不含楼栋前缀，如 "302" / "001" / "422"）
 *   - Code 字段仅是"唯一标识字符串"，无内在结构约束；编号解析规则在 adapter 层
 */
export interface Classroom {
    "ID": number;
    "CreatedAt": string;
    "UpdatedAt": string;
    "DeletedAt": gorm$0.DeletedAt;
    "code": string;
    "name": string;
    "buildingId": number;
    "floor": number;
    "number": string;
    "capacity": number;
    "roomType": string;
    "status": string;

    /**
     * +v0.5.3: 设备列表 JSON array，如 ["projector","smartboard","aircon"]
     */
    "equipment": string;

    /**
     * Association
     */
    "building"?: Building;
}

/**
 * Course represents a course in the curriculum.
 */
export interface Course {
    "ID": number;
    "CreatedAt": string;
    "UpdatedAt": string;
    "DeletedAt": gorm$0.DeletedAt;
    "code": string;
    "name": string;
    "dept": string;
    "credit": number;

    /**
     * 专业必修, 全校选修, etc.
     */
    "type": string;
    "hours": number;

    /**
     * active, inactive
     */
    "status": string;

    /**
     * +v0.5.3: 课程类别，用于资源匹配。空值=由名称推断(兼容, Deprecated)。
     */
    "category": string;
}

/**
 * DayOfWeek represents a day in the teaching week (0 = Monday, 6 = Sunday).
 * This is the canonical internal representation throughout the system.
 * Display conversion (0→"周一", etc.) is handled by the frontend DAY_NAMES mapping.
 */
export enum DayOfWeek {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = 0,

    Mon = 0,
    Tue = 1,
    Wed = 2,
    Thu = 3,
    Fri = 4,
    Sat = 5,
    Sun = 6,
};

/**
 * Department represents a college/faculty (e.g., 计算机学院, 材料科学与工程学院).
 */
export interface Department {
    "ID": number;
    "CreatedAt": string;
    "UpdatedAt": string;
    "DeletedAt": gorm$0.DeletedAt;

    /**
     * 院系代码，如 "cs"
     */
    "code": string;

    /**
     * 院系名称，如 "计算机学院"
     */
    "name": string;
}

/**
 * Period represents a teaching period slot (0-indexed internal, 1-indexed for display).
 * Period 0 = 第1节, Period 9 = 第10节, etc.
 */
export type Period = number;

/**
 * ScheduleEntry represents a single scheduled course slot.
 */
export interface ScheduleEntry {
    "ID": number;
    "CreatedAt": string;
    "UpdatedAt": string;
    "DeletedAt": gorm$0.DeletedAt;
    "courseId": number;
    "teacherId": number;
    "classroomId": number;

    /**
     * legacy FK, kept for backward compatibility
     */
    "classGroupId": number | null;

    /**
     * FK to TeachingTask, enables combined classes
     */
    "teachingTaskId": number | null;
    "semesterId": number;

    /**
     * 0=周一..6=周日
     */
    "dayOfWeek": DayOfWeek;

    /**
     * 0=第1节..10=第11节
     */
    "startPeriod": Period;

    /**
     * consecutive periods
     */
    "span": number;
    "weeks": string;

    /**
     * Associations
     */
    "course"?: Course;
    "teacher"?: Teacher;
    "classroom"?: Classroom;
    "classGroup"?: ClassGroup | null;
    "teachingTask"?: TeachingTask | null;
    "semester"?: Semester;
}

/**
 * ScheduleSnapshot captures a point-in-time evaluation of a schedule.
 * Generated automatically after scheduling or manually by user request.
 */
export interface ScheduleSnapshot {
    "ID": number;
    "CreatedAt": string;
    "UpdatedAt": string;
    "DeletedAt": gorm$0.DeletedAt;

    /**
     * 快照名称，创建时自动生成
     */
    "name": string;
    "semesterId": number;

    /**
     * 院系范围，空=全校
     */
    "dept": string;

    /**
     * "auto" | "manual"
     */
    "trigger": string;

    /**
     * Hard constraint pass/fail
     */
    "hardPassed": boolean;
    "teacherConflicts": number;
    "roomConflicts": number;
    "classConflicts": number;
    "lockedViolations": number;

    /**
     * Soft constraint scores (0-100 scale, weighted)
     */
    "totalScore": number;
    "teacherPref": number;
    "courseSpacing": number;
    "teacherDays": number;
    "lowFloorPref": number;
    "weekendAvoid": number;

    /**
     * 体育课时段偏好
     */
    "pePeriodPref": number;

    /**
     * 学生连续疲劳度
     */
    "studentFatigue": number;

    /**
     * 容量不足警告数
     */
    "capacityWarn": number;

    /**
     * Scoring configuration stored at snapshot time for reproducible re-scoring
     * JSON array
     */
    "enabledConstraints": string;
    "scoreVersion": number;

    /**
     * Statistics
     */
    "totalEntries": number;
    "solveTimeMs": number;
    "solver": string;
    "perCategoryMax": number;
    "enabledCategoryCount": number;

    /**
     * v0.5.2: placement completeness (append-only, Stable Core preserving).
     * FinalScore is the completeness-scaled published score (Total × completeness curve).
     * PlacedSessions / ExpectedSessions / Completeness expose the underlying ratio
     * used by the ScoreBreakdown at snapshot time.
     * Legacy snapshots (v0.4) leave these at zero — TotalScore keeps its meaning.
     */
    "finalScore": number;
    "placedSessions": number;
    "expectedSessions": number;
    "completeness": number;

    /**
     * Linked details
     */
    "details"?: SnapshotDetail[] | null;
}

/**
 * ScheduleVersion represents a user-facing historical schedule snapshot
 * containing the actual schedule entries at a point in time.
 * Unlike ScheduleSnapshot (which stores only aggregated statistics),
 * ScheduleVersion stores the full entry set so versions can be viewed,
 * restored, and compared independently of current schedule data.
 */
export interface ScheduleVersion {
    "ID": number;
    "CreatedAt": string;
    "UpdatedAt": string;
    "DeletedAt": gorm$0.DeletedAt;
    "semesterId": number;
    "name": string;

    /**
     * AutoGenerate | ManualAdjust | Import | Restore | Copy
     */
    "source": string;
    "score": number;
    "entryCount": number;

    /**
     * optional: which solver produced it
     */
    "solver": string;
    "entries"?: ScheduleVersionEntry[] | null;
}

/**
 * ScheduleVersionEntry stores a single course entry within a historical
 * schedule version. Fields mirror the main ScheduleEntry but are stored
 * independently so historical versions remain valid even if current
 * resource data (teachers, classrooms, etc.) is later modified or deleted.
 */
export interface ScheduleVersionEntry {
    "ID": number;
    "CreatedAt": string;
    "UpdatedAt": string;
    "DeletedAt": gorm$0.DeletedAt;
    "versionId": number;

    /**
     * optional: links back to the schedule_entry row at time of capture
     */
    "originalEntryId"?: number | null;
    "teachingTaskId"?: number | null;
    "courseId": number;
    "teacherId": number;
    "classroomId": number;
    "dayOfWeek": number;
    "startPeriod": number;
    "span": number;
    "weeks": string;
}

/**
 * Semester represents an academic semester.
 * v0.5.5: 重构为结构化学期模型，删除 Name/IsActive/string StartDate。
 */
export interface Semester {
    "ID": number;
    "CreatedAt": string;
    "UpdatedAt": string;
    "DeletedAt": gorm$0.DeletedAt;

    /**
     * "2025-2026"
     */
    "academicYear": string;

    /**
     * FIRST, SECOND
     */
    "term": string;

    /**
     * 学期第一周周一
     */
    "startDate": string;

    /**
     * 学期最后一天
     */
    "endDate": string;

    /**
     * active, archived, planned
     */
    "status": string;
}

/**
 * SnapshotDetail stores per-teacher/course score contributions for the report.
 */
export interface SnapshotDetail {
    "ID": number;
    "CreatedAt": string;
    "UpdatedAt": string;
    "DeletedAt": gorm$0.DeletedAt;
    "snapshotId": number;

    /**
     * "teacher" | "course"
     */
    "entityType": string;
    "entityCode": string;
    "entityName": string;

    /**
     * Per-constraint breakdown
     */
    "earlyPenalty": number;
    "latePenalty": number;
    "daysActual": number;
    "daysTarget": number;
    "avgFloor": number;
    "capacityWarning": boolean;

    /**
     * Schedule summary
     */
    "entryCount": number;
    "daysCount": number;

    /**
     * e.g. "周一1-2节,周三3-4节"
     */
    "summary": string;
}

/**
 * Teacher represents a teaching staff member.
 */
export interface Teacher {
    "ID": number;
    "CreatedAt": string;
    "UpdatedAt": string;
    "DeletedAt": gorm$0.DeletedAt;
    "code": string;
    "name": string;
    "dept": string;

    /**
     * active, inactive
     */
    "status": string;

    /**
     * Soft constraint preferences
     * 避免早课（1-2节）
     */
    "preferNoEarly": boolean;

    /**
     * 避免晚课（7-8节及晚上）
     */
    "preferNoLate": boolean;

    /**
     * 每周最多到校天数
     */
    "maxDaysPerWeek": number;

    /**
     * 优先低楼层
     */
    "preferLowFloor": boolean;

    /**
     * Per-teacher unavailable time slots (JSON array).
     * Each element: {"dayOfWeek":0-6, "startPeriod":0-10, "span":2-4}
     */
    "unavailableSlots": string;
}

/**
 * TeachingTask represents a teaching assignment: one course taught by one teacher
 * for one or more class groups in a specific semester.
 * This replaces the implicit department-based matching with explicit relationships.
 */
export interface TeachingTask {
    "ID": number;
    "CreatedAt": string;
    "UpdatedAt": string;
    "DeletedAt": gorm$0.DeletedAt;
    "courseId": number;
    "teacherId": number;
    "semesterId": number;

    /**
     * active, inactive
     */
    "status": string;

    /**
     * Time parameters for scheduling
     * 总学时（必填）
     */
    "totalHours": number;

    /**
     * 起始周（默认1）
     */
    "startWeek": number;

    /**
     * 结束周（默认16）
     */
    "endWeek": number;

    /**
     * 周最大学时（0=不限）
     */
    "maxHoursPerWeek": number;

    /**
     * v0.5.1: single-session span preference (HBUT). 0 = 不指定, 1/2/3 = 强制单次连排节次.
     * When >0 and legal under IsSpanLegal for at least one start, overrides the
     * hour-derived default from resolveSessionPlan. Illegal values fall back silently.
     */
    "preferredSpan": number;

    /**
     * +v0.5.3: 显式指定教室类型。空=由 Course.Category 推导。
     */
    "requiredRoomType": string;

    /**
     * +v0.5.3: 显式指定所需设备 JSON array，如 ["projector"]
     */
    "requiredEquipment": string;

    /**
     * Associations
     */
    "course"?: Course;
    "teacher"?: Teacher;
    "semester"?: Semester;
    "classes"?: TeachingTaskClass[] | null;
}

/**
 * TeachingTaskClass links a TeachingTask to its enrolled ClassGroups.
 * A composite unique index prevents duplicate bindings.
 */
export interface TeachingTaskClass {
    "ID": number;
    "CreatedAt": string;
    "UpdatedAt": string;
    "DeletedAt": gorm$0.DeletedAt;
    "teachingTaskId": number;
    "classGroupId": number;
    "classGroup"?: ClassGroup;
}
