// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as gorm$0 from "../../../gorm.io/gorm/models.js";

/**
 * ClassGroup represents a student class/group (e.g., 计算机2301).
 */
export interface ClassGroup {
    "ID": number;
    "CreatedAt": string;
    "UpdatedAt": string;
    "DeletedAt": gorm$0.DeletedAt;
    "code": string;
    "name": string;
    "dept": string;

    /**
     * 入学年份, e.g. 2023
     */
    "grade": number;

    /**
     * 学生人数
     */
    "students": number;

    /**
     * active, inactive
     */
    "status": string;
}

/**
 * Classroom represents a physical room for teaching.
 */
export interface Classroom {
    "ID": number;
    "CreatedAt": string;
    "UpdatedAt": string;
    "DeletedAt": gorm$0.DeletedAt;
    "code": string;
    "name": string;
    "building": string;

    /**
     * 楼层号
     */
    "floor": number;
    "capacity": number;

    /**
     * 普通教室, 实验室, 体育馆, etc.
     */
    "type": string;
    "status": string;
}

/**
 * Course represents a course in the curriculum.
 */
export interface Course {
    "ID": number;
    "CreatedAt": string;
    "UpdatedAt": string;
    "DeletedAt": gorm$0.DeletedAt;
    "code": string;
    "name": string;
    "dept": string;
    "credit": number;

    /**
     * 专业必修, 全校选修, etc.
     */
    "type": string;
    "hours": number;

    /**
     * active, inactive
     */
    "status": string;
}

/**
 * DayOfWeek represents a day in the teaching week (0 = Monday, 6 = Sunday).
 * This is the canonical internal representation throughout the system.
 * Display conversion (0→"周一", etc.) is handled by the frontend DAY_NAMES mapping.
 */
export enum DayOfWeek {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = 0,

    Mon = 0,
    Tue = 1,
    Wed = 2,
    Thu = 3,
    Fri = 4,
    Sat = 5,
    Sun = 6,
};

/**
 * Department represents a college/faculty (e.g., 计算机学院, 材料科学与工程学院).
 */
export interface Department {
    "ID": number;
    "CreatedAt": string;
    "UpdatedAt": string;
    "DeletedAt": gorm$0.DeletedAt;

    /**
     * 院系代码，如 "cs"
     */
    "code": string;

    /**
     * 院系名称，如 "计算机学院"
     */
    "name": string;
}

/**
 * Period represents a teaching period slot (0-indexed internal, 1-indexed for display).
 * Period 0 = 第1节, Period 9 = 第10节, etc.
 */
export type Period = number;

/**
 * ScheduleEntry represents a single scheduled course slot.
 */
export interface ScheduleEntry {
    "ID": number;
    "CreatedAt": string;
    "UpdatedAt": string;
    "DeletedAt": gorm$0.DeletedAt;
    "courseId": number;
    "teacherId": number;
    "classroomId": number;

    /**
     * legacy FK, kept for backward compatibility
     */
    "classGroupId": number | null;

    /**
     * FK to TeachingTask, enables combined classes
     */
    "teachingTaskId": number | null;
    "semester": string;

    /**
     * 0=周一..6=周日
     */
    "dayOfWeek": DayOfWeek;

    /**
     * 0=第1节..10=第11节
     */
    "startPeriod": Period;

    /**
     * consecutive periods
     */
    "span": number;
    "weeks": string;

    /**
     * Associations
     */
    "course"?: Course;
    "teacher"?: Teacher;
    "classroom"?: Classroom;
    "classGroup"?: ClassGroup | null;
    "teachingTask"?: TeachingTask | null;
}

/**
 * ScheduleSnapshot captures a point-in-time evaluation of a schedule.
 * Generated automatically after scheduling or manually by user request.
 */
export interface ScheduleSnapshot {
    "ID": number;
    "CreatedAt": string;
    "UpdatedAt": string;
    "DeletedAt": gorm$0.DeletedAt;

    /**
     * 快照名称，创建时自动生成
     */
    "name": string;
    "semester": string;

    /**
     * 院系范围，空=全校
     */
    "dept": string;

    /**
     * "auto" | "manual"
     */
    "trigger": string;

    /**
     * Hard constraint pass/fail
     */
    "hardPassed": boolean;
    "teacherConflicts": number;
    "roomConflicts": number;
    "classConflicts": number;
    "lockedViolations": number;

    /**
     * Soft constraint scores (0-100 scale, weighted)
     */
    "totalScore": number;
    "teacherPref": number;
    "courseSpacing": number;
    "teacherDays": number;
    "lowFloorPref": number;
    "weekendAvoid": number;

    /**
     * 体育课时段偏好
     */
    "pePeriodPref": number;

    /**
     * 学生连续疲劳度
     */
    "studentFatigue": number;

    /**
     * 容量不足警告数
     */
    "capacityWarn": number;

    /**
     * Scoring configuration stored at snapshot time for reproducible re-scoring
     * JSON array
     */
    "enabledConstraints": string;
    "scoreVersion": number;

    /**
     * Statistics
     */
    "totalEntries": number;
    "solveTimeMs": number;
    "solver": string;
    "perCategoryMax": number;
    "enabledCategoryCount": number;

    /**
     * Linked details
     */
    "details"?: SnapshotDetail[] | null;
}

/**
 * ScheduleVersion represents a user-facing historical schedule snapshot
 * containing the actual schedule entries at a point in time.
 * Unlike ScheduleSnapshot (which stores only aggregated statistics),
 * ScheduleVersion stores the full entry set so versions can be viewed,
 * restored, and compared independently of current schedule data.
 */
export interface ScheduleVersion {
    "ID": number;
    "CreatedAt": string;
    "UpdatedAt": string;
    "DeletedAt": gorm$0.DeletedAt;
    "semesterId": number;
    "name": string;

    /**
     * AutoGenerate | ManualAdjust | Import | Restore | Copy
     */
    "source": string;
    "score": number;
    "entryCount": number;

    /**
     * optional: which solver produced it
     */
    "solver": string;
    "entries"?: ScheduleVersionEntry[] | null;
}

/**
 * ScheduleVersionEntry stores a single course entry within a historical
 * schedule version. Fields mirror the main ScheduleEntry but are stored
 * independently so historical versions remain valid even if current
 * resource data (teachers, classrooms, etc.) is later modified or deleted.
 */
export interface ScheduleVersionEntry {
    "ID": number;
    "CreatedAt": string;
    "UpdatedAt": string;
    "DeletedAt": gorm$0.DeletedAt;
    "versionId": number;

    /**
     * optional: links back to the schedule_entry row at time of capture
     */
    "originalEntryId"?: number | null;
    "teachingTaskId"?: number | null;
    "courseId": number;
    "teacherId": number;
    "classroomId": number;
    "dayOfWeek": number;
    "startPeriod": number;
    "span": number;
    "weeks": string;
}

/**
 * Semester represents an academic semester.
 */
export interface Semester {
    "ID": number;
    "CreatedAt": string;
    "UpdatedAt": string;
    "DeletedAt": gorm$0.DeletedAt;
    "name": string;
    "isActive": boolean;

    /**
     * e.g. "2025-09-01", determines day-to-date mapping
     */
    "startDate": string;
}

/**
 * SnapshotDetail stores per-teacher/course score contributions for the report.
 */
export interface SnapshotDetail {
    "ID": number;
    "CreatedAt": string;
    "UpdatedAt": string;
    "DeletedAt": gorm$0.DeletedAt;
    "snapshotId": number;

    /**
     * "teacher" | "course"
     */
    "entityType": string;
    "entityCode": string;
    "entityName": string;

    /**
     * Per-constraint breakdown
     */
    "earlyPenalty": number;
    "latePenalty": number;
    "daysActual": number;
    "daysTarget": number;
    "avgFloor": number;
    "capacityWarning": boolean;

    /**
     * Schedule summary
     */
    "entryCount": number;
    "daysCount": number;

    /**
     * e.g. "周一1-2节,周三3-4节"
     */
    "summary": string;
}

/**
 * Teacher represents a teaching staff member.
 */
export interface Teacher {
    "ID": number;
    "CreatedAt": string;
    "UpdatedAt": string;
    "DeletedAt": gorm$0.DeletedAt;
    "code": string;
    "name": string;
    "dept": string;

    /**
     * active, inactive
     */
    "status": string;

    /**
     * Soft constraint preferences
     * 避免早课（1-2节）
     */
    "preferNoEarly": boolean;

    /**
     * 避免晚课（7-8节及晚上）
     */
    "preferNoLate": boolean;

    /**
     * 每周最多到校天数
     */
    "maxDaysPerWeek": number;

    /**
     * 优先低楼层
     */
    "preferLowFloor": boolean;

    /**
     * Per-teacher unavailable time slots (JSON array).
     * Each element: {"dayOfWeek":0-6, "startPeriod":0-10, "span":2-4}
     */
    "unavailableSlots": string;
}

/**
 * TeachingTask represents a teaching assignment: one course taught by one teacher
 * for one or more class groups in a specific semester.
 * This replaces the implicit department-based matching with explicit relationships.
 */
export interface TeachingTask {
    "ID": number;
    "CreatedAt": string;
    "UpdatedAt": string;
    "DeletedAt": gorm$0.DeletedAt;
    "courseId": number;
    "teacherId": number;
    "semesterId": number;

    /**
     * active, inactive
     */
    "status": string;

    /**
     * Time parameters for scheduling
     * 总学时（必填）
     */
    "totalHours": number;

    /**
     * 起始周（默认1）
     */
    "startWeek": number;

    /**
     * 结束周（默认16）
     */
    "endWeek": number;

    /**
     * 周最大学时（0=不限）
     */
    "maxHoursPerWeek": number;

    /**
     * Associations
     */
    "course"?: Course;
    "teacher"?: Teacher;
    "semester"?: Semester;
    "classes"?: TeachingTaskClass[] | null;
}

/**
 * TeachingTaskClass links a TeachingTask to its enrolled ClassGroups.
 * A composite unique index prevents duplicate bindings.
 */
export interface TeachingTaskClass {
    "ID": number;
    "CreatedAt": string;
    "UpdatedAt": string;
    "DeletedAt": gorm$0.DeletedAt;
    "teachingTaskId": number;
    "classGroupId": number;
    "classGroup"?: ClassGroup;
}
